---
title: "USdatadiscreps"
author: "jim"
date: "22/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Discrepencies to Decode ##

<p>
1950 USA published census looks better than the USCenPE-11 spreadsheet. The latter exhibits male-biased age heaping of one-year-olds (0.77 = SR1t2 minus SR0t1 ), with the census-difference (0.23= SR1t3 - SR0t1).  And for the Black age-heaping is 3.3 points!
</p>

### PUMS vs cenVols

<p>
 -- key anomolies: 
NewEng: SR5 fPMUS vs cenV 1850 and 1870 are discrepent in opposite directions, creating big noise for possible trend. 1850 +0.5; 1860 0; 1870 -0.4; 1880 -0.2; 1900 +.2; 1910 -0.6; 1920 +0.3; 1930 0; 1940 -0.4    </p>

Look at 1850 for (1) Mass  and then (2) state by state

Look at state census for  1865 1875         1905 1915  relative to census/pums discreps
and look at 1885 1895 for 1890 ...

1875 census SR was  huge outlier .... JIM FIXED TABULATION ERROR -- 1yrold female total is 2000 too high

MASS SR5  CONCERNS -- 1850 1870  1910  (and 1920, 1930)
1850 PUMS is 0.7 over census (101.6)
1860 PUMS is 0.2 over census (101.3)
  1870 PUMS is 0.7 under census (101.5)
1880 PUMS is 0.2 under census (102.2)
1900 PUMS is 0.2 over census (101.1)
1910 PUMS is 0.5 under census (102.0)
1920 PUMS is 0.3 over  census (101.7)
1930 PUMS is same as census   (103.2) 
1940 PUMS is 0.3 under census (104.0)

Mass 1865 state census has SR2 >> SR5 (SR2 102.9  SR5 101.3)  1.6 points!
 
 
 

NewEng  ?SR2? 1870 fPUMS -.5  1910 -.7  1920 +.5 1940 -.6




1850 SR is much higher in PUMS than in census volumes.
E.g. whites
SR(1to4) PUMS 103.7  Census 103.3  +0.4
SR(0yrs) PUMS 103.9  Census 103.4  +0.5
SR(1yrs) PUMS 105.2  census N/A
SR(2yrs) PUMS 103.8  census N/A

South Atlantic PUMS 0 is 0.7 above census; 0 is +0.7 1to4 is +0.4 above census; and age 1 has SR 108.1
Possible revision is to use SR3 -- aggregation reducing noise? (see MakingBestJudgements.xls)

... u5 is 0.5 high -- what if we simply used PUMS minus 0.5 ?
 

Most of the divergence of our census-based estimate versus the PUMS is because we assume the SR(1-2) is the same as the SR(1-4), but in the PUMS the latter 1.5 points higher.
To make them comparable, we can use the PUMS's proportions of age1 in ages 1to4 for males and females. Census is still lower, but they are more comparable. Alternatively, we could deem the PUMS erroneous, and use the same 1/4 of 1to4 as the age1 estimate in PUMS and cenVo. DECISION: use PUMS as is; for cenVol estimate 1 is 1/4 of 1to4 (don't impose PUMS SR on the cenVol)

<p>1870 Franklin MA age0 348 349  age1      total    fullpums
SEEMS Jim missed 1 yr olds when sibling of 0-yr-old? If contemps did same, would that explain the fPUMS/cenVol discrep?
</p>

## 1890 census anomalies

<p>1890 issues: SR2 values look implausible ... but some SR5s seem only modestly too high (0.1 above 1880 values -- but I suspect the decline of the true SR from 1880 to 1890 is masked). Probably SouAtl looks worst, NewEng best (and via Mass state census, Mass 1890 looks ok?).
</p><p>Mass SRs
1880 102.3 102.2;  1885 101.7 101.0; 1890 101.3 101.3; 1895 101.3 101.1; 1900 100.9, 100.9   
<p>1890 New England SR5 works, to replace the goofy high (103.0) from under-sized u2 count. New England is simple -- extrapolate on U5 counts and 1890 SR is same as 1880, and we see simple decline from 102 1850-1890 to below 101 in 1900, recovering after 1920 and moving to a new high in 1930. SR5 tells same story as SR2, except for the 1890 SR2.</p>

<p>Middle Atlantic SR5 works, again to replace goofy high (103.1) SR2. SR5 about the same as in 1880 (0.1 higher, at 102.5); and full 1-point drop of SR5 from 1890 to 1900. -- as with New England, under-sized U2 count with high SR (103.1). Undersized insomuch as U5 population swells 9% but U2 count falls 3%.
</p><p>ENC 1880 to 1890 SR5 rises 0.5 pts, but SR2 again seems biased upward in an undersized count (u2 pop falls, as U5 increases 12%) from 

  <br> 1900 & 1910 census volumes discuss problems with the 1890 enumeration of young ages, casting doubt on the categorization of infants and young chhildren. Unfortunately, manuscripts not available (fire destroyed?); so no MS sample to corroborate or correct the published volunes.


</p><p>ENC 1890 SRs look high (SR2 104.2 esp, also SR5 at 103.4). 1860-1880 we see SR5 of 102.9-103.0; 1900 is 102.3. The 1890 census gives us a 0.5-point rise, followed by 1.1-point drop. This occurring as Chicago, Cinnci, Clevel, Detroit, Milwauk, Indianap, 
Columbus, Toledo, Dayton, Gr Raps all probably double in size, while the pop grows maybe 10%. So maybe %urban goes from  25/100 to 50/110 or 25% to 45% And that would pull down SRs</p>
<p>Chicago looks at least 1-point too high. So Jim has a look.
<br>for 1880,  1890,  1900, consider the Illinois SR5 for Chicago/NonChicago
<br> (1880 101.3 vs 103.2) (1890 102.3 vs 103.6) (1900 100.6 vs 102.2)
So 1880 to 1900, Chicago SR2 falls 0.7, 101.3 to 100.6, as population triples+ . But the 1890 census tells us Chicago's SR jumped 1 point then dropped 1.7. Seems like crap/noise. Via 1880, 1890 census, u5dr about constant ...
<br>
Chicago has 16% of Illinois's u5 population (SR 101.3, rest of Ill 103.2), and in 1890, that share has risen to 30% (1900 35%)  </p><p>via Higgs 1979, Hoffman's CDR for cities, <br>
p31 Chicago 1871-74 18-31; 1878-81 16-26   1888-91 17-24   1898-1901 14-16 But with population doubling 1880 to 1890, what do we make of that? And 1890 to 1900, pop grows 1.54 while u5 grows only 1.36  --- which would tend to push down the CDR. 


<p>Maybe Jim propose estimates of 1890 U2 by region, accepting the U5 values, but reshuffling among ages by distributing girls-by-age from a life table, then distributing boys via ?
DETAILS: 1890 census age-question was newly worded, and the 1900 and 1910 census volumes include discussion of the resulting problems in counts at age 0 and 5 (far fewer than usual at 4, extra at 5, because age at nearest birthday take 4.51 yrs to 5). I thinking we take the 0to5 or 0to4 population, and allocate it to ages
to replicate a life-table pattern consistent with the observed over 0to5 (U5+5) sex ratio. For example, New England's 1890 SR06 is 102.0  and the SR5 is 102.1  -- we'll use the latter (against my prior, that lower makes more sense in 1890).  209,170 u5girls.  
</p>