---
title: "SSMM-US-data: sources for US for the SSMM/CSR Project "
author: "jri, with jrm"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
  
<a name="TOC"></a>

<p> [DRA & census vital stats](#DRAsect)   Census volumes [1940 volumes](#1940US),  ([state of MASS](#MASS))), 
  </p>

this pulled from bigger datasources 2022.0905

### USA ###

<p>**Spreadsheets** USAkidsForR.xls has national totals; US-KIDSFORR.XLS has state and finer data (and starts with national total white pops 1900-1980), but see also each wrangling/raw for US data used for specific projects. Old (2021.0604) Age25censRegns.xls compiles regional data, NewEng, MidAtl, SouAtl; but often does not give source. I suspect I totalled up the state-level. And it does not isolate white populations except for South</p>

PUMS   -- to cite:  Steven Ruggles, Sarah Flood, Sophia Foster, Ronald Goeken, Jose Pacas, Megan Schouweiler and Matthew Sobek. IPUMS USA: Version 11.0 [dataset]. Minneapolis, MN: IPUMS, 2021. https://doi.org/10.18128/D010.V11.0    

<p>[city codes](https://usa.ipums.org/usa-action/variables/CITY#codes_section) Boston 0810    NewYork 4610 (Brooklyn 4611)  Phil 5330 (1850: 5331-35)  Chicago 1190    Baltimore 530   NewOrleans 4570  Cleveland 1330    Detroit  1750     <br>
[State Codes](https://usa.ipums.org/usa-action/variables/STATEICP#codes_section)</p>

[Region codes](https://cps.ipums.org/cps-action/variables/REGION#codes_section)     
Northeast: 11 New England, 12 Middle Atlantic ; Midwest 21 ENC  22 WNC    
South: 31 SouAtl, 32 ESC, 33 WSC;    
West: 41 Mountain, 42 Pacific


#### SR Population Counts -- checking for inconsistencies

Grove & Lindner (VS1900-40) have states' u1 u5 pops by sex starting pdf885- p872  (Supplement Population Tables USA). This show 1930 & 1940 as in 1940 census -- so VS probably good for white IM etc

   1900-04 t vii by months

<p>PUMS data extracts (on Jim's computer or drive)   </p>
<p>National **white** SR5 discrepencies over 0.1% --  1870 PUMS is 0.3 less male **important** insomuch as it is against our findings;   
1850 fPUMS 103.72  cenVol 103.35  PUMS 0.37% more male (more healthy) -- not likely important; could strengthen ours     
1870 fPUMS 103.04  cenVol 103.34  PUMS 0.30% less male (less healthy) -- potential to weaken our results;   
1900 fPUMS 102.50  cenvol 102.64
1910 fPUMS 102.50  cenVol 102.93  PUMS 0.43% less male (less healthy) -- potential to clarify?

</p><p>1870 
recall that for whites, PUMS 1870 (103.04) is 0.30% less male than the published volume.     

1870 MASS all SR5 fPUMS (100.8) is 0.74 less male than cenVol (101.53). But 1875 state census is 100.9 and 1865 is 101.3. So the 1870 cenVol SR5 may seem high? 
1870 MASS whites SR5 fPUMS ()  is 0.7% less male than CenVol. Looking at single years of age, age 0 is most dramatic, it is 1.7% less male ... if the PUMS SR0 had the cen value, then Mass would be just 0.2 less male ... And that is a matter of 141 infants being moved from female to male ... out of almost 33K infants ...    
Looking at counties, Norfolk is largeish with low male SR 93 with 2K infants; but random sample finds fem-tilt (10/21 in pure random; fuller sample 28/37 ).  Maybe there is a large county that undercounted males in some part? Would need much luck, or district-level PUMS ...      
e.g Boston Wd10 start at i100.     
Age0 91 1 0, 92 0 1, 93 0 0, 94 0 1, 95-103 0 0; 104 0 1, 105 0 0, 106 2 0;  188 1 0, 189 0 0, 190 0 0, 191 1 0, 192 2 0
1870 SR5 all   -- will restricting to white narrow the discreps?
NJ cenVol 102.2 PUMS 101.7  PUMS 0.5% less male; white 0.6% less male (102.4 101.8)     
NY cenVol 101.9 PUMS 101.6  PUMS 0.32% less male; white 0.32% less (101.96 101.63)    
PA cenVol 101.9 PUMS 101.2  PUMS 0.7% less male; white 0.76 less (102.03  101.26)     
MiddAtl whites SR5 PUMS is 0.54% less male than the published census

</p>

<p>1880 -- via Mass IMR prediction, 1880 Mass seems much more male than other years. Both cVol & PUMS are more male (2%)
</p>


<p>**discrepencies** between fPUMS and published volumes include <br>Mass SR5 f-101.5 c-102.0 ; <br>NY white SR5 f-101.4 c-102.1 (SR2 101.9 102.9) ... when time, Jim to randomly sample ...

</p><p> 1920 white SRs 
<br>PUMS above Census -- 
MD SR5p 0.4 above census (102.6 102.2); SR2p same (103.7 103.7)
MA SR5p 0.3 above census (102.1  101.8); SR2p 0.6 above census (101.7 101.1). Ji checked and it seems correct.   
WA SRp 0.3 above census (104.4  104.1); SR2p 0.5 above census (103.8 103.3) 
PA SR5,SR2 0.3 above census (sr5 101.9 101.6 ; sr2 102.2 101.9)    
NC SR5p 0.2 above census (104.2 104.0); SR2p 0.2 above (104.5 104.3)
NY SR5p 0.2 above census; SR2-P 0.3 above (SR5 102.7 102.5; SR2 102.2 101.9)     
OH SR5p 0.2 above census (103.3 103.1)      
MN SR5p 0.1 above census (102.9 102.8); SR2p 0.2 above census (103.4 103.2)
KT SR5p 0.1 above census (103.9 103.8); SR2p 0.1 above census (104.1 104.0)
IN SRp 0.1 above census (102.5 102.4); SR2p 0.1 below census (102.9 103.0) 
CT SR5p same; SR2 0.6 above census (102.5 vs 101.9); SR25-P must be well below?    
MI SR5p same (102.9); SR2p 0.2 above (102.7 102.5)  
VA SR5p same (102.4); SR2p 0.3 above (102.3 102.0) 
WI SR5p same (102.9); SR2p 0.1 below (102.8 102,9)<br>  
KS SR5p 0.4 below census (103.0 103.4), SR2p 0.9 below census (102.0 102.9)
Small state results
ME SR5p 0.3 above census (103.1  102.8); SR2p 0.3 above census (103.3 103.0); u5 ~75k
UT SR5p 0.2 above census (103.3  103.1); SR2p 0.3 below census (103.4 103.7); u5 ~60k (Ji checked u2, cen has 104.0)
RI SR5p 0.5 above census (101.4 100.9); SR2p 0.6 above census (101.8 101.2)
NH SR5p 0.5 above census (102.7 102.2); SR2p 0.1 above (102.5 102.4) -- small state, u5 41k
VT SR5p 0.3 above census (103.1  102.8); SR2p 0.2 above (104.0 103.8)  -- small state, u5 34.5k     
DC SR5p 0.3 below census (101.6  101.9); SR2p 0.7 above (103.9 103.6) -- very small place, u5 23k

</p><p>1930 white SRs -- *Arizona* alerts us to potential problem with category "white" in published census versus the PUMS.  VS (vital statistics) and census both seem to group "Mexican" in "colored". 
<br>1930VS has 438K total, comprised of 266K white and 172K colored ;
<br>census has 436K total, comprised of 264K white and 171K nonwhite (11 negro, 114 mexican, 44 indian)
<br>The 1929VS estimated pop of 1929 is 372K and 56K colored;  1931 269 174;
<br>  
<br>1930 census has 1930 white SR5 103.59 (n= 9,927,396) for US -- smaller pop b/c "Mexican" classed as nonwhite.
<br>1940 census has 1930 white SR5 103.51 (n=10,142,169) for US -- Mexican in "white"
<br>1970 census has 1930 white SR5 103.50 (n=10,151,119) for US (same in 1980 census, T45)
</p>
<p> Total pops 
 1940 1980cen 103.2; also that in pe11, hmdinput; HMDdata 103.1;    -- 1940census 103.2
 1950 1980cen 103.9; also that in pe11, hmdinput, HMDdata, 1950cen 
 1960 1980cen 103.4; also that in pe11, hmdinput, HMDdata, 1960cen
 1970 1980cen 104.0; also that in pe11,  hmdinput, 1970cen (HMDdata 103.9)    


US-IMR USA-IMR US infant mortality

<H2> USA IMR  </H2>

HSUS Series Ab9^[Haines, Michael R. , "Fertility and mortality, by race: 1800-2000." Table Ab1-10 in Historical Statistics of the United States, Earliest Times to the Present: Millennial Edition, edited by Susan B. Carter, Scott Sigmund Gartner, Michael R. Haines, Alan L. Olmstead, Richard Sutch, and Gavin Wright. New York: Cambridge University Press, 2006. http://dx.doi.org/10.1017/ISBN-9780511132971.Ab1-39] (white IMR) Footnote #2 on dates 1900 and 1910: 

    For the expectation of life at birth and the infant mortality rate, the values for 1900 and 1910 are from approximately 1895 and 1904, respectively.


HSUS Ab31-37 shows BRA and DRA populations and % of US totals.       
BRA 1924 76.2%, DRA 1918 76.6%; BRA 1928 94.3%, 1927 90.0% ;  

Our key source is the web page [Vital Statistics for 1890-1938 ](https://www.cdc.gov/nchs/products/vsus/vsus_1890_1938.htm). These mostly annual volumes are Mortality Statistics for the DRA and Birth Statistics for the BRA.  But the Censuses before 1930 provide additional births data, in the context of their production of life tables.

HSUS (1976) [Vital Statistics and Health and Medical Care](https://www2.census.gov/library/publications/1975/compendia/hist_stats_colonial-1970/hist_stats_colonial-1970p1-chB.pdf). Vital Statistics (Series B 1-220). Series B 142-144 Infant mortality rate, by, race, 1915-1970. Source: U.S. Public Health Service, 1915-1939, Vital Statistics--Special Reports, vol. 45, No. 1, p7. ({I find it at Google via Hathi. Odd that they don't cite Linder & Grove, as in the 1957 edition}). 1940-70 from Vital Statistics of the US: 1940-67 in VSUS, 1967, vol. 11, Part A, p. 2-3; 1968-70 VSUS annual issues.    

1915-1932 Birth Registration Area only.  1915 99.9  1916 101.0   1931-61.6 1932-57.6  1933-58.1   -- same values in Linder & Grove.     
<br>p44 B 1-220. General note.  
<br>A two-part compendium updating and expanding the second edition, Historical Statistics of the United States, Colonial Times to 1957. 
<br> US Bureau of the Census, *Historical Statistics of the United States, Colonial Times to 1970,Bicentennial Edition, Part 1*, Washington, D.C., 1975.

<p>June 1959 [Historical Statistics of the United States, 1789 - 1957](https://www.census.gov/library/publications/1949/compendia/hist_stats_1789-1945.html)9-
<br>Cites Linder & Grove for IMR. 
</p>

<br>[NVSS HIST293](https://www.cdc.gov/nchs/nvss/mortality/hist293.htm) offers data and discussion about US mortality statistics (DRA 1900-32, USA 1933-98) 

<br>This [page](https://www.cdc.gov/nchs/nvss/mortality/hist293.htm) about VS history attributes to  
[Hetzel AM](https://www.cdc.gov/nchs/data/misc/usvss.pdf) U.S. Vital Statistics System Major Activities and Developments, 1950-95. 72 pp. (PHS) 97-1003 pdf icon[PDF – 724 KB]

<p>CDC NCHS [Vital Statistics](https://www.cdc.gov/nchs/products/vsus.htm) e.g. [1890-1938](https://www.cdc.gov/nchs/products/vsus/vsus_1890_1938.htm)
</p>

<p>CDC weekly [Achievements in Public Health, 1900-1999: Healthier Mothers and Babies](https://www.cdc.gov/mmwr/preview/mmwrhtml/mm4838a2.htm)
</p>


**later 20th C sources **

CDC Deaths 2017 Infant mortality 

Bell&Miller Life Tables, Table 6 is "Period Life Tables" and 1900 has male e0x 46.41 (p26); Table 7 is "Cohort Life Tables" and 1900 has e0x (p89) 51.52 

<p>Life Table [2005](https://pubmed.ncbi.nlm.nih.gov/20578408/)  [1992 Vital Stats](https://www.cdc.gov/nchs/data/vsus/mort92_2a.pdf) for HSUS IMR 1915 on. pdf p507 

[1961 Vital Stats](https://www.cdc.gov/nchs/data/vsus/vsus_1961_1.pdf) live-births by sex, 1-28, pdf 
1962 t15 pdf       pg 1-30 pdf38 by state

[1950](https://www.cdc.gov/nchs/data/vsus/vsus_1950_1.pdf) p81 (pdf 91) offers SRB for 1935-1950, for all/white/nonwhite.  E.g. 1940 white 106.0    But I worry Southern whites tend to inflate the national average?
</p>


#### CDC "Births:Final Data for 20xx ####

annual [Health](https://www.cdc.gov/nchs/hus/previous.htm
https://search.cdc.gov/search/index.html?query=%22sex%20ratio%22&sitelimit=NCHS&exact=sex%20ratio%20at%20birth#results) reports.

https://www.cdc.gov/nchs/products/vsus/vsus_1980_2003.htm
vital stats don't have births by sex

[National Vital Statistics  Reports](<https://www.cdc.gov/nchs/products/nvsr.htm>). (Births)
Most recent (as of 2020 May) seems to be 2018 (SBRs  1.046all 1.052white 1.029black 1.063Asian 1.036Hispanic 1.036Amerind/Alaska 1.022PacficIsle). Looking for SRB discussion later than 2001 report (not 2018, 2015,  YES: 2005 noting downward trend 1970s to 2002 -- citing Mathews&Hamilton (2005 CDC)

Mathews&Hamilton (2005 CDC) [Trend analysis of sex ratio at birth in the United States](<https://www.cdc.gov/nchs/data/nvsr/nvsr53/nvsr53_20.pdf>). Quick read by Jim indicates they don't place a welfare interpretation on the declining SBR 1970s to 2000 ...  1.050  "In 2002 the sex ratio reported for fetal loss was higher than for live births (1,128 compared with 1,048)" 1.0763 -- CDC data

Matin, Hamilton, et al. [Births 2001 (CDC 2002)](<https://data.nber.org/natality/2001/docs/nvsr51_02.pdf>). p8 1046 p9 .... 


### USA data on/for Infant Mortality to 1940  (1890, 1900-04, 1900-05, 1900-40)

2021Nov02 CENSUS DAY CENSUS DATES 1850-1900 June 1 (1890 June 2); 1910 April 15; 1920 Jan 1; 1930 onward, Apr 1. 


<p>CDC NCHS [Vital Statistics](https://www.cdc.gov/nchs/products/vsus.htm) e.g. [1890-1938](https://www.cdc.gov/nchs/products/vsus/vsus_1890_1938.htm)
<br>[1900-1970](www.census.gov/data/tables/time-series/demo/popest/pre-1980-national.html)  
</p>

<p>[1900-1940 Vital Statistics Data](https://data.nber.org/vital-stats-books/vsrates1900_40.CV.pdf) Probably Linder & Grove? IMR Tables 26 to 35. Table 26 IMR by state  But these don't have birth counts? (for GLS weighting)
p572. I'm looking for SRB data -- not Table 53, which gives total births (and IMR data) at various geographic levels. Not Table 50, crude birth rates by month;    </p>

Children's Bureau
Montclair NJ, Baltimore MD, Waterbury CT, Johnstown PA, Manchester NH, Brockton MA, NewBedford MA  
Also Pittsburgh 1920, Memphis

Duncan BS, Duke E. 1917. Infant mortality: Results of a field study in Manchester, N.H. based in births in one year. Washington, DC: U.S. Government Printing Office, 134 pp. (Children's Bureau publication; no. 20; Infant mortality series; no. 6)

### BRA/DRA data

Our data:  1915-1920  urb/rur births and u1deaths.  ALabama 1925 on deaths; IMR 1927 on.  AZ 1925 on deaths; IMR 1926-30.   DE    
FL  GA 1928 onward, BRA (not in DRA before that). Atlanta in DRA earlier ...  
IL DRA 1918-1920  Chicago 1915-1920  BRA-IMR 1922on ; IN DRA 1915-; MD BRA     1916+    DRA     1915+ ;
MA BRA  1915+  ;  MN 1915-1920 can do white urb/rur  or do folk=all and Minneapolis-StPaul as 1 place and it is a metro (>600K)  for metro/urb106/rur10  /    ... 1930 is next ... 

MO 1925+ white urb/rur (StL < 500K)

NJ 1925-1930  Newark ~400K so we could split it off
NC Not 1915-1920 -- anomalous geog coverage ...

2022.0309 Considering state-level IMR:SR   -- NY is in the DRA from 1890


[1900](https://www.census.gov/history/www/through_the_decades/overview/1900.html) June 1; 


DRA 1910 we could estimate IMR via u1 deaths, u1 pop, separation factor. But worry about u1 counts -- better use u5?
  1910 u5 boys 3145145.0      eIMR 107.45935 (m&f)     
1910 builds from USimrDRA1910.RDS 16June2021, which is with USimrBRA.RDS in Wrangling/Raw/US ...
USimrDRA1910.RDS   Note we have only 1 yr of IMR data to connect to SR (so use SR2?)

Dempap uses full BRA. BRA data for IMR 1920, 1930 -- US totals (but 1920 is Jan 1, so 1920 refers to 1919; before 2021Nov 2, 1920 erroneously included some 1920 IMR). Ji also looked at US-North 1920 (excludes DC) amd   1930 US-North US-Sou-white US-Sou-black.        

USimrBRA.RDS is simply the BRA part of USimr-BRA.xls (which covers 1915-1931); that RDS file was made by EstUSimrDRA.R, and that file reads the u1 deaths counts from USimr-BRA.xls (top part of which is the BRA data) and merges them with the u1 pop counts in US1910SR1.RDS (which was created from 1910 PUMS full-count in 2nd part of buildPUMSurb10.R). That SR1 file has 27 states (tot/urb10k, rur10k)

u2u5forBRAimr.RDS 

For 1915 to 1930 (for census SRs of 1920 and 1930), we get IMR by state/race from [Lindner & Grove (1943)](https://www.cdc.gov/nchs/nvss/mortality/hist293.htm#:~:text=Lindner%20FE%2C%20Grove,the%20Census.%201943%3B) Vital statistics rates in the United States, 1900-1940. We use annual Birth Statistics pubs to get birth counts. Oddly, [Hetzel's](https://www.cdc.gov/nchs/products/other/miscpub/vsushist.htm) history of US vital statistics systems has SC starting in DRA 1916 and BRA 1919, yet SC not in Birth Stats 1926     

South: 1925-1930 DC (6 2.8) DE (3.6 0.7) FL (20 9) KT (53 3.5) MD (24 6) NC (53 24) VA (38 16) WV (38 2) 

1925 birth stats (google books or Hathi)  pdf 33 has table with legit & illegit by state, but not total births ...       
Va 1917      
Ala Ark La Tn are 1927 onward, so could relate them to SR2 ...   GA 1928 


<p> **Birth Statistics for the BRA**    

[Maybe a full set](https://catalog.hathitrust.org/Record/003923081) at HathiTrust

[1915](https://babel.hathitrust.org/cgi/pt?id=uiug.30112051430939&view=1up&seq=9) [1916](https://babel.hathitrust.org/cgi/pt?id=hvd.li4xnm&view=1up&seq=5), IMRs pdf 8-17 
[1917](https://babel.hathitrust.org/cgi/pt?id=hvd.li4xnn&view=1up&seq=5) has link to Google books for download.   pdf 28-61 (in digLib)

1918 pdf44-75 for Table 1   1919 pdf 42-61

Library of Congress site has pdf of [Infant mortality in the birth registration area of the United States: 1920](https://www.loc.gov/item/21027433/)

[1921](https://babel.hathitrust.org/cgi/pt?id=uiug.30112002972542&view=1up&seq=7)   [1922](https://babel.hathitrust.org/cgi/pt?id=uiug.30112051430954&view=1up&seq=9)

1919  Table 1 "rural" excludes municipalities 10K+ in 1910;   66p61 Table III  -76p71 Table IV    

1925 T22 for cities? 195-233 
1926 pdf10 TOC  Table I pdf 16-20?   Table 1 Births by month (no Brooklyn; nor race)


1927 Table 1 pdf349-354   (pdf has 2 vols, 1926 & 1927)  cities f354-364 10-30k

[1928](https://babel.hathitrust.org/cgi/pt?id=uiug.30112002972575&view=1up&seq=7) Tab 1 pdf 55-  Looking for Brooklyn     maybe Brooklyn 247-297

      

[1929](https://babel.hathitrust.org/cgi/pt?id=uiuo.ark:/13960/t3521c56x&view=1up&seq=27&size=150) Downloaded. Table 1 pdf 53-59   Reg. cities 52-67  f59-74  f53- 



1930 BRA      T1    pdf -145  f280 T10 stillbirths,   T21 day/month U1 deaths

[1931](https://www.cdc.gov/nchs/data/vsushistorical/birthstat_1931.pdf) IMRs pdf 51-102


<p> For 1930, Birth, Stillbirth, and Infant Mortality Statistics for the Birth Registration Area, [1930](https://www.google.ca/books/edition/Birth_Stillbirth_and_Infant_Mortality_St/yM3cOoJMf2UC?hl=en&gbpv=0) (difficult to find, I downloaded from GoogleBooks). For 1931 we have both the B-SB-IM-BRA and Mortality Statistics, and they give same u1 death count for Illinois (which serves to confirm same data, for me)    
     -17 Stillbirths; Tables 18-20 cover whole BRA;   
  Table 21 give State-level deaths by causes, and by ages (u1day, 1, 2, 3-6 days, 1wk etc)     
Table 22 gives States' total/cities/incorps/rural with >10K and >2.5k as cutoffs.  And deaths are by sex. 

Table 23 has that same 3-way breakdown, for deaths by days/weeks/months




 [Mortality Rates 1910-1920](https://www.cdc.gov/nchs/data/vsushistorical/mortrates_1910-1920.pdf)  438pdf436 Calif influenza. 
       
1920 BRA  Michigan cities have new cities versus 1919 -- Hamtramck 1851 births, Highland Park 845, Owosso 277, Wyandotte 492 but  loses Manistee 135 births, Menonimee 240 births,   -- Net change ~ 3100

NC 1920 vs 1919 -- 28% increase in births in the 1919 places?  1920 1/3 of births are in towns not in 1919 list ... 
 looked at urban white ... 
  so 1920 added Gastonia 13k Goldsboro 11k HighPoint 14k  NewBern 12k  RockyMt 13k Salisb 14.4K Wilson 10.8
IMR of the extra: Gastonia 83 Goldsboro 139 HighPoint 60 NewBern 53 RockyMt 106 Salisb 41 Wilson 91  
1920 82 6194 : Ash, Charl, Durham, Greensboro, Raleigh               Gastonia Goldsboro HighPoint NewBern RockyMt Salisb Wilson
1919 93 3144 : Asheville, Charlotte, Durham,  Greensboro, Raleigh, Wilm, Winston-Salem



<p>[Life Tables](), where we see 1920 Registration Area states are a large proportion of population (maybe 80% or more?). I used 1919-21 and 1929-31 from the [1930 Life Tables volume](https://www.cdc.gov/nchs/data/lifetables/life30.pdf)
</p>


[CT Monthly bulletin of the Connecticut State Board of Health for the month of](https://archive.org/details/monthlybulletino619tutt/page/n3/mode/2up)

Monthly bulletin of the Connecticut State Board of Health for the month of
https://cscu-csl-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01CSCU_NETWORK_ALMA7170353930003451&context=L&vid=CSL_V1&lang=en_US&search_scope=CSL_ALMA&adaptor=Local%20Search%20Engine&tab=default_tab&query=sub,exact,Mortality%20--%20Connecticut%20--%20Statistics,AND&mode=advanced&pfilter=dr_s,exact,18400101,AND&pfilter=dr_e,exact,19100201,AND&offset=0
internet archive   -- looked briefly, searched for infant, did not get mortality data

[CT Deaths under age 1 p228](https://archive.org/details/monthlybulletino1412tutt/page/n227/mode/2up?q=infant)

<a name="DRAsect"></a>


<H4> **DRA Mortality Statistics** </H4> 

[Appendix](https://www.cdc.gov/nchs/data/misc/usvss.pdf) to US VSSS  offers history of DRA and BRA.     
p57  Growth of the Birth- and Death-Registration Areas      
  ... In 1880, the Bureau of the Census established a national ‘‘registration area’’ for deaths. This original area consisted of only two States—Massachusetts and New Jersey—the District of Columbia, and several large cities having efficient systems for the registration of deaths
     
p58 Table 1.01 lists dates for "Records on file for entire area (columns: Deaths Births"      
DC 1855 1871     MA 1841 1841    MI 1867 1867   NH 1850 1850    NJ 1848 1848    RI 1852 1852    VT 1857 1857      
but MI not into DRA until 1900 -- hmm

Condran & Crimmins 1979 Hi Methods    on quality of census mortality data 1850-1900.  Ji looks through 2022.0811 and tends to be discouraged from trying to use data from before 1900 ...     
  safe to say 1850 1860 1870 almost all from retrospective (not registration) Ji: BUT that seems to be supposition -- wonder e.g. about MI, NJ,  as well as MA
  in 1880 and 1890 registration data in place on enumer data for entire DRA   
  in 1900, reg data regarded as suff complete to be used in the census report only in CT MA NH and certain counties and cities in NY and NJ -- deaths not enumerated in the census.  remaining parts of DRA mort collected on census schedules,  returns compared to reg returns  The enum returns used to add unregistered deaths to the mort totals   fill in missing data on reg record ... a mixture of enumerated and registered deaths.    1880 and 1890 register of deaths solicited from physicians / added to returns from census enumerations.
  

**1870 census **     
[1870 Census: Volume 2. The Vital Statistics of the United States](https://www.census.gov/library/publications/1872/dec/1870b.html)

Intro seems to say the totals are worthless -- when did NJ start reg?  are there ant reg cities for 1870?
  p513 Table of Births
b-32 p535 Table XXI sex    ; b-34 p560 Ages Table XXIII 
T V sex/age/cause by state   Table VII causes NOT AGE   
 Table IX age/sex/color  -- entered these, for DC MA MI MH NJ RI VT,  in case they prove to be state registration data
   
**1880 Census **

1880 Census, [Vols 11 & 12, Report on the Mortality and Vital Statistics of the US]
(https://www.census.gov/library/publications/1885/dec/vol-11-12-mortality.html) As published, named Parts I (1885) and II (1885), but census web page refers to them as Vols 11 and 12. 


  Compendium refers to MA and NJ "registration records ... probably very near accurate" and lists cities with good registration -- we'll use ...

v11 pp 9-13 deaths by age/sex for census year -- look at NJ & MA and see if those are reg values YES THEY ARE    

v11-01          ; p L Appendix -- lists counties of states.      
v11-02 p2 Tab I Deaths by sex, states, 1860,70, 80; p6 Tab II deaths by state, sex, color; p9 Tab III death by state, age/sex; p15 Tab IV deaths by state, age/sex/color; Tab V death in each state (row) by region; Tab VI region/rate (odd to Jim) v11-03 p43 Tab VII (start); v11-04 p126- Tab VII;   v11-06 pp286-365; v11-08 p426- Tab VII Texas; v11-09 p499 Tab VIII cities
 
  v11001-Pt2 pp633-47 IMR stuff; Mass 649-51; NJ 653-655   
 
v12-01 Part TOC ...   xxiii urban/rural; v12-02 xxvii (27) Tab 30 German cities; Section VIII -- Causes of Death ... measles;
v12-03 lvii (57) Mumps ... Lightning    v12-04  cxxxvi Morbidity or Sick Rates  ... Section XII Conclusions and Recommendations    
v12-05 1-183 **Tab XIII**     
v12-06 p185 Tab XIV Deaths disease/age/month;      
v12-07 p347 Tab XV causes;  Tab XVI age/sex/cause  375 Tab XVII causes/ages;   387 Tab XVIII causes      
v12-08 p428
v12-09 p543 Tab XXXVI cancer, ...   Tab XLV cancer of uterus, Tab L uterus by age, p623-47 Tab LI deaths in infancy: u1yr, u1m, u3m; Tab LII Mass deaths enum/reg; Tab LIII NJ deaths enum/reg;       
v12-10 p657-  Tab LIV pop, births, women 15-49; Tab LV ditto with race; .... Tab LIX ages of native white, Tab LXIII pop age/sex for states; mass v12 p641 totals u1d m 4087, f 3201         
v12-11.pdf p771 Approximate Life Tables    
v12-12.pdf index

v12-05 1-183 **Tab XIII**     
MA u1d 7288  consistent with MA VS for 1880&81 7190 7389; but 1879 VS is just 5805 and IMR just 143; 




1880 LT census year Boston 203  Mass 146   Non-Boston ~ 131        ; Brooklyn 180 ;    pdf 158 Tab VII deaths age/sex (1881 MA annual corroborates Boston value).
 


old note:  1880  urban south atlantic SouAtl urban:  DC St=? Baltimore 530, Richmond 5870, Wilmington 7490

v11 GrandGroup2 cities are -- Balt, Brklyn, NYCxB, Cambden, JerseyC,Newar,Wash, Wilm
   not useful, b/c we will strip out Brklyn, NYCxB, NJurban, and we'll use the race detail on Balt, Wash, Wilm ...   
rural NY is 204K -- how can we easily divide it?  pdf549 lists counties in groups


<p>**1890 Census**
        
At [older link](https://www.census.gov/prod/www/decennial.html), and at [VSUS 1890-1938](https://www.cdc.gov/nchs/products/vsus/vsus_1890_1938.htm) Volume 4 in 4 parts has mortality data.   </p>
     
Our 1890 u1d/SR5 panel: MAurb OthNEUrb  NewEngRur Brooklyn NYCxB  Phila  

RuralNY:  Chi 140K   (Det-Clev-Cinnci-Pitts-Milw-)

MAssUrb 158k OthNewEngUrb? 59k  NewEngRural 142k  -- could take 30 minutes and create urban as BostonPlus and Other? Boston 40k  FallRiv 8  Law 4  Lynn 5  Camb 6.6  Low 7.1  worc 8.4  -- BostonEtc 78   othNE 140

for NewEng, CT MA NH RI VT  (all but ME). We'll use MAurb othNEurb NErur    Boston too small? (43k)
RURAL CT 39.2  Mass 43.5  NH 21   RI 13.5k   VT 27  total 142 -- one observation?

CREATED top10NewEngUrban othNEurban NErural

 rural NY?    build via RUR25K by subtracting off  cities 25K and above
 
  group 4 has u5 pop 93902 with 277 nonwhite who are 137 140    It includes Buff 33k  Rochest 14  Oswego 2045

 rural NY plus rural CT for an east-coast aggregate 


Volume 4: Report on Vital and Social Statistics in the United States<br>
[Part 1: Analysis and Rate Tables](https://www.cdc.gov/nchs/data/vsushistorical/vsush_1890_1.pdf) <br>

217  urban rural mortality

495-512 f539-  "Description of areas for which data are given" 
CT	DE	DC	MA	NH	NJ	NY	RI	VT
and their MANY "cities" are listed -- but we can use R and city codes to aggregate ... rest of a state is "rural"
And another set of Registration Cities are listed -- incl Chicago, Philly, Detroit,  .. Total of RegCities 271 (in and not-in Reg States)

pp513-658 has key data, but we need to enter what is in the Reg Area ...   USE R for cities -- pdf539 of Pt 1 ...

 would like to use small OH cities like Springfield, but how do we get "white" sr5 ? only total m5 and f5 in table 1 ...     

p584 New Jersey



Part 2: Cities of 100,000 population and upward (in Jim's digLibrary) ... Volume 4, Part 2, Vital Statistics, Cities of 100,000 pop ... 19610506v4p2.pdf
<br>1890a_v4p2-01.pdf has TOC, shows pop by age/sex/color etc 337-360; 391-408 death rates by ward. 
<br>19610506v4p2ch4.pdf  p2-06.pdf has "General Tables" pp. 335-444; p2-07.pdf for pp445-549 table 5 is continued ;  p2-08.pdf pp550-655 still Table 5 ;
<br>48 cities death rates, u1 231, u5 78; Chicago u1 213  u5 69;  Newark stands out for high u1dr 318 (also DC, via "colored" dr > 490 )
</p><p>Can muscle out city U2 vales -- Chicago U2 103.3 U5 102.3 -- pattern like Illinois, with the SR2 a full point above the SR5 ... 
</p><p>
<br>e.g. p514 Table 1 has u1 u5 for US, states, cities?
<br> volume? is called: 1890 Bulletins  no. 100 Social Statistics of the Cities
      
1890 CITIES   1890a_v4p2-08 t5 has by wards;  T6 has deaths m/f deaths by age -- by causesayse

</p>

Part 3: Statistics of Deaths  SEEMS TO BE CAUSES       <br>

[Part 4: Statistics of Deaths](https://www.cdc.gov/nchs/data/vsushistorical/vsush_1890_4.pdf)
Table 1 Deaths ..  in registration states, and cities in registration states, at certain ages and groups of ages, ..  sex, color, nativity, parental nativity, and birthplaces of mothers  ... May 31 1890. 2-21     
For each Reg State, deaths by age/sex/color; and for reg cities of that state ...

p501 6yr area: Metro District in NY, state of NJ, Baltimore, Boston, Phila, DC

Table 13 Deaths during the 6 years endiig May 31,1890, at certain ages and from certain causes, with distinction of sex, color, nativity, parental nativity, and birthplaces of mothers. 502-663

6 yrs e.g. p578f567 NJ state total, months/u1/u5/ ... / sex/color ;  also rural and urban split -- excruciating detail

Tables 16-24 are on New Jersey NJ only
 
### 1900 census

1900 Census: Volume III. Vital Statistics, [Part 1, Analysis and Ratio Tables](https://www.census.gov/library/publications/1902/dec/vol-03-vital-stats.html)
1900 Census: Volume IV. Vital Statistics, [Part 2, Statistics of Deaths](https://www.census.gov/library/publications/1902/dec/vol-04-vital-stats.html)
Or at CDC website: 1900 census reports [vol III](https://www.cdc.gov/nchs/data/vsushistorical/vsush_1890_3.pdf) and [Vol IV](https://www.cdc.gov/nchs/data/vsushistorical/vsush_1900_4.pdf)

**1900 Volume III **

Evaluation of 1900 Table 19?  Start with MA  -- 1900 censusMortSt IMR 160, MA vs (hsus 928) 157   -- close enough.
1920MS  shows 1920/1910/1900 u1d/u1pop  for DRA states, which we can compare to BRA IMR to some extent ... see US-kidsForR.xls 


For 1900 we have both the census-year deaths and the calendar year.     
We use table 19  pp  285-555 (pdf 598-868)  -- p xi rates reported when "the results are fairly comparable; for the nonregistration (enumeration) areas the insufficiency of the data are indicated by an asterisk (*). This character is also used for the same purpose in the registration area ...  It gives warning that the data are not regarded as sufficient for the computation of reliable rates."
      
Thence Ji enters all PA cities over 4K u5 pop; same done for IL IN OH WI ... maybe MN etc?      
NY rural is huge ...     try to id a large simple rural chunk?
 Group 1 434K kids, incl NYC with 397 !   Tiny rural ...
 Group 2 29K kids -- too small 
 Group 3 28k too small   
 Group 4 108,651  No f52p472   -- need pull out 7 cities, including Buff 41k & Rochester 15k   -- rural will be <30K
 Group 5 151K  incl 15+ cities to deduct... 
     
<br>
p xiv in many cases there were actually fewer deaths recorded in the later years of the decade 1890-1900 than were recorded in 1890, notwithstanding large increases in population.  ... decision to have the enumerators make inquiry and return deaths in all areas where any doubt of the sufficiency of registration existed, in order to use the information as a check upon the accuracy of registration, and to supplement and complete the registration returns if found defective in numbers or in detail.   
     The registration record was accepted as sufficiently complete and satisfactory in Mass, CT, RI, and NH; certain counties in the state of NY, nameley Broome, Columbia, ... cities: Albany, Cohoes, NY (greater), ... and certain counties and cities in the state of NJ ...
<br>In these areas the mortality schedule was withdrawn from the enumerators. In all others they were directed to report deaths, and their returns ... compared with the reg records. The result of the comparisons, ... indicated that registration was defective in many places where it was supposed to be perfect, a considerable percentage of the deaths reported by the enumerators not being found in the reg record. As the enumerators did not report more than 50 or 60 per cent of the deaths, the presumption is strong that the omissions in the registration record were even greater than indicated.
<br> tabulated result of the comparison of the two sets of returns [on next page]
<br>xv  xvi Chicago looks not bad: registration record (RR) forms have 93.5 of deaths recorded (the other 6.5% being enumerated deaths not in the RR</p>     
    
1900 Table 5 Deaths in the United States, each state and territory, and each registration city, during the census year ending May 31, 1900, at each age, by sex --    GOOD FOR CITIES, but not by race     p21
1900 Table 6 has states' deaths by age and sex, color,  e.g. pdf p65     

Vol III Pt 1 zip file: p7.pdf T8 deaths/occ; p8.pdf **Tab 19**    p9.pdf Tab 19 cont. ; p10.pdf Ratio Tables, p559 Table 20 Deaths & Rates, by cause (rows), total, total cities, total sttates ; p565 T21 death rates by cause, by state (columns); T22 deaths by cause, for counties (rows); T23 Deaths at age per 1000 deaths (columns 0, 1, ... 4, u5, 5to9 etc) eg p599; T24 T23 by cause; T25 deaths by cause per K deaths;    T26 deaths by cause per 1000 deaths (total, total cities, tot states) eg p656; p11.pdf T27 ratios/pop



**1910 census**

unnumbered table has births, u1deaths, IMR for reg states and some cities (50K+?)




Life Tables 1890 1901 1910
Pdf 446 has births (computed, registered) 1901 1910 for:    
DC neg&col; Indianna; Mass; MI; NJ; NY; Bost; CHic; NYC; Phil




**DRA 1900 onward Mortality Statistics  **

1900-1904 1900 Table 8   pdf  308-349    1902 Tab 2 death/age  532-549      Tab 8 deaths/age by cause CITIES     
1905 MS Tab 2 by age 216-233;   Tab 4 age, race, sex 252-269; Tab 8 city 100K+ 306     
1906 MS T4 states, ages;     
1906 onward has infant deaths for large cities    
1907 T2 pp282f276  by race is in southern places only ; T4 adds nativity;   
1908     
1909 toc pdf2  Table2 pdf468-   T2 doesn't have rural totals   T4 p550/f546 again no rural totals. Pretty thorough skim through tables and it seems we would need to sum up rurals or cities? to get rural. MA would be managable, but rural is defined via 1900 populations, and 1910 is via 1910 ...
1910 Table 3 pp204    pdf195-242   1910 has urb/rur breakdown

hsus? 1910 builds from USimrDRA1910.RDS 16June2021, which is with USimrBRA.RDS in Wrangling/Raw/US ...

**Mort Stats 1910** f153 T1 deaths by month of death ;  T2 deaths by color etc  eg f183 f195p204 T3 deaths by age   
Table 1 lists indiv cities ... pdf 432-      
Table 2 deaths by age -- again, no totals  eg pdf 482    
Table 3 NOT AGES rural by indiv counties, no sums pdf p532    
T4 States: age, color, nativity  eg pdf 556    
T5  not by age (urb/rur by state) eg pdf572 T6 not by state  T7 States: age, cause  eg pdf600
T8 ages, causes by cities 100K+   eg pdf 670
T11 occs, male   T12 occs, fem  T13 Reg Area, by age, Index pdf 791-805


1910-1920 Table IV pp428-   (pdf426-) 1910 and 1920 death rate per 100K enumerated population by age groups u1 1-4 u5 5-9 etc  MAYBE can back out IMR estimates from these?  pdf 426-27, 454-55, 484-85,     
PAGES  512-13, 540-41, 568-69 (pdf566) Pittsb RI SC, TN UT VT VA WA WI    
 (pdf is 2 less)

1915 T3 184-211   f179-


MS 1916  IA, IB, II causes,  III causes, rates, IV not ages; T1 T2 not ages;  T3 by age, state/color, state/city 152-74; T4 176-206 not urb/rur;   T5 not ages; T6 T7 T8 causes/ages, not rur/urb;     T9 u1 deaths by cause cities 100K+  t10 not ages;   T11 days/weeks  1916 T3 150-    f145-    

1918 T3 144-169  f138-163     
1919 T3 130-155 126-51     
1920 printed table 3, 4  f137-  140 Table 3 deaths age/color 171-  Tab 4 col/age/nati    272 Tab 7 DRA causes/ages
Table 8 deaths-cause by age (u1, 1, 2 ..., 5-9); Table 9 cities 479-540   pdf 476-536  ;       p224 is in Tab 5 deaths by cause Xage.   
ToC Deaths of Children under 1 year  p 67   mentions that births are available for 2/3 of the DRA states (and refers to BS for those data); p68 shows u1dr/u1pop for DRA states 1900-1920. Will use these for evaluation of 1900 census IMR findings


1925   IA,B II   not ages;  Tab 3 age & color pp36-42 (pdf 38-44)   282-314 for cities?
1926 T3 34-39   pdf37-42   f20-32 cities

1928 t3 38-46 f41-

1930 (for racial breakdown lacking in BRA for some states)  IA IB not by age; Table 1 by months (not by age); T2 not ages.     
Table 3  age; urb10 unincorp rur;
Table 4   age; white nativity/race

[Mort Stats 1929](https://www.cdc.gov/nchs/data/vsushistorical/mortstatsh_1929.pdf) Tab 3 108-116  (pdf 110-118).    
Tab4 States, u1 1to4 m/f    
Tab5 deaths by cause (not age)  pp134-
Tab6 causes: state, urb/rur  pp  176
Tab7A causes: by race
Tab8 causes: by age, for states
Tab9 causes: by age, for major cities
Tab10A causes: by month for cities
Tab11 by cause, by infant-age, in Houston?

<p>[Mort Stats 1931](https://www.cdc.gov/nchs/data/vsushistorical/mortstatsh_1931.pdf) Tab 3 Deaths by age and color 80-90 (pdf 86-95), 



<p>Early on: Bureau of Labor Statistics [Annual Reports](https://fraser.stlouisfed.org/title/bulletin-united-states-bureau-labor-3943?browse=1890s#477578) have city-level deaths by causes (these found via Cain & Rotella (2001)). But they lack age-specific deaths.  
</p><p>But there are death-by-age in Registration cities for 1900 (census year, in Census Reports, Volume IV, Vital Statistics, Part II, [Statistics of Deaths](https://www.cdc.gov/nchs/data/vsushistorical/vsush_1900_4.pdf)); I pdf-save Table 5 23-55   pp21-53



<a name="MASS"></a>

#### State of Mass


Richards (1909) "A Study of New England Mortality"
[Annual Reports 1898](https://books.google.ca/books?id=L2VBAQAAMAAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false)   Shows time-pattern of IMR (see SSMLit.html)

[Annual Reports](https://archives.lib.state.ma.us/handle/2452/39847/browse?rpp=20&sort_by=2&type=dateissued&offset=40&etal=-1&order=ASC)


##### U5 populations by sex in Mass 

US census volumes and data-sets for 1860-1970 at 10-year intervals; Mass State Census for 1865-1915 at 10-year intervals. 1925-1965? (2021Oct26): not 1925 1935  1945 1965.      
Some in 1955, Table 16, p 108

<p>Mass [state cenuses](https://archives.lib.state.ma.us/handle/2452/122027/browse?type=dateissued) of 1865-1915 have u5 pop by sex. Not so: 1925 

[1855 MASS census](https://archives.lib.state.ma.us/handle/2452/122030) Table 2 (64-97 -119) gives totals in age-groups, but not by sex.  p222 discusses sex. Jim cannot find any sex/age data here. 

[1865 MASS census](https://archives.lib.state.ma.us/handle/2452/122031) has age/sex

[1875 Mass census](https://archives.lib.state.ma.us/handle/2452/122032) 
2021.0530   found 1875 Mass census compilation error (age 1). Page 269 "The state by totals" reports age1 populations of 13825 male and 15589 female. Summing up the county-level values, we the male value is correct but the female value is 2000 too high. Ages 71- (pdf 139-)   p78 f146 is end of Barnstable, w/o totals ...  county recaps 263-268


[1885 Mass](https://archives.lib.state.ma.us/bitstream/handle/2452/122033/ocm10085339-1885-v.1-pt.1.pdf?sequence=1&isAllowed=y) pdf532 p434 

[1895 Mass v2](https://archives.lib.state.ma.us/bitstream/handle/2452/122034/ocm09219786-1895-v.2.pdf?sequence=2&isAllowed=y)   pdfs 7, 11, 442  ages recap 5ry p422

</p>

##### Mass IMR 

Haines (1998:231) Unfortunately, collection of vital statistics was left to individual states and municipalities, which resulted in tardy and uneven coverage. Massachusetts was the first to begin this activity at the state level in 1842 and achieved relatively good coverage by about 1855 (Abbott, 1897:714-715). 

Abbott 1897:714 The period of forty years (1856–95) has been selected for consideration for the reason that it presents a definite portion of time in which the returns of vital statistics of the cities and towns may be deemed to be fairly accurate. The returns of the first few years following 1842 are more or less incomplete and untrustworthy, but those of the forty years under consideration must be considered as approximately correct.

<br> Note: arguably, the rural data are perhaps not "deemed to be fairly accurate" ?

Haines (2006 HSUS essay) The Massachusetts data reach reasonable quality by about 1860 and are reproduced here in Tables Ab928 and Ab1048–1058.


<p>Mass Vital Statistics [Annual Reports](https://archives.lib.state.ma.us/handle/2452/39847)
[By date?](https://archives.lib.state.ma.us/handle/2452/39847/browse?type=dateissued)  I started to check 1890 versus 1885 and 1895, but realized Mass 1890 looks fine ...</p>

<p> [searched Mortality](https://archives.lib.state.ma.us/discover?filtertype_1=dateIssued&filter_relational_operator_1=contains&filter_1=1901&submit_apply_filter=&query=Mortality&scope=2452%2F39847)  And then use advanced filters to get date desired (issue date 1900 gives rpeort  of 1900 )

[1842-1899 Mortality etc](https://archives.lib.state.ma.us/discover?query=Mortality&scope=2452/39847&filtertype_0=title&filter_relational_operator_0=contains&filter_0=&filtertype=dateIssued&filter_relational_operator=equals&filter=%5B1842+TO+1899%5D)


In each, generally, see table VII (pdf 140+) for deaths; 

1859 births 20 xx   stillbirths xxvi  deaths 42? 44? 54?  xxxiv (pdf132)
1860 xxiv ; 1861   xxxiv   (births pdf 100 p xx)     
    1862 xxxiv pdf111 for u1 m/f deaths


1865  6? 10?    p29    clii -- 10  year sum 


1876 pdf56p42 gives 10yrs of births and u1 deaths for Mass  cxlvi ? deaths by age

1880 TOC pdf 13-     p7 births ?census year?           VII county/town age/sex xxxiv  pdf204 deaths; 
xxxii is pdf172      clxiv Tab XX deaths by county/age/sex totals of 16 years


1889  24 year totals p198 deaths p185 births

1898 1899  2, 34
1900     34 (pdf46)

1914 has births 1866 forward pdf194 p180 
1915 TOCpdf8 deaths 130-31



<H2> US Census Data for Childhood Sex Ratios </H2>


<p>US Census Office offers a partial listing of [**Pubs by decadal census**](https://www.census.gov/programs-surveys/decennial-census/decade.1950.html). But the 1890 page does not show Volume 4, which has vital statistics<br>
Maybe other volumes are at the older link to [Decennial Pubs](https://www.census.gov/prod/www/decennial.html). 
<br>Sometime useful are the IPUMS USA [incomplete links to census volumes](https://usa.ipums.org/usa/voliii/tPublished.shtml)
<br> * also see the PDF on 20thC US for linked sources, in our B/W page
</p>




Our full PUMS downloads are 
1850&70 00076.csv; 1860 00075.csv; 1880 ages 0-5 00069.csv; 1900 00070.csv 1930 00074; 1940 00073.csv; -- these have CITY -- which others also do?    
00057 includes 1860, but what else? ; 00069 has 1850-70, but 1860 loads with problems.

1880-1910 1920, 1930, 1940 u11 00068; 



<p>census dates or census timing:      1840-1900 June 1, 1910 Apr 15, 1920 Jan 1, 1930-2020 April 1    
1930 onward April 1 (90/365); 1920 Jan 1;  1910 April 15, 1840-1900 June 1* (1890 June 2)  
1850-1900 June 1 (but 1890 June 2); 1910 April 15; 1920 Jan 1; 1930 onward, Apr 1. 
[1900](https://www.census.gov/history/www/through_the_decades/overview/1900.html) Jan.1; [1910](https://www.census.gov/history/www/through_the_decades/overview/1900.html) Apr 15; 1920 Jan 1;   
MA 1865 May 1

</p>
 
<br>[1900-1970 intercensal pops](www.census.gov/data/tables/time-series/demo/popest/pre-1980-national.html)  


<p>Age by Race & Sex 1900 to 1970 in Table 53 of [US Summary](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_us1-07.pdf) from 1970 Census of Pop: Characteristics ... June 1973, Report Number Volume 1. Web page link is "chapter 7" but the text says "Chapter B".
<br>1940 census v4 has 1920,1930,1940 single year ages for white/nonwhite; also 1910 for total population.
</p><p>
These may contain age/sex/race, but odd text files ...
[1980-1989](www.census.gov/data/datasets/time-series/demo/popest/1980s-national.html)
</p>

<p> Except for Mormon's 1850 & 1880, the full-count PUMS are from Ancestry.com  </p>

ICPSR datasets with ages: 1800, 1810, 1820: 0-9;  0-4 (or better) are in 1830, 1840, 1850, 1860,  1930 (Part 27), 1940, 1950, 1960, 1970.  

NOT 1870 5-18,18-44, 21+
NOT 1880 -- can get u10 via 10-14, 15-20, 21+
1890 get u5 via 5-20, 21+  nat-white, for-white, colored
1900 get u5 via m21+ 5-20
NOT 1910 no age/sex
NOT 1920 
1930
Ages NOT in 1870, 1880 (5-17, 10-14, 15-20, 18-44, 21+),
02896-0005-Data.dta 


<p>[2020 all races by age](https://www2.census.gov/programs-surveys/popest/tables/2020/2020-demographic-analysis-estimates/table-1.xlsx) U.S. Census Bureau, Population Division, 2020 Demographic Analysis (December 2020 release).
<br>[2020 tables](https://www.census.gov/data/tables/2020/demo/popest/2020-demographic-analysis-tables.html)
<br>[2010 by age](https://www.census.gov/data/tables/2012/demo/popest/revised-2010-demographic-analysis-estimates.html)
<br>Jim pasted in 2020 and 2010 demog analysis estimates of pop by age/sex/col
<br>[1900 to 1970 Nationals](https://www.census.gov/data/tables/time-series/demo/popest/pre-1980-national.html)
</p>

**2010 and 2000** [2000-2010](https://www.census.gov/data/datasets/time-series/demo/popest/intercensal-2000-2010-national.html)
<br>
Maybe [1990-2019](https://wonder.cdc.gov/controller/datarequest/D163)
<br>
maybe [2000-2010 Intercensal](https://www.census.gov/data/tables/time-series/demo/popest/intercensal-2000-2010-national.html)

maybe [State Intercensal Datasets: 2000-2010](https://www.census.gov/data/datasets/time-series/demo/popest/intercensal-2000-2010-state.html)

NOT 2000 state-volumes "Summary Population and Housing Characteristics" e.g. [Rhode Isle](https://www.census.gov/prod/cen2000/phc-1-41.pdf)  not single years of age. PHC-1-41 is not what we're after (but does have U5)

Not useful: [1990-2000](www.census.gov/data/datasets/time-series/demo/popest/intercensal-1990-2000-national.html)

[Census of Population and Housing, Decennial Pubs?](https://www.census.gov/prod/www/decennial.html)
<p>
[*Publications grouped the census Decennial*](https://www.census.gov/programs-surveys/decennial-census/decade.html)</p>
**2000**  For NYC I find [Total Population by Single Years of Age and Sex - 2000](https://www1.nyc.gov/assets/planning/download/office/data-maps/nyc-population/census2000/sf1p6a6i.xls)<br>
2000 PHC-1 u5 ages; PHC-2 no age-data; PHC-3 no age data; DP-1 u5; Briefs NO; Profile NO;

**1990** [1990 Census of Population, General Population Characteristics, United States](https://www2.census.gov/library/publications/decennial/1990/cp-1/cp-1-1.pdf)
States 262a-g Northeast metro/not etc tables 64, 65 <br>
cities in tabs 61-63?
<br>[PA 1990](https://www2.census.gov/library/publications/decennial/1990/cp-1/cp-1-40-1.pdf). Table 17 for urban/rural. Phil is part 2 (I printed the page)br
[1990 states](https://www2.census.gov/library/publications/decennial/1990/cp-1/)  10DC 11FL 12GA  15IL 18Kansas  22Md   26Missi  36ND  38 OK   44 TN   47Vt   50 WVa

[**1980 census pubs**](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1980.html)      
spotty access need to dig around at  https://www2.census.gov/prod2/decennial/documents/1980/



[USA ages](https://www2.census.gov/prod2/decennial/documents/1980/1980censusofpopu8011u_bw.pdf) Page 1-23 Table 41 Single Years of Age by Race, Spanish Origin, and Sex: 1980, in 1980 Census of Population, Volume 1, Ch. B, General Population Characteristics, Part 1, United States Summary<br>
pdf 35-55

[Illinois](https://babel.hathitrust.org/cgi/pt?id=uva.x004451315&view=1up&seq=173&q1=single%20year) at HathiTrust, images 173-
<br>
[NY volume](https://www2.census.gov/prod2/decennial/documents/1980/1980censusofpopu80134unse_bw.pdf)
pdf84 Table 18 p72   pdf111 NYC&NENJ urbanized area <br>
General Population Characteristics, PC80-1-B34, Vol 1, Characteristics of the Pop, Ch B, General Pop Char
<p>
IPUMS has good access to [1980 age volumes](https://usa.ipums.org/usa/voliii/pubdocs/1980/pubvols1980.shtml) <br>
<br>Michigan 1980 [Table 18 pdf 162ish](https://catalog.hathitrust.org/Record/009780899)
<br>But it does not have Illinois Ch B
Chapter 2 (with ages) for PA seems to be missing (looked on Hathi too). Poked around the census directory, looking at pdfs 80134 is NY <br> vol 1
</p> 
<p>Illinois at [Hathi](https://catalog.hathitrust.org/Record/102583049)
<br>[PA ages Tables 18-20](https://www.dropbox.com/s/jzhux09h39clhfz/1980PATabs18-20.pdf?dl=0) extracted from  [Penn Volume](https://www.dropbox.com/s/3nectos2e359yql/PA_1980_Vol1B.pdf?dl=0) downloaded from GoogleBooks.Ca
</p>
**1970** census  [Characteristics of the Population](https://www.census.gov/library/publications/1973/dec/population-volume-1.html) 
<br> Maybe chapter numbered 7 on webpage is US total age data 
<br> Generally Ch 4 on that webpage (URLs differ)<br>
Table 19 Single Year of Age by Race and Sex p87 negro and negro&other   Table 24 p102 SSMA's Table 17 p85 race by sex -- no ages.
<br>1970 Pop Vol 1 Unites States Summary
<br> Section 1, [Ch 7](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_us1-07.pdf) Table 50 single years by race & sex; pdf12 1-265     
Table 53 5yr age/race/sex US 1900-1970    
Table 56 5yr age/race/sex Regions 1970 
<br> Ch 1, does not have ages; Ch 5 starts with Tab 170 Industry of employed males
<br> Section 2, [Chapter 1](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_us2-01.pdf), pdf15 for Table 19 which has 1970 and 1960 5yr age groups by sex for total, native white, foreign-born white, etc But Data is "based on sample"


<p>The standard [MASS link](https://usa.ipums.org/usa/resources/voliii/pubdocs/1960/Population/Vol1/37722946v1p23ch3.pdf) is missing the start of Table 16. So we use the detailed [Table 271](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37722946v1p23ch5.pdf).
</p>

[PA ages](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/00496492v1p40s1ch3.pdf) pdf 51 t24 Phila

[NY ages](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_ny1-02.pdf)

[MA ages](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_ma-01.pdf)

**1960**  

[1960 census pubs](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1960.html)

<p>Reconciling Vt data, I find statement (Vol 1, Part 47 Vermont, p xii) that chapter B has complete-count while chapters C and D have 25% sample stats. Eg the U5 totals differ by 3. For [Vermont](https://www.google.ca/books/edition/Census_of_Population_1960/vSabfPk3ERMC?hl=en&gbpv=1), I use google books copy. <br>
MASS is missing p31 or so; I use Google Books version.
</p>

[This directory seems to have the 1960 age data](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/). But Mass is missing the start of Table 16 (p23-31). This 
[page at census.gov](https://www.census.gov/library/publications/1961/dec/population-vol-01.html) has some valid links. But GA is missing -- maybe ok via write in URL at https://www2.census.gov/library/publications/decennial/1960/population-volume-1/
DC 10  FL 11 GA12 . Some are like GA: [12-d is Georgia](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-12-d.pdf). But others are like [NC, which is p35ch3](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/06586188v1p35ch3.pdf)
And then the 1960 census page has a valid link to [SC](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37749999v1p42ch3.pdf)

[only some via IPUMS](https://usa.ipums.org/usa/voliii/pubdocs/1960/pubvols1960.shtml) CT For any state, use its Population Vol 1, section 3, general pop characteristics.

census [Vol 1](https://www.census.gov/library/publications/1961/dec/population-vol-01.html)
col-01-01-k 
[Table 156 Single years of age, by nativity, color, and sex, for the US, urb &  rural](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-01-h.pdf)

Table 232 single years of age, by color and sex, for regions, 1960 p612   Vol 1 states or cities lack single year, lack age-group     

1960 Vital Statistics [Vol 1 Natality,](https://www.cdc.gov/nchs/data/vsus/nat60_1.pdf) SRB by state 1-27   Also, p 1-9 for national SRB white 1.055  nonwhite 1.018     2-4 Live births by specified race and sex: US and States pdf54


Vol 1, Pt 2, for each State.  Single years : Tables 94, 95, 101, 102.  Cities: age groups 20, 96
[Mass](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37722946v1p23ch5.pdf)
Mass Table 16 (pdf p9) white female U1 52,822 but Table 94 52,940

[NY](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37749573v1p34ch3.pdf) 
Table 16 Age by color and sex ... pdf p10
Table 20 pdf44 for NYC  

[PA](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/17216604v1p40ch07.pdf)
table 94 single year of age, state; color (white/nonwhite)

ILL [Tables 13-19](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-15-e.pdf) in the directory as vol-01-15-e   15-c is Number of Inhabs    15-e includes age/sex color single year

1960 PE11XLS  single year, white/black/other


1960 The table presented here is a preprint of table 65 from Final Report PC(l)-1C, which contains summary information on these and other general social and economic characteristics of the population.

This report presents statistics on age by sex and color for the urban, rural-nonfarm, and rural-farm population of the United States.


[**1950** US Census](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1950.html)

(https://www.census.gov/programs-surveys/decennial-census/decade.1950.html) <br>

Vol 1 is pop totals;     
<br> Vol 2 Characteristics of the Pop. Part 1 US Summary [TOC](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/21983999v2p1.pdf) .   Table 38 US age/sex for rural/urban 1940 & 1950. Table 39 1880-1950 US age/sex/color. Regions/division 1950 only (via "General Contents p viii of TOC.)    
Table 61     5yr age /race/ urb-rur / REGIONS 1950
Table 62  p112 Age by sex, for divisions: 1950   -- not by race


Age-data from Table 15 in [**Volume 2 for each state**](https://www.census.gov/library/publications/1953/dec/population-vol-02.html). Table 15 groups ages 1&2, we split as 48.5% age 1 (based on sample-evidence in Table 51). Table 15s are in dropbox. 
<br>Table 33 is SSMAs, urban, cities, etc.  <br>
[Penn T33](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/23760756v2p38ch3.pdf) is pdf 2-25
Population Table 94 via sample; Table 95  single year  white/nonwhite  1940; Table 38  u1 1&2 3&4   white/nonwhite, 1940 & 1950; 
Table 39  5-yr ages    white/nonwhite    1880 to 1950


BW: 1950census does not have negro <br>
1950 For U2, we extrapolate on the full count's 1&2 age group by taking 48.5% of them as the age 1 (based on the 20%-sample counts). Maybe 1960 has full-count data for 1950?    Table 33 NY pdf 23-41
using the 20% sample (Table 51)   <br>
Table 51 says 1950 data from 20% sample; says Tab 14,15, 33 are complete count. 


US Census of Pop (via my zip 21983999v2p1 probably Vol 2 Part 1) <br>
Vol I Number of Inhabitants (comprising Series P-A bulletins) <br>
Vol II Characteristics of the Population (comprising Series P-A, P-B, and P-C bulletins) <br>
Vol III Special Reports: ... Nonwhite Pop by Race, <br>
<br>
Population Volume II   ... compruses 54 parts ... 1. US Summary 2. Alabama  ... 21 Mass
Looks like I have Pt 1 -- US Summary. <br>  Pt 32 is NY   [ch3](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/22980932v2p32ch3.pdf) for U1 and 2-yr or 5-yr age and sex <br>
[ch 4](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/22980932v2p32ch4.pdf) Tab 51 for single-year <br>
Part 38 is [PA](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/23760756v2p38.pdf) tables 15, 33
<p>Region single year data Table 146 -- based on 20% sample. NE NC Sou West -- Full count Table 61 -- 5yr groupings. We'll need to tally up states.
</p>
1950 [Vital Statistics](https://www.cdc.gov/nchs/data/vsus/VSUS_1950_1.pdf) 
p81 Registered live births and live births adjusted for underregistration, by race and sex: US, 1935-50
p81 Male births per 1,000 female births, by race: US, 1935-1950 
1950 Vital Stats [Vol 2](https://www.cdc.gov/nchs/data/vsus/VSUS_1950_2.pdf) p187 live births by race & sex, US and states. pdf193 Table 18 page 187  p324

<p>US total for CEA paper, Jim extrapolated from the 1960 black/nonwhite ratios by sex: U2 for ages 0 and 1; Age2to4 for ages 2, 3, 4 (U2 and 2-5) to avoid noise.</p>
Census of Population: 1950, Vol. 2, Tables 94 & 97; Table 94 has sex by single year of age for “White” and for all “Nonwhite”. For our black SR02 in 1950 (100.9), we reduced the nonwhite value by 0.1, based on the difference between the negro and nonwhite sex-ratios for under-age-5 (via Table 97). A 1950 black SR02 of 101.0 results from applying the same correction to the nonwhite SR02 from the spredsheet for 1950 in the National Intercensal Tables: 1900-1990 (released in 2004). </p>
<p> PE-11 has Nonwhite SR2 is 101.1, census has 101.0 </p>


<a name="1940US"></a>

**1940**

<br>1940 Population Volume 1 has various population totals (nation and states).
<br>
<br>[1940 Census of Population: Vol II Characteristics of the Pop ...](https://www.census.gov/library/publications/1943/dec/population-vol-2.html) . Has 
Table 7 1940 & 1930 age by race & sex, urban & rural.  T21-48 "Divisions and States",  T26 Age, by race and sex, ... 1940. 
1940 Census of Population: Volume 2. Characteristics of the Population. Sex, Age, Race, Nativity, Citizenship, Country of Birth of Foreign-born White, School Attendance, Years of School Completed, Employment Status, Class of Worker, Major Occupation Group, and Industry Group
No 1930 age data by region found in Vol II. 
<br> Pop Vol III Labor Force.  
<br>Pop **Vol IV Characteristics by Age** / Marital Status, Relationship, Education, and Citizenship;   
Part 1 US Summary; Part 2 AL to LA; Part 3     ; Part 4 OH to WY ;    
Part 1: US Summ Tab 1 age/sex, 1930&1940, for whites/nonwhite, urban/rural; 1920 total pop by age. Table 2 1930&1940 age-sex all/white/nonwhite and all/urb/rur for white & nonwhite; "Regions" Tables 26-45 and "Divisions and States" Tables 46-52.     
T26 ages by single years, color sex for regions 1940. Can't find a 1930 regions/division u5 source here.  

<p>Table 1 in [Vol 4](https://www.census.gov/library/publications/1943/dec/population-vol-4.html) has single-year ages (1930 & 1940, I think). Page 4 has light discussion of under-enumeration of infants. States are in groups, within which there are city-data. E.g. For Philadelphia, see pdf35, p206 [Table 2](https://www2.census.gov/library/publications/decennial/1940/population-volume-4/33973538v4p4ch3.pdf).
<br>[1940 NY](https://www2.census.gov/library/publications/decennial/1940/population-volume-4/33973538v4p3ch6.pdf). 33973538v4p2ch3.pdf Arkansas
</p>
<p> USA 1940  98.9 if we use the PE-11 XLS (2004) SR2 adjusted for Black vs Nonwhite for 99.0-0.1     
<br>2004 PE-11 release for 1940 nonwhite has SR1 98.4  SR1-2 99.5 suggesting heaping    
<br>1940 census  has u1 and u5 negro  and more detailed for nonwhite. From that
<br>   negro vs nonwhite  U1 -0.13     U5 99.1 vs 99.2
<br> I ADJUST 1940 NONWHITE U2 DOWN BY .1 FROM 99.0 to 98.9     BUT see PAPER for latest version
<br> Looking for 1940 U5 by state or division v2 pt 1 Table 26 p59
</p>

<p>
[**1930**](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1930.html)
<br> see 1940 for correction of 1930's grouping of Mexican with colored
<br>See Vol 2 Ch 10 pdf 111 for Illinois
[1930 Vol 2](https://www2.census.gov/library/publications/decennial/1930/population-volume-2/16440598v2ch11.pdf) for ages, pp674-690  pdf 112-128
<br>
v2ch11 T8 p577 5yr by sex  color, nat ;  T16 p587 urb/rur ; T24 p669 divisions age/sex race     
<br> Tab 33 p724  city 500K+ ages
<br>

urban/rural 1930 USA vol 1ch02  p7 in recent censuses / 2,500+   1930 definition modified to include unicorp places with 10K+ and pop density 1K+ per sq mile ... adds 4 town in CT   ...  in NH MA RI  previous censuses had some rural townships in urban ... 

<br>
SR2 census negro 98.4  nonwhite 98.6    PE-11 nonwhite 98.6
<br> Vol III has state-level data, including urban/rural u5 age/sex; also 1920 u5 age/sex (and % splits for rural vs urban, but too imprecise)
<br> 
v3p1 TOC pdf   
pdf44p594 Table 3 age/sex rural/urban
pdf50 p600 Table 11    
Table 11 County-level  u1 u5, all/native white/foreign-born white/negro     
Table 12 Cities  pdf58-63    
Table 10 occs

Calif Tab 12 47 (pdf 17-)


<br>Looking for regional totals: Table 24 has 5yr totals

</p>

1925 NY state census -- no age data presented.


<p>

**1920**   [1920](https://www.census.gov/library/publications/1922/dec/vol-02-population.html) <br>
Our age data, including single-year for Divisions, found in [Vol 2, ch 3](https://www2.census.gov/library/publications/decennial/1920/volume-2/41084484v2ch03.pdf) pdf20 is p162 Table 9 "Dist by Single Years of Age" for US as a whole,    
pdf29 **Table 13** single age  Regions and States (states is 188-285   pdf 46-143), but white pops presented as np, nwfp, nwmp, fb
<br>[ch 4](https://www2.census.gov/library/publications/decennial/1920/volume-2/41084484v2ch04.pdf) Table 15 has cities with single-year ages

v3 Tables 1 to 13; Table 8 is Ages for cities 
e.g. [Georgia](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch04.pdf)
[Kansas etc.](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch04.pdf)
[NewYork](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch06.pdf)  NYC Ch4 Table 15 pdf10
[Ohio, Penn](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch07.pdf) Table 3, e.g. pdf p3 p769  (Ohio) has u1 u5,  
<br> W/B use census, based on small difference and 1910-based doubts of PE11 for older data
DROP IT BY .2 to 98.5
census SR2 negro 98.4  nonwhite 98.6  
PE-11 nonwhite 98.7

[**1910 census volumes**](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1910.html)  e.g. [Pop vol 1](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p1.pdf)   


use [census](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p7.pdf)
census SR2 negro 99.2  nonwhite 99.6     PE-11 SR2 nonwhite says 100.8 with very rounded numbers, so I reject, and stick with census    TABLE 43 has Divisional ages   

1910 Pop [Vol 1](https://www.census.gov/library/publications/1913/dec/vol-1-population.html). [Ch 4](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p6.pdf) has single year ages, including  [major cities](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p7.pdf)
Table 29 is national totals, including the 1910 "negro" values which I found elsewhere. <br>
Table 33 has USA, u5 m/f 1880 1890 1900 1910   Table 41 age periods, divs & states, but not by sex <br>
 Table 43 single year p391 NY
 Table 48 no sex breakdown, u5 by region. Table 49 1910 t50 (100-500k),t51 (500k+),t52,t53,t54 1910
1910 Vol 2 NOT AGES  has state detail, section for each state, Table 1 has state and county
<br>Looked for, and did not find, u5 by sex for previous years.

V1 Distribution by broad age periods of the urban and rural · population, classified by sex, bydivisions:.1910 ............ 425

MS VA reg cities  Alexandria 0090. Danville 1631, Lynchburg 3790, Norfolk 4810 , Petersburg 5310, Richmond 5870  -- Citycodes

**1900** [12th census pubs](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1900.html)

Much like 1890, single-year for states (Table 2); age-groups for cities    
vol 1 tables 1-4 NO age data; 
[vol 2](https://www2.census.gov/library/publications/decennial/1900/volume-2/volume-2-p5.pdf) has ages. Vol 2. Pop, Part II, Statistics of the Pop, has mainland US totals. In tables,   Table 3 is states 5yr by sex



<br>
1900 bulletins 1-60, 61-106
<br>Bulletin 13, "A Discusssion of Age Statistics"
[discussion of age statistics](http://www2.census.gov/prod2/decennial/documents/03322287no13.zip) p18 indicates 1890 ages were "age at nearest birthday" and therefore confusion in 0 1 2 age groups  <br>
To think about: if 11mo olds are rounded up, how does that distort the SR1? It would seem to leave more of the younger, who are more male ... That is a 39 page essay, with attention to sex-ratio evidence rural/city-sizes ...
<br>

**1890** census

AGES in [Eleventh Census - Volume 1. (Part I & Part II) Report on Population of the United States](https://www.census.gov/library/publications/1895/dec/volume-1.html)
<p> Report on the Population of the United States at the Eleventh Census: 1890, Part II (Washington, D.C.: GPO, 1897). Table 1 has US; Table 2 has states: ages by U1 months and single years (we have it in 2 parts). Table 3 states' sex by 5-year age groups;  Table 4 ages by periods of years of native white; 
In Vol 1 Part 2,  Table 8 Ages by periods of years ... for cities having 25,000 inhab or more -- sr5 not available for smaller places in 1890 </p>

See above in [DRA section](#DRAsect) for mortality data from 1890 census

Ages were to be asked as "age at nearest birthday" so the data are not consistent with 1880 or 1900 (and there are the manuscripts were destroyed by fire). Looking across 1880 to 1910 by state, some states seem plausible, a few seem odd, in terms of SR5 values over time.
Odd include
14PA -2.7 -3.2 -1.5 -1.9    1.7 1890 over 1900
21IL -2.8 -3.1 -1.6 -2.5    1.5
23MI -3.2 -3.6 -2.4 -2.6    1.2
24OH -3.2 -3.3 -2.3 -3.0    1.0
Not odd: 

Eleventh Census - Volume 1. (Part I & Part II) Report on Population of the United States : 1890 rural/urban populations by state pdf36/51 p lvxiii of "Progress of the Nation" 


### 1880

[census bureau site -- publications](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1880.html)


Vol I, Statistics of the Population ... has single-year ages in Table XXI [Ala-Nevada](https://www2.census.gov/library/publications/decennial/1880/vol-01-population/1880_v1-15.pdf) and [NewHamp-Wyoming](https://www2.census.gov/library/publications/decennial/1880/vol-01-population/1880_v1-16.pdf)    
Table XX US single year for all, white (native/forgn-born), colored; Table 21 by states;

<br>
VA is pdf33 p636; With enough time, can compile U5 ages for cities,
1880 city ages in [vol 12](https://www.census.gov/library/publications/1885/dec/vol-11-12-mortality.html) <br>
Ages u1 & 1to5 [Vol 12, Table XIII](https://www2.census.gov/library/publications/decennial/1880/vol-11-12-mortality/1880v12-05.pdf) THis has county and city detail (white/col/tot)




### 1870

Age counts in 1870 Census: [Volume 2. The Vital Statistics of the United States](https://www.census.gov/library/publications/1872/dec/1870b.html)  
Table XXII is US age/sex with nativity or race, 1850-70
Table XXIII is US & states, Aggregate population, Age/sex, 1850-1870     
Table XXIV Native Pop, Table XXV Foreign-born    
Table XXVI white; t xxvi native white; T xxvii foreign-born white     
Table XXIX US & states, colored pop age/sex, 1850-70      
Table XXX US & states, chinese & indian age/sex, 1850-70. Tab XXXI ages 80+     
 
 Ages with sex for each period of life ...    p563  /      Ninth census, volume 2, The Vital Statistics of the United States    1872 Wash GPO.
link was down 220308





[1870 census page](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1870.html) lists volume 2 but the link is broken (March 8, 2022).


[**1870**](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1870.html) US aggregates in Vol 2 [Table XXII](https://www.dropbox.com/s/dndp8e0uv4nf1vf/1870b-33Vol2TabXXII.pdf?dl=0) <br> [Table XXIII](https://www.census.gov/library/publications/1872/dec/1870b.html) for national and state-level white ages in 1870, 1860, 1850.^[Vol 1 tables have large age group -- "ages" is school age, 18+ ;  XXV some large age groups, some cities, but no way to get u5. Ninth census, volume 1, the statistics of the population of the United States embracing the tables of race, nationality, sex, selected ages, and occupations ...  Washington: GPO 1872.]   
For 1870, published city-level data for SRs not found. V1 Tab XXV has school age counts.





1860 has national and state-level ages u1 1-5 -- but nothing to add to 1870s presentation; and 1860 total includes "asiatics" of California (not in 1860 whites as reported in 1870)     
1850 census volume's USA white u5 pops same as reported in 1870




**1840**   slave and frcol are u10.   Census site lists    
1840 Census: Sixth Census or Enumeration of the Inhabitants of the US      
1841 {pub date, I deem}     
Aggregate amount of each description of persons within the United States and their territories, according to the Census of 1840.   {not in census digital collection}

deletion from data appendix of dempap 
Mass 1890 p 104 Table 3, Ages by periods of life  of Volume 1 Part II (see TOC in census data of 0SSSm in dig lib) [1880 Census: Volume 1. Statistics of the Population of the United States](https://www.census.gov/library/publications/1883/dec/vol-01-population.html)  MASS p592 in Table XXI  Table XXI. Population, by Specified Age, Sex, Race, and General Nativity of the Whites, by States and Territories: 1880 
   1870 Census: [Volume 2. The Vital Statistics of the United States](https://www.census.gov/library/publications/1872/dec/1870b.html)  LINK IS BROKEN MAR08 2022 Table XXIII. Ages with sex for each period of life ...    p563  /      Ninth census, volume 2, The Vital Statistics of the United States    1872 Wash GPO      -->



### US Census for the Black SR1 ###

population volumes from 1850 and 1860 give U1, 1-u5, 5-u10 etc, for Whites, Free Colored Slaves.  Negro Population 1790-1915 Ch 4 provides SR1 for blacks 1850, 1860, 1870, 1900, 1910 and explains that 1880 and 1890 includes "indians, chinese, japanese" with blacks. So we need to extrapolate to fill in -- calculate non-white totals 

1940 can't find negro age 2 -- just nonwhite for single yr

Have nonwhite 1900-2010 ? really

searchable index
https://www2.census.gov/programs-surveys/popest/FTP2_Key.xlsx


https://www2.census.gov/programs-surveys/popest/tables/1900-1980/national/asrh/pe-11-1910.xls

https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.html

#### State Censuses

US census site lists [state censuses](https://www.census.gov/history/www/genealogy/other_resources/state_censuses.html)





**1875** Mass state census  pdf p141 County of Barnstable       pdf541 occs

and see above for Mass

Michigan - 1837, 1845, 1854, 1864, 1874, 1884, 1888, 1894 ages, 1904 ages.    
Mich [annual reports on births, deaths etc](https://catalog.hathitrust.org/Record/008616744?type%5B%5D=subject&lookfor%5B%5D=%22%20Michigan%20Statistics%2C%20Vital.%22&ft=)     
1902 VS annual report indicates that birth enumeration is flawed:    
  
     The usual comparison of births and deaths, their difference constituting what is known as the natural increase of population, cannot be made, since the improved accuracy of the returns of deaths removes them from the plane of comparison with the very imperfect returns of births.


1907 sb not split out for rate of 22.6 per Kpop (p63)
1908 births moved to front, in recognition of improved accuracy

1909 VS annual report p4 indicates that 1906 forward is good for MI births ... 1905 to 1906 births per K pop jumps from 18.4 to 22.7   And p20 that death counts good from 1898 on

New Jersey - 1855, 1865, 1875 5-16; 1885 5&u; 1895 5&u; 1905, 1915.


##### New York State censuses

[NY state library](https://www.nysl.nysed.gov/scandocs/nyscensus.htm)

[1855](https://nysl.ptfs.com/data/Library1/06042012/88819.PDF)    YES-- AGEs     
[1865](https://nysl.ptfs.com/data/Library1/77860.PDF) Yes -- ages      
[1875](https://nysl.ptfs.com/data/Library1/93418.PDF) Yes -- ages      

1892 no ages   p29 Exh C election districts, pop (citiz, alien)
[1905](https://nysl.ptfs.com/data/Library1/93419.PDF)   -- no ages data

1915

1925 no ages
Population figures for the cities, incorporated villages, towns, and counties of New York... Census of June 1, 1925.  No AGES

#### Wisconsin

Wisconsin - 1836, 1838, 1842, 1846, 1847, 1855, 1865, 1875, 1885 -- no ages, 1895 no ages ,   1905 -- no ages.

<a name="AlterSect"></a>

<p>***UNDERCOUNTING of Children *** Underenumeration of infants and children? Hacker (2003) relies on PUMS samples for 1850-1870, which we doubt for SR data. Earlier work on fertility refers to infants, but the empirical work and estimates work with 5-yr groups (u5, 5-9, etc). See LIT for Thompson & Whelpton (1933), Yasuba, Coale & Zelnick, Land et al., Hacker.
</p>
<br>
1850 compendium DeBow p 104 mentions age heaping at 10 15 20 ....


### ICPSR data

ICPSR 2896 :  Parts 1-43 are an update to HISTORICAL, DEMOGRAPHIC, ECONOMIC, AND SOCIAL DATA: THE UNITED STATES, 1790-1970 (ICPSR 0003).  Parts 1-41 contain data from the 1790-1970 censuses   .... Most of the published county data on population and housing were included up to the early 20th century. 

Part 7 : 1850; Part 9 1860; part 46 1860 slh

[back to top](#TOC)