---
title: "P-H Fatal Years"
author: "jim"
date: "14/05/2021"
output: html_document
---
<p>Preston & Haines (1991) [*Fatal Years*](https://www.dropbox.com/s/fk0yglszu300s1u/Preston%26Haines1991FatalYears.pdf?dl=0) 
<br>Points for CEA paper: p74 their 0q5 is 180/k (falling from 204, I'd say) and that reflects IMR (123, falling from 137) and 1q4 (66, falling from 78) --
So they have about 10% fall in infant & child mortality. And with a 1-level change in West, that's +2.5 yrs to female e0 
If we eliminate the q0 fall, the 0q5 fall is about 1/2 as much; e0 effect, also about 1/2 as much ... 

-- average their 3 models for 

     "The grand mean is approximately a level of 13.5 for 1895. At this level of mortality in the West model life table system, q(5) is .180 and theimplied expectation of life at birth is 49.8 years.
     
West model 
level 13 IMR 130 1q4 72   0q5 192  with 1q4 60: 182.3 
level 14 IMR 116 1q4 60   0q5 169  with 1q4 72: 179.3 

... without IMR decline? avg Lev13 192 and 179  (not 169)   ... suggest 185  not 180 ...  


hard to pin down the change of mortality. Decadal e0 change +2.8 [say level 12.46 to 13.68 -- 1.22 in 11 yrs, so 1.10 in 10; e0 goes up 2.48 years level 13 to 14, 12to13 2.59 yrs avg 2.54 across 1 level, 1.1 levels implies 2.8 yrs ...  IMR change per level averages 14.3 so 1.1 levels implies IMR falls 15.7 ... over 15, almost 16.
<br>Prob of death 0-5 = q0 + 1q4 x (1-q0)   Level 13.5 is 180.7  Level 13.68 should be 176.6 ...  0.32 * 192.3  + 0.68 * 169.2  = 


<br> q(5) of 18% for 1895, an improvement over prior decade, and since mid-1880s, they say. Emphasize 18% prob of death by exact age 5 in West model, maybe level 12.5?   p72 Using the marital-duration estimates, the average Model West level of mortality for marital durations 5-9 and 10-14 years was 13.68 (1895.9 level 13.68   1884.9 level 12.46)

p74 q(5) of .180 for 1895  -- that is 18% probabilty of death before the age of 5  -- that comes from the level 13.5 of mortality in the West model life table system;  
<br>p72 Model West level improvement from 12.46 to 13.68 (call it 12.5 to 13.72); p74 level 13.5
<br>Consider 1-level change in West, from 12 to 13, or 13 to 14 : the IMRs are 144, 130, 116; seems like the IMR change is about 22 (like 144 to 122)
</p>
<p>xviii Our census sample suggests that child mortality had been declining in the two decades before 1900 for whites and for the total population.</p>
<br>1900 IMR and childMR rates (or 1895, retrospective source)
<br>p49 Little is known about trends, levels, and differentials in American mortality in the nineteenth century. It is not altogether clear when or even whether mortality declined in the United States during the period 
<br> description of Death Registration Area (DRA) and discussion of mortality data <br>p50 Mass 1842 starts vital registration  Gutman 1956   <br>"By 1860, the Mass death registration were quite good"
[Useful discussion of DRA relative to USA]
<br>*p51*  ... Higgs (1973) argues that mortality began its decline in rural America in the 1870s and that the decline took place largely as a result of improvements in diet, nutrition, housing, and general levels of living and without much assistance from public health. Meeker (1972, 1974) contends that mortality improved little if at all before about 1880 ... Both analysts use a variant of intercensal survival analysis ...which produces virtually no information on mortality in early childhood.
<br>*p52* Table 2.2 compiles previous estimates of nineteenth-century mortality in the United States. The data are confined to available life table information. On the whole, the results indicate little or no decline before the 1870s, higher mortality in urban areas, and much higher mortality among blacks. 
<br>&nbsp;&nbsp;&nbsp;&nbsp;  By the 1890s, it is likely that mortality was declining in both rural and urban areas, although the absence of high-quality data of national scope leaves the matter open.
<br>Whatever the progress of the mortality decline in nineteenth-century America, accurate data on mortality levels become available for part of the country with the formation of the Death Registration Area in 1900
<br> presents Haines 1979a e0 at census years <br>
male 1850 36.5 1860 40.7 1870 42.1 1880 38.2  1890 43.9  1900 46.3<br>
wmale 1850 37.7 1860 na 1870 43.1 1880 39.6  1890 45.1  1900 47.6<br>
and Fogel 1860 value which is similar
Table 2.3  DRA values white IMR .124  urb .138  rur .100  black .234 </p>
<p>p58 Tab 2.3 US-DRA q1 (IMR) 1900/02 124  1909/11 115  (England 1890s 156 1900s 131) q5 1900/02 182  1909/11 161  

</p><p>Using proportion of children reported dead to infer mortality. p61 [equation 2.1 identity of D/B and integral of (q x %born in slice of time) over time-period of births (years since birth of first child born to the women reporting)]    p62  [Looks like can use women's ages or marital duration -- q1 best identified by % dead among women aged 15-19; q2 from women ages 20-24 or marital duration 0-4 ] 
An alternative approach to the indirect estimation of child mortality is the surviving-children method (Preston and Palloni).  ... backward projection of the age distribution of surviving "own-children" by various levels of mortality within a model life table system to the point where the back-projected number of births equals the number of children reported as ever born by the [p63] group of women. 

</p><p>p66 ... For the surviving-children approach ...  p67 ... For the total population, the range of q(5)'s indicated by the various Coale and Demeny model life table solutions is only .004, whereas it is .024 for q(1) and .030 for q(20) (Preston and Haines 1984). Using a formula  Preston and Palloni (1978:84), we estimate that the year to which this robust surviving-children estimate of q(5) pertains is 1896.
[Ji: s-c estimates' ranges are q5 .004   q1 range .024  ]
</p><p>**Results**<br> 
 ... Agreement among the three approaches is close for ages
3, 5, and 10.  ...  If we make the reasonable assumption that the West model life table system pertained in the period 1880-1900 roughly as accurately as it did in 1900, then children of older women were clearly subject to higher mortality conditions than were children of younger women.<br>
These estimates thus suggest that a substantial reduction in child mortality occurred prior to the census of 1900, an implication consistent with some of the research cited earlier in this chapter</p>
<p>*p68* Table 2.5   Age model q1 15.3% (1899) q5 17.7% (1894)    p69 Marital-duration q2 14.7% 1898.7  q3 15.5% 1896.6,  q4 18% 1894.2, q5 18.2%  p70 surv-child method q1 11.8 to 13.3  and q5 ranges 17.3 to 19.7   
</p>
<p>p72  ...  Using the marital-duration estimates  ... Model West level of mortality 13.68 ...
<br> p72 Using the marital-duration estimates, the average Model West level of mortality for marital durations 5-9 and 10-14 years was 13.68 and the average date to which these estimates is 1895.9 (i.e., 1900.5 - (3.4 + 5.8)/2). For women married 25-29 and 30-34 years, the average Model West level was 12.46 and the average date 1884.9. Thus, over the course of 11 years, the improvement in level was 1.22. These estimates translate into a decadal rate of gain in expectation of life at birth of 2.8 years between the mid 1880s and the mid-1890s.</p>
<p>This pace is consistent with Stolnitz's summary of changes in expectation of life at birth in western European countries between the 1880s and the 1900s, which suggested a median decadal rate of gain of 3.05 years (Stolnitz 1955: Table 6). 
(1895.9 level 13.68   1884.9 level 12.46)
THEY TEASE OUT mid80s to mid90s e0 increases 2.8 years -- over the course of 11 years, the improvement in level was 1.22  ...  West 13.68 to 12.46 ...   </p>
<p>p73 Other sources, using different indirect procedures but without direct information on child mortality, have also suggested that mortality declines were occurring in the United States during this period (Higgs 1973, 1979; Meeker 1972; Haines 1979a; D. S. Smith 1983). Direct evidence from registration data (for the limited number of states and cities that had registration systems in place) also points to mortality decline for infants and for children aged 1-4 years in the 1890s (Condran and Crimmins 1980: Table 1).  But the child mortality data analyzed here are the strongest evidence yet available, or likely to become available, that child mortality levels were improving for the United States as a whole in the decades before 1900</p>
<p>Referring again to Figure 2.1, it can be seen that *estimates of q1 and q2 are much less consistent than those at more advanced ages.* In particular, the age model gives relatively high estimates of q(1) and q(2), and the q(2) estimate exceeds all of the estimates of q(3). Before discarding age-model estimates for q(1) and q(2), we experimented with alternative age groupings for women. ... results ... showed an even less regular pattern ... </p>
<p>p74 ...  Therefore we are inclined to disregard age-model estimates of q(1) and q(2).
To derive a single best estimate of child mortality conditions in the United States near the turn of the century. we amalagamated the q(3), q(5), and q(10) estimates from the three different estimation procedures.  *The estimate of a q(5) of .180 for 1895 is probably the single most robust estimate* of childhood mortality that we can make based on the census sample</p>
<p>p98 Child Mortality Index Cleveland stands out for much lower mort, under 1/2 of NYC or Boston</p>

<br>p208 "the mortality decline since (p209) the middle of the 19th c" alluding to McKeown's explanation for "British mortality improvements between 1848 and 1972"  
<br>p208 1900 U5MR 18%  "Its population was also highly literate and exceptionally well-fed."  "The high level of mortality that existed amidst the relatively affluent American population"   
<p>p209 Further evidence that lack of know-how rather than lack of resources was principally responsible for foreshortening life in the United States in the 1890s is the pattern of social-class differences in child mortality.    ... Particularly telling is the mortality of offspring of doctors, which was only 6 percent below the national average.</p>
<p>p210 race  and size of place  "Larger cities had higher child mortality in the late nineteenth century, despite having administrative structures that facilitated the introduction of public-health measures"</p>
