---
title: "SSMM-LIT-Slavery Literature for the SSMM (CSR) Project "
author: "jri, with jrm"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


<a name="TOC"></a>

[General works on US slavery](#GENSLVsect) [Places or Types](#PLACEsect)  [Gender & Family](#FAMsect)  [Demography of US Slaves](#DEMOGsect)    [Slave health](#HEALTHsect)

# to look at: #    

via Fogel, on mortality:     
EM #41 "The Life Expectation of U.S. Slaves c.1830"    
TP #18 "Slave MortalityL Analysis of Evidence from Plantation Records", Richard H. Steckel.
 --also: 19: Logistic Models of Slave Child Mortality in Trinidad


Steckel paper (maybe 1996 chapter in volume about AA women ?)
41. Reductions of 210 grams for Ethiopian women were reported by N. Tafari, R. L. Naeye, and A. Gobezie, “Effects of Maternal Undernutrition and Heavy Physical Work during Pregnancy on Birth  Weight,” British Journal of Obstetrics and Gynecology 87 (1980): 222-26



### Enslaved Americans/ Antebellum Southern Slaves  -- via Steckel and others

Dreadful infancy: Steckel (various); Schneider (2017 EHR) postnatal only, *in utero* good. But what are Schneider's implications for IMR?

Not dreadful infancy:   Steckel dissertation?  ?Carson  Coelho&McGuire

Carson 2008 argues for vitamin D differences for geog difference is slave height

Coelho & McGuire (2000 JEH) downplay maternal overwork and poor maternal/infant diet, argue for hookworm & malaria. Steckel (2000 JEH) reply shows they overstate plausible effects of those diseases.

Steckel, Richard H.  (1986a), “Birth Weights and Infant Mortality among American Slaves,” Explorations in Economic History, 23:173‑98.
______ (1986b), “A Peculiar Population: The Nutrition, Health, and Mortality or American Slaves from Childhood to Maturity," The Journal of Economic History, 46:721-42.
______ (1986c), “A Dreadful Childhood: The Excess Mortality of American Slaves,” Social Science History, 10:427–65.
abc via EEH April 1986;     JEH September 1986;      SSH Winter 1986;




<a name="DEMOGsect"></a>

### demography of slavery/Blacks

#### summary of IMRs

Steckel's 350 (used in HSUS); 

Eblen used by Baptist?

Steckel (1986 SSH) recaps previous IMR's:  Eblen (1972, 1974) 246-275; Farley (1970) 274-302; Evans 1962 182.7; Postell 1951, 1952  152.6 (1817-61);      
p428 Thomas Afflick's remark "Of those born, one half die under one year"


Unsourced claims from [Digital History 2021](http://www.digitalhistory.uh.edu/disp_textbook.cfm?smtid=2&psid=3040).  Slaves suffered extremely high mortality. Half of all slave infants died during their first year of life, twice the rate of white babies. And while the death rate declined for those who survived their first year, it remained twice the white rate through age 14. As a result of this high infant and childhood death rate, the average life expectancy of a slave at birth was just 21 or 22 years, compared to 40 to 43 years for antebellum whites. Compared to whites, relatively few slaves lived into old age. 
 

#### slave/Black demography

#### Steckel & related work 




Schneider (2017 EHR)^[Children's  growth in an adaptive framework: explaining the growth patterns of American slaves and other historical populations]       
via epigenetic: good conditions in utero -- foster catch-up growth after a dreadful childhood         
**NOT** good article; a load of bullshit beyond pointing out the bio-theory point that Steckel's proposed catch-up growth (and terminal heights achieved) are inconsistent with Steckel's story of low birth weights and tough conditions *in utero* . For us: to what extent are relatively healthy adult heights a challenge to our findings of maternal-infant mortality? Is selection (vs scarring) the answer? Recalling Malthus's allusions to very-tall & hearty tribesman with high IMR?



In terms of scholarship, super-light junky (if only for citing Schwartz 2000 as somehow "evidence" on materials conditions of slave life).The paper does point out that Steckel's birthweight results are not robust and easily could be much understated. But of course the paper accepts as US slaves catch-up growth as fact -- when really that is the question isn't it? Are we thinking the height measures of 3-4 year olds are valid? (scrunching/in arm?)


 
p3  Human biologists, anthropologists, economists, and anthropometric historians have tended
to treat these inherited and environmental factors as intrinsically separate Because environmental factors explained more of the variation in mean heights than
genetic differences within a like population, these scholars mostly ignored inherited          
{p4} influences on height to focus on the effects of varying environmental conditions on nutritional status.      
    Within an adaptive framework, it is possible to understand how environmental conditions trigger certain genetically and epigenetically encoded life strategies, which, in turn, affect final height, longevity, and morbidity throughout the life cycle. An adaptive framework for growth can also help historians to make sense of the varied patterns of growth in historical populations. For instance, it can help explain why the timing of the pubertal growth spurt varies widely across populations and why some groups of children experience catch-up growth when others do not.      
    Steckel ... He imputed slave birth weights from other evidence, arguing that they were extremely low compared to modern populations. However, despite slave children’s low starting point, they experienced remarkable catch-up growth after entering the labour force around the age of 10, attaining final adult heights taller than many of their European working-class contemporaries.2 In essence, this article argues that the tremendous catch-up growth experienced by slaves is inconsistent with Steckel’s assertion that slave birth weights, a proxy for health in utero, were incredibly low. Adaptive theories of human growth suggest that poor conditions in utero have long-lasting effects on the growth pattern of children, especially in limiting catch-up growth. Thus, it is more likely that slave children experienced relatively good conditions in utero and had higher birth weights than Steckel argued. Terrible health conditions in infancy and early childhood led the children to become extremely stunted, but the combination of prenatal adaptations for a tall adult height and improvements in their diet and environment made their remarkable catch-up growth possible.  ...
    I I   Before delving into the prenatal and postnatal adaptive models of children’s growth
in detail ... first / explain the concept of adaptation from a biological perspective.  Functional adaptations  ...  improve an organism’s fitness or functional viability within a specific environment ... 

p6   Predictive adaptive responses attempt to align the organism’s physiology with later environmental conditions, conferring long-term advantages, but not necessarily improving the immediate fitness of the organism.    ...   The adaptive mechanisms presented in this article increase a person’s chances of surviving to reproductive age and reproducing, but they also have some negative long-term consequences on health after the typical period of reproduction.        

  Barker / ‘early origins hypothesis’ or ‘foetal programming’,     
    In other words, if a foetus is undernourished in the womb, epigenetic and hormonal processes adapt it to be able to survive better in a postnatal environment with limited nutrients.      
    
p7  There are two sets of long-term consequences of predictive adaptive responses in utero: the first affects the child’s growth pattern during the growing years. Children exposed to poor conditions in utero have a slower metabolism, reach a shorter adult stature that requires fewer calories to maintain and experience faster maturation and an earlier age at menarche, so that the foetus reaches reproductive viability early and has a better chance of reproducing before death.11 The second set of long-term consequences of a prenatal predictive adaptive response influence children’s longterm health and productivity.  ... exposure to poor conditions in early life increased the prevalence of heart disease, stroke, and diabetes in later life.12  ... exposed to poor conditions in utero also experience non-adaptive scarring such as cognitive impairments and lower educational attainment and earnings.13     
 ... three potential adaptive responses to environmental conditions in the postnatal period: an immediate adaptive response of limiting growth to minimize the basal metabolic rate, an immediate adaptive response of delaying the pubertal growth spurt and menarche in females in order to postpone sexual maturity, and catch-up growth when environmental conditions improve following a nutritional or disease insult. 
8 The first postnatal immediate adaptive response is a slowing of growth during
a nutritional or disease insult. ... the child limits increases to its basal metabolic rate that come with growth in order to conserve energy. However, there are costs to this response ... postnatal stunting is not healthy  ...  higher risk of disease because malnourishment weakens the immune system.17   ...  the stunted child has a higher relative level of fitness compared to a child who continued to grow normally despite poor environmental conditions.      
       The second postnatal adaptive response is to delay the pubertal growth spurt and sexual maturity during times of hardship. Despite the fact that menarche would be programmed to arrive earlier by a poor prenatal nutritional environment,  ... menarche can be delayed during periods of poor nutrition in the postnatal environment. This was an immediate adaptive response to postpone reproduction until environmental conditions improved ... also have the unintended consequence of delaying or slowing the pubertal growth spurt, extending the length of the growing period, and lowering final adult height.     
    The third postnatal adaptive response is catch-up growth that occurs when environmental conditions improve during the growing years.  ...  Type A catch-up growth is a period of rapid growth after a nutritional insult that attempts to bring the child back in line with its genetically and epigenetically defined growth curve. Type B catch-up / not / more rapid  ...  Instead, the growth period is extended longer than normal ... Type C catch-up growth includes both type A and type B ...  Catch-up growth occurs most commonly among children who are substantially below modern standards in terms of height-for-age and when the nutrition and the disease environment to which they are exposed improves during the growing years.     
      Children with low birth weight, a proxy for health in utero, are less responsive to hormones signalling growth ...  , their catch-up growth happens more slowly and is smaller on an absolute scale than normal birth weight children.      ... { Swedish study feotal length & final heigth}
      
p9 Therefore, it appears that children facing growth retardation and predictive adaptive responses in utero have a different growth pattern than children exposed to healthy conditions  with earlier maturation, different responses to hormonal growth signalling, and a lower final height potential.  ...  improving nutrition and type A catch-up growth in children who
suffered malnutrition in both the prenatal and postnatal periods may trigger earlier
pubertal development, limiting the amount of type B catch-up growth  ... In any case, catch-up growth is also adaptive because it helps children attain their height potential and confers upon them the advantages of larger body size: greater productivity, health, and self-defence.   ... 

  II The previous section set out an adaptive framework for understanding children’s growth and attempted to explain how some of these mechanisms might have worked.  next 3 sections / demonstrate the utility of this framework by using it to suggest a reinterpretation of the growth pattern of slaves in antebellum America and in the Caribbean.

p14  ...  This new interpretation is built on four key assertions about slavery in antebellum America that have to be carefully justified: first, slave women had to be healthy and well fed relative to women in other historical populations; second, conditions for slave children had to be very bad in infancy and early childhood and improve thereafter; third, slave children’s birth weights could not have been as low as Steckel estimated; and finally, catch-up growth could not have occurred on the scale observed if the children experienced poor conditions in the prenatal period.      

The first assertion ... that slave women had to have been healthy relative to other historical populations.  nutrition {F&E yes; Sutch no; Kiple & Kiple iron&calcium deficient; Gibbs et al. yes; Jasienska no; } US fem slaves 158.9cm       

p15     ... the size of catch-up growth that slaves of both genders experienced is evidence that slaves were given more than enough nutrients to grow despite their high work requirements in adolescence.    

FIRST ASSERTION -- NO BASIS TO PROVE OR DISPROVE.
It is thus credible that aside from their heavy labour, adult female slaves experienced fairly good conditions relative to other historical populations.  ...  the conditions that pregnant slave women and their developing children experienced in utero were superior to the conditions  that slave children faced in the first few years of life.      

SECOND ASSERTION -- NO BASIS TO PROVE OR DISPROVE. 
The second key assertion is that the environmental and nutritional conditions that slave children faced in infancy had to be exceptionally bad and there had to be improvement over childhood and adolescence. There is substantial evidence to support this claim, though the evidence on slave children’s health and nutrition is sparse and fragmented at best. {speculation follows, which pretends to be evidence. Cites Schwartz 56-7: recovery time after giving birth, 60-64: breastfeeding}  ^[While mothers tried to breastfeed their children for at least a year, this could prove difficult, depending on owners’ labour requirements. Agricultural journals and plantation rule books generally suggest that slave mothers were given one month out of work following a birth, allowing them to recover and practise exclusive breastfeeding, but after this month and even during the first month in times of peak labour demand, it became more difficult to maintain an exclusive breast milk diet for their babies. On smaller plantations, infants might be brought with their mothers into the fields where they could be nursed regularly. However, on larger plantations using gang labour or where the slave owners wished to extract more productive labour, infants would be kept either in the slave quarters or in a nursery, with mothers returning two to three times during the day to breastfeed their children.49]     
Slave children were fully weaned probably around one year, though mothers were given less time to breastfeed after eight months.52 {maybe yes, maybe no -- we just don't know, and there is so little sensible/representative evidence}      
p16 After weaning ...   This poor diet was even less plentiful in the first two years of a child’s life, since slave holders often denied weekly food rations to children under the age of two, forcing parents to feed young children from their own rations.55      
 section of ASSERTION TWO IS BULLSHIT, in the sense of wholly unsubstantiated ...
       
p17    According to agricultural journals and guides to plantation management, children working in the fields received substantially larger rations with more meat than children not working in the fields.       

Third, it seems likely that Steckel significantly underestimated slaves’ birth weights. {est birthweight from age3-4 heights}  ... same growth trajectory from birth to {ages 3-4} / as the reference populations ... Growth faltering, or stunting in early life, is common in impoverished populations, and probably occurred in Steckel’s reference populations.64 However, the evidence presented above suggests that infancy and early childhood were periods of extremely poor nutrition and health for slave children, and probably poorer than Steckel’s reference populations. Thus, it seems plausible that slave children would have become severely stunted by the time they reached the age of three or four, especially since growth velocities are highest before the age of three.65    ...  Lumi 
p18 {Lumi} mean birth weight around 2,400 grams, but at maturity women were only 147 cm tall, nearly 12 cm shorter than female slaves in the US South.68 Thus, while it is impossible to know the birth weights of slaves, this evidence suggests that Steckel’s predicted birth weights are  implausibly low and that slave birth weights were probably substantially higher.     
     ... Analysing the potential causes of low slave birth weights also leads to suspicion of Steckel’s figures  { low-height/sickle cell/maternal malaria for -380gm, hard L during pregancy -680 gm } First / likely / pregnant women / given less physically demanding tasks ... Agricultural journals and a general attitude of paternalism among slaveholders suggest that this was a strong norm. **REALLY? "a general attitude?**  ...
     Second, more recent historical and medical research has shown that early neonatal mortality (deaths in the first seven days) is a better predictor of foetal health than infant mortality or neonatal mortality (deaths in the first 28 days) {p19 refers to Steckels plantation sample}     
     Third, a large percentage of stillbirths and early neonatal deaths historically were caused by complications during childbirth that had little to do with foetal health and thus predictive adaptive responses.    
Fourthly, Campbell’s finding / work release {FINDING -- would we so describe?}       
Finally, the magnitude of the catch-up growth that the slave children achieved is unprecedented and would seem implausible if slave children were exposed to such terrible conditions in utero. {WHAT? CIRCULAR -- you are looking for EVIDENCE that Steckel understates Bweights IN ORDER TO ARGUE THAT THE CATCH-UP IS IMPLAUSIBLE }   Modern studies have **mostly**? found catch-up growth of less than one standard deviation relative to the modern mean.79 Thus, it is clear that the catch-up growth of American slaves was truly remarkable, especially considering that the intervention sparking catch-up growth occurred in the first half of the nineteenth century when even the best nutritional and environmental conditions were far below modern levels YECH: first 1/2, nutrition/enviro **far below modern** 

p20  ...  {Indian girls adopted in Sweden}   Thus, the low average birth weight of American slaves seems inconsistent with their remarkably high level of catch-up growth. Their unique pattern of growth would make more sense if slave children developed and set their metabolism and growth trajectory in a relatively good uterine environment, then faced severe deprivation in infancy before experiencing catch-up growth as conditions improved in late childhood and adolescence.

IV  The adaptive framework seems plausible in explaining the growth pattern of American slaves, but explaining why Caribbean slaves would also experience substantial catch-up growth is more difficult.  In terms of maternal health, slave women in the Caribbean were substantially shorter than their American slave counterparts and shorter than or equal to women in England and Ireland.     Slave {p21} women born in St Lucia and Trinidad were 153.3 cm and 155.6 cm tall respectively,
and slave women born in Africa were 1–2 cm shorter.85 {Higman?}  ...  slaves in the Caribbean achieved substantial catch-up growth because their material conditions did improve across their growing years. However, their potential for catch-up was limited by the prenatal predictive adaptive response, which set their growth trajectory and metabolism at a lower level. Although conditions were still probably worse in the postnatal period than the prenatal period, the mismatch was smaller, which meant that Caribbean slave children did not fall behind modern standards as quickly as American slave children. Their metabolism better matched their postnatal experience. 

V      {THIS SECTION SEEMS LARGELY IRRELEVANT TO SSMM research}
With the lessons of the previous case study in mind, we can now explore the implications of an adaptive framework of growth to changes in the growth pattern of human populations over the past 150 years.^[recall p4 "After discussing this case study {slaves}, this article draws on the secondary literature to develop four stylized facts about children’s growth patterns in the past and places these stylized facts within the adaptive framework of growth. The article concludes by offering some ideas about methods and topics ripe for future research.]  discussion / rather speculative ... However, a perusal {22} of the secondary literature does allow for the development of four preliminary stylized facts ...      
 
p22     four preliminary stylized facts that could guide a more systematic and robust analysis. First, early life health conditions have been relatively stable over the past 150 years in the western world. {WHAT ??? 1870-2020 ... urbanization?}.  Second, there is considerable heterogeneity in early life health around the world today, with some developing countries experiencing very low average birth weights. Third, children in the past experienced the pubertal growth spurt at later ages than modern populations. Fourth, there has been a secular decrease in the age at menarche for girls in the west over the past 100 years.      
    at least from the mid-nineteenth century onward, it appears that early life health conditions in the west were fairly good. *Where birth weight evidence is available*, mostly for working-class populations, it seems that in the second half of the nineteenth and early twentieth centuries, average birth weights in North America had already reached their modern levels (table 1).       
p23 children in North America and Europe were never exposed to the worst intra-uterine conditions now present in the developing world. {does he mean *white* children?}         
Despite relatively good early life health conditions, the delay in the timing of the pubertal growth spurt and later age at menarche in western populations in the past suggests that these children must have been making immediate adaptive responses to delay maturation in response to poor nutrition or  high levels of morbidity in the postnatal period. Thus, the secular increase in adult height over the past 150 years was probably caused by a reduction in postnatal stunting over time.99 {Hatton}


STECKEL 1986 etc for IMR   -- Steckel's work is very loose/sloppy, and his IMR estimate is built from slim evidence ... so how do we handle that? 

why does he not also use the Bundi?  Malcolm doesn't have birth weight for Bundi ...

Tanner 1991 W Aus aborig n=340 p322 3.1kg birthwt    Manus 2.7 kg

Steckel (1986 EEH)  goofy extrapolation of birth-weight from child-height via regression with n=8 which is dominated by the Lumi who are 12.6% below standard while other 7 are 4.8% and less (and slaves are 13.3%). And then a goofy extrapolation from pseudo-weight to neo-natal IMR 152 or 156 ...    

p180 modern standard 3.5 kg and 3.4 kg for males and fems, average 3.45  

{ Basic idea is the tiny Lumi people give Steckel a birth weight ... but the  Wark article says the women are small 145-148 cm  42-46 kg;  US slv women 62.51" or 159  -- >4" taller!         
Confirmed in Tanner et al 1966 p626 m 3.5y 50th 98.0, f 3.5y 96.8        
Note height or weight by age refer to +/- 6months while Steckels ages are 6mos more (via assumption of uniform age dist) ... 1976p15       
Eveleth & Tanner 1991 Many countries collected and analyzed new data in the 1970s and 1980s and only these are presented here in Table 2. Data from 1955-70 will be found in the first edition of this book. We use the older data for comparative purposes in some of the figures since secular trends in worldwide growth will be an important focus in this edition.      
Lumi 68.6% implies birthweight 2.3667  -- extrap on slv/Lumi heights gives 2348 grams, or 1.2% more than Steckel's  --         
Evel & Tanner 1976 p412 Lumi male 2.4 kg 68.6% ,  p406 male 3y 83.7cm  4yr 87.4cm, fem 84.2 88.9  m weights 3,4 are 10.7, 12.1  1966std 3.5y 15.6       
Wark article, ages are +/- 6mos :  Lumi male 3 83.7, 4   Birthweight 2.4 kg is male & female, implying % of standard is 0.69565 or 69.6% and not 68.6%; age 4 males 12.1 kg (SD 1.4)    }

p181 Lumi relative to standards: birth weight 0.686, age 3-4 height 0.874% ; slaves height 86.7% of modern standard, regression implies 2320 grams --   Table 3 has birth-weights and age 3-4 heights relative to standards -- cites, w/o pages, Eveleth&Tanner 1976 book, and Tanner et al 1966 articles

4-yr-old m slave 35.9" or 100.33 cm  3yo slave 84.7  Lumi  4yo m87.4 f88.9cm 3yo 83.7, 84.2       
standard male 4.5y 105.0 cm    3.5y 98.0 used by Steckel for 3yo slave

2.320 kg (2250-2380g 80%) American slave newborns among the smallest documented for poor populations in developing countries of the mid-20th century (Meredith, 1970; WHO, 1980). 

p 183 Table 5:  Jayant, shifted, for birth-weight distribution; US vital stats 1957 for NNMR by weight pp 211 215 218

Nonwhite births delivered by nonphysicians outside of hospitals and institutions in
metropolitan counties.  211    215   218
kg,NNMR 2.5-3 24.7, 3-3.5	12.9   ... Steckel seems to assign that whole effect to birth weight, but clearly weight here proxies for wellness more generally?



Steckel (1986 SSH)  IMR of 350 from 1986EEH  
p454 n5 neonatal birth to 4 weeks / via n17 "227 per thousand is a reasonable {p455} conjecture for the slave neonatal mortality rate.   ... combined with a postneonatal mortality rate of 162 per K calculated from plantation records ... imply {sic} an infant mortality rate / Table 1  of 350 per thousand      
n17  neonatal mortality rate of 152 from estimated birth weights and a schedule of neonatal mortality by birthweight (Steckel 1986a {EEH})     
n39 use Haines and Avery (1980:95), "The avg of the  I M Rs (male and female) for the Brass logit and the Model West life tables in H and A (1980:95) is 179.1" **OUCH!** those are for total US pop, and the Brass model has qm/qf < 106%  (West 117.3) -- he acknowl that B+W issue in JEH table


Steckel (1986 JEH) "Peculiar Population ... "  
  The stature of young slave children would trigger alarm in a modern pediatrician's office. At age 4.5 boys on average reached only centile 0.2 and girls attained only 0.5        
  p732  If the height data are credible, then why were young slave children so small? The origins of poor health can be traced to difficult periods of fetal and infant growth.24 Slave newborns probably weighed on average fewer than 5.5 pounds or 2,500 grams compared with modern standards of 3,450 grams
 p733 table with IMR, cites SSH 1986 (which cites EEH! -- oh, he is SLOPPY)

Steckel (1992 WCC )  refers to the 1986 trio aEEH, bJEH, cSSH and 1987  for white IMR, SSH-n39, which is a mess/BS. 

Steckel (1987 ann hu bio). Mostly on heights and catch-up growth, but some attention to issue of measurement of heights on ships; also discussion of breastfeeding and maternal work. This paper cites 1986 EEH SSH   for IMR ~350, with 4q1 ~ 201 on large plantations

Steckel (1979, 1992reprintWCC)  11 plantations, not representative ... 
 

Meeker (1976 EEH) "Mortality Trends of Southern Blacks, 1850-1910"    DRECK: via life-table e10 emancipation reduces health (recover by 1900)
-- Implications from West Model life tables and census data
offers e0 via population data and West model life tables
p22    the Model West mortality levels which have been argued to best represent the life expectancy of blacks during the last decade of slavery, Model West levels 5 and 6 {IMR values there are 5: 296, 256 for 276; 234.38 271.35 for 253 }
p23 my results show a significant drop in life expectancy at birth compared to the slave populations in 1850 and 1860     
p25 It shall be concluded that the most reliable evidence points to a worsening of health after the Civil War.
p26    health improved during the decades 1880-1900, ... level of life expectancy for blacks in 1900 was on a par with that for slaves during the years 1850-1860.
p31  The finding that slaves enjoyed better health than their post-Civil War free counterparts could therefore be due to their having reduced levels of nutrition and housing; to their being more urban; and to their having decreased levels of literacy {no}
p37 



Eblen (1974 Demography) census-pop & various model LTs
"New Estimates of the Vital Rates of the United States Black Population During the Nineteenth Century"      
abstract: 19C e0 33.7   m0  male 266-278; female 222-237   birth rates fell 53.2 to 43.8     

p302   After 1900 black mortality rates improved rapidly relative to earlier periods, and the period beginning about 1900 is perhaps best considered separately as one of demographic transition.  Life tables for the black population, based on deathregistration statistics, begin with the year 1900

Eblen 1974  via pop survival, model life tables IMRs   Black 1900/1910 only a little above Haines's 1850-80 white

Eblen (1972 Pop St) "Growth of the Black Population in Ante Bellum America, 1820-1860"  census-pop & West Model LT
 
possible to construct a life table for the  *ante bellum* black population having approximately West level 5 life expectancies up to age 25  ... but <287>  showing a female infant mortality of about 225 instead of 307, and a male mn0 of 275 rather than 368.  These rates would undoubtedly be more credible and convincing. {307 is m, q is 256; 368 is m, q is 295.46      
Translate his remarks from m to q:  female IMR 196 instead of 256, and male IMR 234 instead of 295   use fem levels 8; 6 for male m to q }   -- 196,234: 215 // 256,295: 275.5
 
Farley (1970 [*Growth of the Black Population*](https://archive.org/details/growthofblackpop0000farl/page/n5/mode/2up))      
p1 planters "needed" laborers so they imported slaves       p2-3 The fertility rates of blacks must have reached a biological maximum before the Civil War. {see ch 2;      }   The Negro growth rate began to slacken after 1880, and for a long time the growth rate decreased. Reduction in fertility  { 1930 general fertility rate ~100 vs ~250 in pre-Civil War period (p2)  1955/59 ~160  p5 figure shows children ever-born per 1000 women for birth cohorts 1835/40 7000 1855/60 6400  1875/80 3800   ... 1915 2500 1935 3700  p6 e0 1930 48, 1966 64   1900 cities in DRA IMR among blacks exceeded 300  p7 quasi-stable pop techniques / pre-Civil War era / 250-300 IMR e10 +41 yrs  1930 e10 +45 } with the exception of a possible reduction in infant and childhood mortality, there may have been minimal gains in life expectation during the seven decades following the Emancipation.    Contemporary accounts indicate that the death rate among blacks went up sharply during and after the Civil War. Regular food supplies were interrupted and contagious diseases spread among the camps occupied by many of the freedmen.  not possible to obtain demographic measures of these changes in mortality. { hints at possible deterioration in living standard between 1876 and 1930, via rural overpopulation   p9 recap of Franklin Frazier's views with urbanization causing marital disruption p10 early 20thC pellagra via peonage and lack of gardens or cash   p12 by 1930s 20% adults have syphillis/gonorrhea  } p12 In conclusion, between the time of the emancipation and the Depression, only limited improvements were made in health conditions among blacks. Certain fertility inhibiting diseases probably became more common and helped to cut the birth rate. Since the 1930s, health conditions have improved.     
p33 Table 2-2  IMR 1840-50 274  1850-60 302  (GFR 240  221)    e0 m,f 33,35   30,33  { e0 about 30, 1850s Mass 39, England 1841 41}   
p70 IMR 1900 WashDC 366, Balt 356, NYC 348 (1900 census); Balt 1916 219, 1930 94; Phil from 160 to 100 Holmes S J The Negroes' Struggle for Sirvuval 1937 Tab xxiv     p74 IMR  1937 83, 1956 42, 1967 35 

Farley (1966 Demography) "The Demographic Rates and Social Institutions of the 19thC Negro Population: A Stable Population Analysis" IMR RISES AFTER EMANCIPATION      
p395 1830-50 IMR 276  1850-80 300
p397  Prior to emancipation, masters may  have provided some care for pregnant  women and infants, since additional slaves  usually meant capital gains. The absence of  such care after the war and the general  decline in health conditions probably pro-duced the higher infant mortality rates  indicated by the population models, and <p398> it is likely that three out of every ten  babies died before age one.  Quasi-stable population techniques have used to assess the fertility and mor-tality levels of the nineteenth-century Negro population. The results indicate that health conditions generally deterio-rated in the second half of the last cen-tury, while fertility, in the absence of any regulating institutions, remained very  high, producing a rapidly growing popu-lation

Postell (1952 Pediatrics) as in 1951, IMR of 152.6 (170 deaths, 1114 live births) 
      
       ... There was nothing the planter was more interested in than the increase of his slaves through the birth and rearing of children, and within the bounds of medical knowledge of the period, he took the time and effort to promote conditions that were conducive to the rearing of large families.      
      The first care of the planter was the prenatal care of the mother. Rules were drawn up by the planter and overseers were instructed in the care of the expectant mother. Crude as this care was in comparison to our knowledge today it was still far superior to anything the Negro had known in Africa, and it compared favorably with the medical knowledge of the ante-bellum period.

 - lighter tasks, midwives, 4 weeks postpartum rest then 2 weeks or more light work ... planter remarks that children "are not likely to be neglected, as they pay a good interest upon the amount of care and expense bestowed upon them."  p539 breastfeeding first month   ... 
         
         
        p539    Since the mothers were too valuable as field hands to be permitted to remain home after they were well enough to return to the fields, the responsibility of caring for the infants was the duty of the "children's nurse." 


Low % infant deaths in first week/month? which he interprets as successful breastfeeding and then diarhea (bottle-fed?) One example of infant/child food sounds pretty bad, and like Steckel says, doesn't include meat ...


#### other demography of US Blacks

Hacker (2020 SlvAbol)  ** high IMR implies high 
  Thus, despite using somewhat different methods and assumptions, most researchers agree that birth rates for the black population were in the range of 50-60 births per thousand population in the early nineteenth century.  ...   n11    ...   If Richard Steckel is correct that age pattern of slave mortality did not conform to the age pattern of white mortality—compared to the white population, slave infant and child mortality rates were elevated relative to adult slave mortality rates —birth rates derived using stable population methods and Jacobson’s life table may be too low. Given that the estimated nineteenth century birth rates are already near 60 births per thousand, however, it is difficult to see how much higher slave birth rates could have been. Richard H. Steckel, ‘Birth Weights and Infant Mortality among American Slaves’, Explorations in Economic History 23, no. 2 (1986): 173-198.



Elo & Preston (1994 Demog) re: mort at older ages (likely older age mort understated via age-errors)       
p428 In this paper we investigate the consistency between census data and death registration  data for African-Americans from 1930 to 1990.   / conventionally constructed African-American death rates may be seriously flawed as early as age 50



Zelnik (1969 JASA) "Age Patterns of Mortality of American Negroes: 1900-02 to 1959-61"   Official life tables for US Blacks are compared to C&D West model tables. He leans toward view that West model doesn't fit US Blacks 1900-1960.         
ABST: / Large differences between the age patterns of mortality as reflected  in official U.S. life tables exist for whites and Negroes. /
{ is it from bad data on Blacks?       
 approach is to show West model LT level associated with a 5qx -- 1 high mortality; level 24 low mortality 
435 puts aside 1901 and 1910 tables;  level of IMRs: 1901 6.6, 1910 9.6, 1920 14.2, 1930 17.0,  1940 19.1, 1950 20.6, 1960 21.3      
Plots of levels vs age tend to be U-shaped, suggesting prime-age mortality worse than expected from infant & child mortality? E.g. 1920 shows level below 8 for males ages 20 to 60 -- e0 below 35 ... I DEEM IT A JUNKY APPROACH      
441 re:1960 In effect, it does not appear as if undercounts in the census are  primarily responsible for the differences between the official life tables and the  model life tables       


Zelnik (1966 Pop Studies)  birth rates 1830 ~59-60 1850 ~52-54     -- 1830 value is a little above Farley's 54 -- Ji doesn't quite follow this; something about Zelnik assumes stable but fert was declining so older ages larger? 
  

HolmesSJ (1937) *The Negro's Struggle for Survival; a study in human ecology* (inet arch); oddball racist tract that provides some US data by race. Interesting review in [Science and Society](https://www.jstor.org/stable/40399228)

US Census 1918 *The Negro Population of the U S, 1790-1915.

#### Non-US Black Demography
 
Trinidad - a. meredith John, book and articles, using data from Fogel & Engerman. 

"Plantation Slave Mortality in Trinidad", 1988 Pop Studies     
p173 plantation slave children 0-4 828 boys, 837 girls 
p180 "more than one-third of newborn plantation slaves in Trinidad died before their first birthdays.  fewer than half of the slaves on a Trinidad estate reached their fifth birthday: about 55 (+/- 5) per cent of boys and 58 (+/- 6) per cent of girls died before their fifth birthday.

JohnAM (1988 book p194) Trinidad Plantations 1813 SR04 98.9 (828/837; 3/4 CI 93.5-104.7)  n too small 

South Africa?   Evidence from other Black populations with high IMR??


### high IMR populations?

Mubiri et al.   big drop NNMR 1500-1999 78.9, 2000-2499 17.7, 2500-2999 6.5         


Jayant (1964) *perinatal mortality*  3822 single births  1947-61 in private maternity hospital to upper social stratum; 2279 single births in charity hospital in 1962. Born dead or died within 7 days are non-survivors.
p263  perinatal mortality % priv, charity: all 4.6, 9.7; 3.5-4.5 lbs 26.4%, 20.5%, 4.5-5.5 lbs 8.1, 6,0  {charity hospital has lower mortality at low birth weights, higher mort ar higher birthweight -- can we make sense of that? low-birth weight among the affluent are non-well babies; low-birth weight among the poor are regular babies with poor maternal nutrition? }  Private hospital 50% mortality at about 3.3 lbs (male mort<fem 4.6:4.0; charity 9.7:7.7); charity hospital 50% at about 3 lbs      
Jayant has critical weights (avg morts 4.0 4.6) at f 5.2 and m 5.4 for private. Optimal weights 7.5f 7.4m for mort <2% .  Charity critical (avg morts 7.7, 9.7)  f 4.4, m 4.5      
via private: 4.5 lb male 12%?     via charity: 4.5 lb male mort 9.7% 

birthweight 4lb male pmr 184 (charity) or 225 (private)

   the logarithm of the ratio of probability of survivors to non-survivors {BASE 10??}




<a name="GENSLVsect"></a>

## General works on US slavery 

[Logan (2022 JEP)](SSMLogan.html) ... nothing for SSMM-slv (hints of interest in material conditions of life)

    The obvious attributes of slavery—forced extraction of effort, slow work, resistance, and violence—seemed incompatible with high levels of output produced. 


Baptist 2014 book  -- uses Eblen 1972       
[the expansion of cotton production came from increasing use of "torture" to "push" enslaved workers to produce more. SW slavery worse; cotton kingdom worse; Narrow evidential base (relies on some narrative and autobios)]

<p>
Note that Baptiste's view focusses on normative dimension (how horribly overseers acted to elicit effort) but that doesn't bear on the caloric needs of such work -- in short, chemistry/physics of work trump his efforts to suggest some magic from torture    
<br>
Pitches notion that cotton kingdom was worse for slaves, compared to non-rice east coast -- de-skilling, loss of garden plots and livestock, switch from drivers to overseers,     
</p>

encountering and that was emerging on the frontiers of the early nineteenth- century South was inherently new.  
p113 Entrepreneurs redirected left- handed power by measuring work, implementing continuous surveillance of labor, and calibrating time and torture     
p119   Lydia [walking back from field] carried a baby on her back in a sling of cloth [late for roll, brutally beaten with horrific large whip]    p120  southwestern captivity distilled and intensified slavery     ... Survivors of southwestern torture said their experiences were so horrific that they made any previous “licken” seem like nothing.     
p121 the new pushing system: a system that extracted more work by using oppressively direct supervision combined with torture ratcheted up to far higher levels than he had experienced before. Between 1790 and 1860, these crucial innovations made possible a vast increase in the amount of cotton grown       
p122   Table 4.2 gives infant death rates for 4 SW cotton plantations -- he cites 2 sets of papers and Steckel's thesis (no pages). His Watson infant death rate is 280 while Steckels IMR is 247 (both via 81 deaths)

The rate of infant mortality in the new slave labor camps was extraordinary: one of every four children born died before reaching his or her first birthday.
p123  girls 256  boys 296  115.6%     --- -24  +16 = -8  .. 276  ... cites Eblen 1972  Weird he does not use Steckel?  
p130  Enslavers used measurement to calibrate torture in order to force cotton pickers to fi gure out how to increase their own productivity and thus push through the picking bottle-neck.    
p142  every cotton labor camp carved out of the southwestern woods used torture as its central technology.



walter Johnson 2013 BOOK River of Dark Dreams

p170 memories bespeak spaces and routines that were dense with the threat of  vio-lence inflicted on bodies exposed by their labor.   ...  Slave-holders used the well- grooved patterns of  plantation life to construct a simulacrum of  domestic and agricultural order over sexual predation

p193 reformer Phillips says 3/4 child mortality "Perhaps he exaggerated; his essay was a philippic, designed to spur his society to change. Perhaps the real figure for child mortality was a mere 60 percent, or 55, or 50.n41"   41: p467-68 Follett estim that some Louisiana sugar plantations had a 55 percent mortality rate among slave children within the first year of life  Afflect 50% u1 10% more 1-5 ... 55%  


p195  Being enslaved was not only a condition characterized  by  vulnerability  to  sexual  assault—it  was  always  al-ready  a  condition  of   sexual  violation.  n46 Debh Gray 

p464notes   almost impossible to imagine a scenario in which most field hands did not suffer from some level of  malnutrition. 


Pargas 2011 Slv&Abol
 Brenda Stevenson, Wilma Dunaway : VA slave women full labour quotas until giving birth, return to work after 2-week confinement (rest). Then childcare by sibs & elderly.  LowerSouth studies lighter tasks during pregnancy, 4wk+ confinement.   ISSUE: slave childhood "stolen" (early work) or separate from plantation economy

</p>

Kaye 2010 book

Kaye 2002 Slv & Abol       
In  the Natchez District of Mississippi, slaves cultivated solidarity in ways that created not one community but many.
      There, the name that slaves put to the grounds of solidarity was not ‘community’ but ‘neighbourhood’. They imbued the term with social as well as geographical meanings that were as rich as they were precise. Slaves defined neighbourhood in terms of adjoining plantations because that was the terrain where they engaged in the relations of power – labour, property, kinship, discipline and sociability – that constituted their society.



JonesJaq 2010/1985 *Labor of love, labor of sorrow : black women, work and the family, from slavery to the present*      
xv   One of the criticisms of the book when it was first released was that it presented an overly sentimental view of black families s (as revealed in the title, as well as the text), oblivious to the realities of husband-wife and parent-child relations, especially as those relations played out in households under great stress. I agree with that criticism, up to a point. Yet the story told here focuses not on the social or psychological dynamics of black households, but on the historic forces that have shaped the labor patterns of black women at home, in communities, on antebellum plantations, and in the paid labor force. This edition supports the view that as a group, black working women through history have made heroic exertions to provide for their families and to resist the dehumanizing effects of a marketplace undergirded by white-supremacist ideologies.    


<p>Berlin 2003 book (prestigous historian's overview) *Generations of Captivity: a history of African American slaves*
<br>sense that older areas had milder slavery? anticipates Baptiste's extreme view of torture-horror of southwest (New South?). Maybe an implication/prediction for comparative IMRs and thus CSRs ...  
</p><p>Draws on Steven Miller's paper in cultivation and culture -- 1993, mentions charles Ball. As do most general works since?

</p>

<p> wilma a Dunaway (2003 CUP) [The African-American Family in Slavery and  Emancipation](https://books.google.ca/books?id=gXdbikvSXJMC)
MINOR WORK   Jane T Censer raises doubts about the arguments, suggesting the narrative sources for applachia give a bleaker view because interviewers were A-A Fiske students, unlike regular WPA folk. Also Albemarle VA etc included in Appalachia.

cited by Hilde (2020 Introd p2n4p291)   Wilma Dunaway argues that Mountain South masters had an incentive to inadequately feed and clothe their slaves, leading to higher levels of malnutrition and mortality than in the Lower South. Dunaway, African-American Family, 86–97, 100–113, 273, 282; Fogel and Engerman, Time on the Cross, 5, 109–126.

  These voices recount experiences that are representative of a majority of slaves of the Mountain South, ... low black population density and small plantations. What they have to say is startling b/c they are reporting a past that contradicts the dominant paradigm. The conventional wisdom is that owners rarely broke up slave families; that slaves were adequately fed, clothed, and sheltered; and that slave health or death risks were no greater than those experienced <p2> by white adults. </p>

KayeAE (2007 UNC) *Joining Places: Slave Neighborhoods in the Old South*
the first book about slavery to use the pension files of former soldiers in the Union army, a vast source of rich testimony by ex-slaves    
Ji's sense it highlights autonomy/agency     
p51 Ch 2 "Intimate Relations"    
Mary Helam 1845 forced to marry 3rd husband william Madison ; they name first child after friend's husband but that baby died at 1 month; two survive to adulthood (m & f). {more about mary Helam in intro and throughout?}

p54 Slaves devised a structure of intimate relations that enabled and obliged them to collaborate with and discipline both slaveholder and neighborhood.  ... Marriage produced a great many nuclear families everywhere in the South.14 <n14  WhiteDG In the Natchez District, living together did so, too.

p74 Slave marriages across plantation lines comprised somewhere between one and three of every ten marriages, studies of the Works Progress Administration narratives suggest, and the proportion was higher in some states, such as South Carolina.99 <n99 Escott 27.5% {but that refers to different owners, could reside/work in same plce (rentals, relatives own)} ; Crawford 10.4% ; emily West extrapolated 19% from Crawfod and estimated 33.5% for SC;  Escott (1979 Remembering), Crawford    West  *Chains*

p77 Indeed, no tie bound the neighborhoods of southwestern Mississippi more tightly than marriage. After the wedding, often a neighborhood event, the husband became a fixture over at his wife’s quarters. The proximity of adjoining plantations facilitated more frequent visiting than was possible in an ‘‘abroad marriage,’’ which typically permitted couples to spend weekends together. In the Natchez District, some married men had a standing pass to spend one night during the week, usually Wednesdays, as well as Saturdays and Sundays with their families.∞∞π Edward Hicks beat the path every day between his cabin on Oak Ridge and his wife’s, only three-quarters of a mile off on the adjoining Grant place.118 {edward Hicks, absalom Grant, case 5516}


saidiya Hartman *Scenes of subjection: terror, slavery, and self-making in 19th america* Highly influential. A view of US slavery that makes the high levels of production quite mysterious? Emphasis on violence generally and sexual violence more narrowly. Sometimes gives a sense that emancipation did not make much difference?    
(2022 edition)  I intended to bring into view the ordinary terror and habitual violence that structured everyday life and inhabited the most mundane and quotidian practices. This environment of brutality and extreme domination affected the most seemingly benign aspects of the life of the enslaved and could not be eluded, no matter the nature of one's condition, whether paramour, offspring, dutiful retainer, or favored nursemaid. {field hands' relative autonomy?}   
      With the advent of Emancipation, only the most restricted and narrow vision of freedom was deemed plausible: the physical release from bondage and the exercise and imposition of the contract ... In the aftermath of slavery's formal demise, the old relations of servitude and subordination were recreated in a new guise.    ... the nonevent of Emancipation ... 

 The plantation was hell, factory, killing ground, Sodom. In attempting to explicate the violence of slavery and its idiom of power, *Scenes* moved away from the notion of the exploited worker or the unpaid laborer toward the captive and the fungible, the commodity and the dominated, the disposable and the sexually violated, to describe the {25} dynamics of accumulation and dispossession, social reproduction and social death, seduction and the libidinal economy, and to highlight the vexed relation of the enslaved to the category of the human. ... Slavery was the blind spot in critical theory n5  ... Conservative scholarship ... denied the magnitude of the violence required to produce the human commodity and reproduce the relations of master and slave, and replicated the assumptions of romantic racialism and the plantation pastoral by describing slavery as a paternal institution characterized by reciprocity and consent, "Aunt Jemima in Dialectics" n6  The work of radical historians and intellectuals was devoted to refuting such assertions and celebrating slave agency, excavating slave culture, demonstrating black humanity and resilience in the face of dehumanization, recognizing the enduring totality of African beliefs and values despite the rupture of the Middle Passage, and fundamentally challenged the idea of the damaged person or pysche produced by centuries of enslavement. ... vitality of black culture, the autonomous zones created in the slave quarters and the provision grounds, and the strength of the black family. 

Hartman (1997)
Intro:  The period covered thus extends from the antebellum era to the end of the nineteenth century. Despite the amazing tumults, transitions, and discontinuities during the antebellum period, Reconstruction, and the Gilded Age, I feel this scope is justified by the tragic continuities in antebellum and postbellum constitutions of blackness.    
p10 Notwithstanding the negatory power of the Thirteenth Amendment, racial slavery was transformed rather than annulled. As suggested earlier, this transformation was manifested in debt-peonage and other forms of involuntary servitude that conscripted the newly emancipated and putative free laborer, an abiding legacy of black inferiority and subjugation, and the regulatory power of a racist  state obsessed with blood, sex, and procreation.

p198 It is not my intention to argue that the differences between slavery and freedom were negligible; certainly such an assertion would be ridiculous.



<p>Fogel (1989 *Without Consent or Contract* main volume)     
Ch 5 The Population Question     
Franklin on US healthy;
p 119 Anti-Slavery Reporter on slaves's natural increase in US vs UK sugar regions "superiority of the U S in the physical treatment of their slaves."n11
p120  Weld's view that "much hardship and great cruelties without experiencing so great a derangement of the vital functions as to prevent childbearing"    
p128      One of the more important discoveries is that the century-long decline in the mortality of U.S. slaves probably came to a halt during the 1810S or 1820s and then began to rise ...  plantation records indicates that the death rates of infants rose by about 24 percent between the 1820s and the 1840s

p145 It thus appears that diets sufficient to maintain the health of nonpregnant women engaged in heavy labor were insufficient to produce average weight gains in pregnant women that would yield adequate average birth weights and forestall high infant death rates. 

**MORTALITY RATES** n63 refers to EM #41 and TP #18 (Steckel's revision of SSH 3)  

</p>

### Slave Community & Culture

Rawick 

Blassingame 

Stuckey (1972, 1988, 2006, 2013)  {Agency; US-wide African-american culture}      
2013 2nd Ed **Slave Culture** {searched infan/death/mother/nursing/childcare/breast gets breastbeating (dance)}       
{intro to 2nd reflects back} p xv the twenty-fifth anniversary edition of ***Slave Culture** appears against a backdrop of inattention by historians to the arts and American slavery that not even Douglass’s genius has yet reversed. We may take solace, however, from the fact that the judgment of most American historians con-cerning such matters need concern us no longer. They now stand practically alone in denying African influences that have steadily been demonstrated by scholars in anthropology, art history, linguistics, music, literature, dance, and still more disciplines.    
xvii  {highlighting Frederick Douglass on music/song} He sometimes thought “the mere hearing of those songs would do more to impress some minds with the horrible character of slavery, than the reading of whole volumes of philosophy on the subject could do.” His insights on the social implications of slave music should be of lasting interest to artists and intellectuals at the highest reaches of American life.     
Intro ... p15 quotes Herskovits:  In all those parts of the New World where African religious beliefs have persisted, moreover, the river cult or, in broader terms, the cult of water spirits, holds an important place. All this testifi es to the vitality of this element in African religion,    ... n409 use Curtin not the Atlantic Voyages project     
p38 {African content of slaves' Christianity}  When the convert in “How the Slaves Worshipped” is held underwater— under the Kalunga line—he “dies a small death, and then is reborn, emerging from a short commune with the ancestors.”    
p33  {Va & Md}  Born into slavery in 1843, Simon participated in the most sacred of rituals in the 1850s by the age of thirteen—a common practice in slave communities in both the North and the South, as children, within a year or two after they were able to walk, joined in some ceremonies, especially in the ring shout. In fact, slave culture was, despite its centeredness upon the elders and ances-tors, a culture in which the very young played a more vital role than scholars
have assigned them.
p42 {re Simon Brown} In the 1850s, these youths participated in burial customs common to Central and West Africa, customs known to vast numbers of slaves, although by then second- and third-generation Africans greatly outnumbered those born in Africa.   ... Brown tells us that slaves helped each other in illness as in death. If a woman fell ill, “other women came over to help her with the chillen, or to cook the meals, wash the clothes or to do other necessary chores.”      ... Sometimes a man or woman with a healin’ touch would brew a herb tea, mix a poultice, or apply peach tree leaves to the fevered brow, to help the sick git well. All of this lovin’ care cheer’ up the trouble’ soul, whether he got well or died."
p220   ... Among Negro peoples a man’s name is often identified with his very soul, and often with the souls of ancestors. Parents name children after rela-tives, heightening the spiritual significance of their names, all the more after the death of a relative. The efforts of some West Africans, the Ashanti and Yorubas among them, to bring the living and dead closer, thereby lessening the pain of death, is illustrated by their rituals on the death of an elder and the birth of a new member of the family. The placing of food on the burial mound or at the crossroads and the naming of infants after the deceased are related means of seeking renewal and approbation from the spirit of the dead, and were no doubt carried out by many for that dual purpose in slavery even when non-African names were given to infants    ... Since Ashanti in Virginia, South Carolina, and North Carolina joined Kongo peoples and numerous other groups in the same locations in practic-ing West African burial ceremonies during slavery,


<a name="PLACEsect"></a>  



<p>Follett (2005)  *The Sugar Masters*  {LA sugar}        
p70 Ceceil George emphasized the inadequate time accorded field hands for maternal care when she observed that most women resumed their field duties a mere nine days after giving birth, either leaving their infants with plantation nurses or rushing back to their quarters to provide occasional suckling.
p72 Birth intervals on other sugar estates further indicate that women delivered infants every twenty-five months and that a period of sixteen months elapsed between delivery and successful conception of the next baby. This phase was significantly foreshortened among mothers who lost their child in labor or soon after delivery.    ... The relatively short birth intervals for slaves in Louisiana suggest that planters followed Affleck's strictures and sought to maximize the reproductive potential of their bondswomen by limiting suckling-or else that the high rates of infant death and the destructive effect of the sugar industry impaired breast-feeding.     ... slave women in the cotton region experienced birth intervals of thirty-four <p73> months      
p73 Slaveholders valued their enslaved offspring and attempted to maximize the reproductive potential of their predominantly male estates, but they had to weigh their immediate labor requirements against lower workloads during the final trimester or during postpartum recuperation. Most sugar masters favored labor over leave, keeping their pregnant women in the fields and offering little respite from the sugar order. During the latter stages of pregnancy, women were occasionally assigned lighter duties-such as hospital work or maintenance of the slave quarters-but during the main cultivation and harvesting seasons, they did not receive a substantial reduction in their workloads until the final trimester. 
p77 Despite importing thousands of slaves a year to the sugar region, Louisiana was unique among the slave states in having a natural decrease in its population.
p78 On some plantations, over 55 percent of children died in the course of their earliest years.37  -- Ji can't find source for 55% in that note. Generally, Follett's citations seem poorly done ...

Follett 2003 J Fam Hi article refers to "distressingly high levels of infant mortality" but I can't find a number there



</p>

Dusinberre (1996) Them Dark Days: Slavery in the American Rice Swamps

Coclanis review in JAH:  To him, N A slavery, at least in the rice swamps, was econ inefficient ... but highly profitable form of capitalism marked by brutal labor exploitation and horrific slave mortality

damien Pargas (2010 U-FL book) *The Quarters and the Fields: Slave Families in the Non-Cotton South*       
Fairfax Co VA u15 mortality via Sweig -- SILLY/USELESS (ratio of adjacent pops in age groups for 'survival' rate)
p73 cites Dusineberre for rice u15 mort        
p75  Evidence suggests that the flexibility of task work afforded new mothers in Georgetown District several opportunities during the day to return to the nursery for breastfeeding as well, unlike in Fairfax County.  4 travellers note breastfeeding: "frequent visits of the mother"  "a visit ... once or twice during the day ... take to their cabins ... when they have finished their tasks -- generally in the middle of the afternoon."   "at one o'clock the babies were taken to the field to be nursed ... then they <p76> were brought back to the Negro house until their mothers finished their work"    at Chicora Wood "nursing babies ... carried to their mothers at regular intervals to be nursed"   "slave mothers allowed to begin their tasks half an hour later ... to nurse their babies in the early morning      
p78   Historian Richard Follett has argued that many sugar planters “favored labor over leave” and kept pregnant women in the fields until shortly before they gave birth, especially on newly established plantations with limited work forces.25^[Follet Sugar Masters 73-75]  
Many of the wealthier and more progressive sugar planters, however, as many of those living in St. James Parish undoubtedly were, were keen to protect enslaved women in advanced stages of pregnancy from overwork, because overexertion in the stifling and unhealthy cane fields could result in miscarriage and thus endanger a valuable potential addition to their labor force. 

Cimprich H-Net review says "The book compares the chattels' domestic situation in three counties, illustrating diversified farming in northern Virginia (Fairfax County), rice-growing in South Carolina (Georgetown County), and sugar-raising in Louisiana (St. James Parish)."

Ji: goofy attempt to see 3 noncotton counties: Fairfax VA -- tiny odd county in far north of VA, 3,116 slave are just 26% of population there in 1860; while in 1820 41% of pop (Sweig 1982 p104)

cites Sweig PhD thesis for mortality rates, but that thesis does not offer credible estimates -- simply referring to a transcription of the Fairfax Co 1820 census???


brenda Stevenson (1996 book on Loudon Co VA, N Piedmont)  **silly on IMR**
p150   some scholars liberally estimate that the mortality for white youngsters under the age of ten was 40% n28p369 donald Sweig 61% u16 mortality for white children (1982 PhD on N Va Slavery )  SILLY! Sweig takes pop14to26/u14pop as measure of survival ...
p249  attributes 50% IMR for Sou slaves to Steckel  via  n57 from michael Johnson NYReviewBooks article about slavery  



Malone (1992 UNC) *Sweet Chariot: Slave Family & Household Structure in 19th C La* -- "shockingly high" IM -- not sourced nor specified 

p178 typically? 34 month birth interval (but often 24?)

p231 Infant mortality was shockingly high, even more so among slaves than whites. Because of the dangers and because reproduction greatly benefited owners, women were usually given better than usual care during pregnancy, birth, and nursing. There are notable exceptions. One former slave recalled that when an overseer wanted to whip a pregnant woman, “he had a hold dug ... an’ made her lay acrost it an’ her ban’s and foots were tied so she had to submit quiet like to the heatin’ . Nineteenth-century planters claimed that this common practice of burying the belly of a pregnant slave in the ground to protect the fetus while she was lashed originated with the French colo¬ nists.89  ...  Despite the hazards, slaves looked forward to having children and viewed them with as a source of pride and pleasure. Charges of parental indifference, neglect, abuse, and even infanticide ...  91

p232 mean age at first birth 19 to 20 yrs, on 16 plantations








<a name="FAMsect"></a>

### Slave Mothers, Family; Gender



<p> Hilde (2020) *Slavery, Fatherhood, and Paternal Duty in African American Communities over the Long Nineteenth Century*. [Buckner review](https://networks.h-net.org/node/4113/reviews/7222405/buckner-hilde-slavery-fatherhood-and-paternal-duty-african-american)  

Probably not useful for SSMM -- IMR via secondary sources (including Steckel). Via review, my sense is it leans towards slaves creating meaning versus slaves being crushed.

Intro    p2 To varying degrees, slaveholders materially “provided” for their dependents by usurping that patriarchal privilege from black men.^4 FN: Wilma Dunaway argues that Mountain South masters had an incentive to inadequately feed and clothe their slaves, leading to higher levels of malnutrition and mortality than in the Lower South. Dunaway, African-American Family, 86–97, 100–113, 273, 282; Fogel and Engerman, Time on the Cross, 5, 109–126.    

n40p296 ...    In his study of three rice-growing plantations in South Carolina and Georgia, William Dusinberre notes of Gowrie plantation, “child mortality devastated these families, so that the most common nuclear grouping was a husband and wife with no surviving children.” Dusinberre, Them Dark Days, 84.    

If the market and mobility frequently separated children from their par-ents, so too did high mortality caused by strenuous labor, physical punish-ment, and malnourishment.24p305n24 Compared to the general slave population, Dunaway finds that slaves in the Mountain South were 1.4 times more likely to die due to inadequate provisioning of food and clothing, malnutrition, overcrowded housing, poor sanitation, and occupational hazards. Dunaway, African-American Family, 85–113, 273.

n54p307 re: attachment White pp 112-113; Schwartz Born in Bondage; more 

n56p307  ... Damian Pargas argues that centralized nurseries improved childcare and that being related to some of the children enabled caretakers to fulfill their obligations to kin. Pargas, Quarters and the Fields, 74, 75, 81–83

n60 Rawick, AS, supp., ser. 1, Indiana and Ohio, 5:212. Poor nutrition leading to low birth weights as well as illness and child death placed a heavy emotional burden on enslaved parents. King, Stolen Childhood, 12; Dunaway, African-American Family, 141, 273; Steckel, “A Peculiar Population,” 728–737; Kiple and Kiple, “Slave Child Mortality,” 284–309. High infant mortality, twice that of white women, resulted from hard labor, malnutrition, disease, attenuated breastfeeding, and seasonal patterns of conception and childbearing. Steckel, “Women, Work, and Health under Plantation Slavery in the United States,” 55–56; Cody, “Cycles of Work and Childbearing,” 61–78; King, “Suffer with Them Till Death,” 149–150.


<p>
2018 Slavery & Abolition issue titled [Mothering Slaves: Motherhood, Childlessness and the Care of Children in Atlantic Slave Societies](https://www.tandfonline.com/doi/full/10.1080/0144039X.2017.1316959)  vvb

sasha Turner -- jamaica -- "The nameless and the forgotten: maternal grief, sacred protection, and the archive of slavery."     
That more than one-half of enslaved newborns perished within days of their birth, and another one-quarter died before they reached aged two, also shaped the emotional quality of enslaved parents’ lives  CITES Higman, 

Jones-Rogers ‘[S]he could … spare one ample breast for the profit of her owner’: white mothers and enslaved wet nurses’ invisible labor in American slave markets .
 ABS ... argues that white mothers’ desires and demands for enslaved wet nurses transformed bondwomen’s ability to suckle into a largely invisible, yet skilled form of labor, and created a niche sector of the slave market. In these ways, white mothers were crucial to the commodification of enslaved women’s reproductive bodies, their breast milk, and the nutritive and maternal care they provided to white children.


2018 Women's History Review titled [Mothering Slaves: Motherhood, Childlessness and the Care of Children in Atlantic Slave Societies](https://www.tandfonline.com/doi/full/10.1080/09612025.2017.1336849)

West & Shearer 2018 WoHiRev  -- sense of non-Baptiste;     
Starts with light-work assignments of pregnant women  ; p2 cites Berlin for high mortality in colonial period;  Enslaved women’s mothering hence took multiple forms and allows for a broader and more flexible conceptualization of motherhood   p3 enslaved women sought to wrench a degree of control over their lives by prioritizing their children above all others and seeking to control their fertility in the face of slaveholder exploitation. p4 . Little is known about those who remained childless through infertility though because surviving evidence makes it hard to differentiate between women who were deliberately childless and those who were unable to bear children  p10 Wet-nursing represented the ultimate exploitation of enslaved motherhood and often deprived women’s enslaved infants of their own mother’s milk in order to prioritize the families of their white owners.

Knight (2018 WoHiR) "Mistresses, motherhood, and maternal exploitation in the Antebellum South" -- tends to trash slaveholding women (not cross-race sisterhood); derivative.
Understanding motherhood as firmly in the female ambit, mistresses’ interventions into their slaves’ mothering expressed their economic interests, served to affirm the respective social roles of mistress and slave, and formed a site through which they could exert their control and authority
p995    While all women suffered maternal and infant health risks, the conditions of motherhood have been mistakenly similarised.45

Though enslaved mothers were likely to bear similar numbers of infants to white women they suffered much higher rates of still-births and infant mortality.4  fn Dunaway, Stevenson, Bleser ed.; Schwartz p104 WRONG.




Fett 2002 


marie jenkins Schwartz (2000 Harvard) *Born in Bondage: Growing Up Enslaved in the AB South"    
**seems unauthoritative** secondary sources combined in an uninteresting fashion**

p22  ...  Slaves found it difficult to persuade planters, as well as overseers, to release pregnant women from arduous chores. No planter could assume a happy outcome from pregnancy. A high infant mortality rate among slaves, combined with miscarriages and stillbirths, ... Only a foolish owner forfeited a woman's labor or assumed any extra expense associated with pregnancy before the pregenancy seemed likely to be carried to term; consequently, slaveholders withheld special accommodations for pregnant women until late in the gestation period. Even then, owners with good intentions might be dissuaded from excusing women from field work if market prices for staple crops soared, tempting them to push slaves toward greater levels of productivity in order to gain short-term profits. Rice planters ... proved particularly vulnerable to the lure of large profits^[vulnerable b/c of the geography of rice?], and they taxed the physical endurance of mother and child to such an extent that slaves growing rice experienced higher rates of mortality than those producing tobacco and cotton ... never reached catastrophic levels / sugar"   n6p219-20  Fogel 1989 pp 127-128; Steckel, "Slave Mortality: Analysis of Evidence from Plantation Records," in WCC: Conditions, TP V2, 407,410; Dusinberre, 410-416 & n82; Berlin&Morgan (1993) C&C, p21.      

p49 {lots of drivel, incl that slaveholders "recognized that infants had to survive if southern society were to continue."  ... 
    
     Tempering the owners’ willingness to designate time for infant care was their knowledge that many babies would not survive to adulthood, and those who did would require years of economic support before they began to pay a return on any investment in their care.^[OUCH: it would not take too many years before the child could be sold] support. Slave-holders knew they could not turn their backs on slave infants, however. Cruelty toward slaves’ sons and daughters, nieces and nephews—or any helpless infant for that matter—would alienate the work force and destroy any semblance of cooperation between owners and slaves. Consequently, most owners conceded the needs of infants but exercised caution in allocat-ing plantation resources for their benefit.

     Slave parents did not allow the economics of child rearing to restrain their desire to care for children. They knew that not all infants survived childhood, but they did not believe this fact should diminish the emotional   and material support of the adults responsible for them. 

The majority of {p50} slaves throughout the South eventually procured housing and HH furnsihings for growing families, even if their owners did not allocate them following the mother’s first birth.  ... the majority of slave children while young lived in homes with two
parents.2 {FN to Gutman book OUCH}
   


p56-57 after giving birth


60-64 (Schneider uses for breastfeeding claims)   notes 26-37: Rawick-Narratives; DeBow; Southern Planter; South Cultivator ... some archival papers; 
65-69 also on breastfeeding etc notes 38-48 -- why doesn't Scheider cite?    
p67 {recommendations on breastfeeding}           
p68    Owners encouraged or acknowledged prolonged breastfeeding by denying infants under age two the weekly food rations they distributed to other members of slave families.{IS there any evidence to substantiate this claim -- "denying" infant the rations?? AARGH}  ... p69 n48 for the paragraph. But n48 is Klein & Engerman on comparative lactation US vs Carib




p104 is cited for IMR and/or births by race by Knight 2018 WHR. Wrong.      



Gaspar & Hine (1996) *More than Chattel: Black Women and Slavery in the Americas*       


Bush barbara, "Hard Labor: Women, Childbirth, and Resistance in British Caribbean Slave Societies," 193–217.


Bush (1990), Slave Women in Caribbean Society, 1650–1838. Bloomington: Indiana University Press, 1990.  {Somewhat useful for contemporary comment; mostly medical/imr via secondary Kiple, Higman, Dunn, Sheridam}

p39-40 Before 1807 there is no indication that fertility increased the worth of women -- women of similar ages, with or without children, generally cost the {40} same. After the abolition of the slave trade, and able-bodied field slave cost approximately L 180 sterling and Stewart noted that a female slave with a healthy infant was 'at least 20% more valuable than she was before it was born.' n8^[]  The decline in slave numbers after 1807 encouraged a much greater interest in the childbearing potentialities of women slaves, in addition to raising the value of infant slaves to a fifth of a healthy adult {not quite correct -- childbearing potential increases woman's value so the 20% overstates the value of the infant}       
 
p87  early West Indian commentators / Ligon / Sloane / were more favorable in their comments on slave marriages and morality than were later 18C writers.    ...  preindustrial Europe  / Phillipe Ariès / before the 17C in Europe, 'family' implied a far looser and flexible institution than it does today. The wider kinhip unit predominated over the conjugal marriage unit and communities were cohered by non-family age-group structures as in many West African societies.  ... little personal privacy was expected or attainable and hence the concept of modesty and the code of sexual morals differed considerably from those which prevailed in later industrial societies (Ariès 1962).        
... 'Mothering' in the modern sense of the word did not exist, for women had vital work to do in the house and fields and could not devote all their time to their children. {*ever so*?} The high infant mortality rate {88-89 illustrations; p90} resulted in a certain degree of 'indifference to a too-fragile childhood' .    ... concept of childhood as a special phase in the life of the individual did not exist before the cultural, demographic and economic changes which resulted from industrialisation in the 19C.     
p122   low fertility is now generally recognized as the prime reason W I slave pops did not naturally reproduce themselves.    ... To a minor degree, the adverse effects of African childbearing habits, such as the late weaning of infants, were also cited as influential in determining the childbearing potential of female slaves. {BUT late weaning reduces IMR?}     
p126 {African taboo on sex for 2yrs after birth} Genovese (1974) and Gutman (1976) both cite evidence of prolonged nursing among nineteenth-century slave mothers in the American Old South where a healthy rate of natural increase existed. {PAGES FOR Geno & Gutm?}     
p127 ... As modern West African fertility rates remain very high despite long periods of breast feeding, restrictions on intercourse, high foetal and infant mortality and early sterility of women, Kiple (1984) argues we must seek other reasons.  For him these are located in the high infant mortality and diet and disease patterns of Caribbean slavery, whilst Richard Dunn (1977), who also rejects the long suckling explanations, argues that ‘eccentric’ birth intervals are better explained by sexual abstinence, miscarriages and abortions, which suggests a more active role for slaves in determining fertility.   ...     
Contemporary observers noted that women whose tasks were lightest had more and healthier children than their less fortunate sisters.     
p131  Dunn (1977) / infant mortality rate was roughly equal for both plantations   {Jamaica & Virginia}
p132 Karasch (1987) 19C Rio  dietary defiencies affected the ability of slave women to bear and raise healthy children.     
p134  Dr Jonathan Troup noted that fewer black women died in childbirth than white women but slave infant mortality was much higher.9    
p143  In the first nine days of life infants were particularly vulnerable and, according to Higman, contemporary estimates placed the mortality rate within this period at between 25 and 50 per cent of all live births (Higman, 1984)    ... tetanus ...      
p146 n his biological history of the Caribbean, Kenneth Kiple (1984) places considerable emphasis on the link between nutrition and disease. Rates of death from infant tetanus, he argues, were fairly uniform in the nineteenth century, comprising betwen 5 and 10 per cent of infant deaths, but many alleged deaths were not neonatal tetanus. He suggests that slave doctors may have confused neonatal tetanus with tetany, a condition derived from maternal tetany (the deficiency of calcium and other vital minerals during pregnancy). This condition results in hypocalcaemic or hypomagnesaemic convulsions in infants. The symptoms of tetany and neonatal tetanus are thus identical but the former was medically unknown even in the latter half of the nineteenth century. Kiple attributes the high rate of tetany to the neglect of the diet of slave women, which resulted in calcium levels falling with each pregnancy. He thus explains the decline in infant deaths towards the end of slavery to better nutrition. However, there are flaws in this argument. Tetany is linked to vitamin D deficiency and this is less common in climates with ample sunshine. It is also generally not associated with mothers who breast feed.     

The key to a fuller understanding of the crucial variables of infant mortality on slave plantations lies, perhaps, in the symbolic nature of the first nine days of an infant’s life in both African and Afro-Caribbean folk lore, a factor which contemporary observers were either ignorant of or chose to disregard, although they frequently alluded to this period as a significant feature of tetanus in infants. When ‘Monk’ Lewis discussed the problems of caring for slave infants with his slave midwife, she fatalistically replied, ‘Oh Massa, ’til nine days over, we no hope for them.’ Thus many planters believed that if more care were given to infants during this period, far fewer would be lost.      
In West Africa a new-born infant is not regarded as part of this world until eight or nine days have passed, during which period it may be ritually neglected. The infant is regarded as no more than a ‘wandering ghost’, a capricious visitor from the underworld. Amongst the Akan of Ghana, for instance, a child remains within the spirit world until this period is over and it becomes a human being, recognised by its father. The hair of the infant is known as ‘ghost hair’, the infant’s excreta as ‘ghost’s excreta’ and the cooing of infants as ‘the language of ghosts’ (Rattray, 1927). If a child dies before this time it is considered never to have existed, which may explain the under-reporting of infant deaths. Similar traditions are found amongst the Ga people (Cutrufelli, 1983). The durability of West African practices relating to childbirth has already been observed and it may be argued that the nine-day period when slave midwives reputedly held ‘no hope’ for infants may have reflected the endurance of African beliefs rather than {p147} deliberate neglect and fatalism b/c of the high risk of tetanus, as Orlando Patterson (1969) suggests.
p147 ... As yet, few scholars have seriously contemplated the possible relationship between the high neonatal mortality rate of slave populations and infanticide, although the latter has been practised, for a variety of reasons, in many diverse societies from ‘time immemorial’ (Langer, 1974). A number of strong motives for infanticide existed in slave society and slave women would almost certainly have known of suitable methods to use, as they did in the case of abortion and contraception.      
p148  ... According to Sheridan, there was a decline in infant deaths from tetanus by 1830 and this cannot be explained solely by better conditions, as planters and doctors tended to be disappointed by their efforts to cut infant mortality rates. {ouch -- planter/Dr vs mothers/women}. It may be explained more satisfactorily by the creolisation of the population and greater impact of Christian beliefs which diluted the mystical justification of the nine-day period.     
p149  ... Among non-Christian peoples in particular infanticide has always been an accepted procedure for the disposal, not only of the deformed or sickly, but of all such new-borns that might strain the resources of the individual family or larger community (Langer, 1974). In this context the practice of infanticide as a reason for the excessively high mortality rate in the first two weeks of life has plausibility.      
The controversy 


JonesJaq (1985) *Labor of Love*   -- see revision 2010

Kiple (1984/2002), The Caribbean Slave: A Biological History. Check also K&King 1981/2002 Bk, K&K 1980 JIH

Campbell (1984 JIH)    
GA plantations of Kollock george j.  
p795 1837-61 24 yrs; 82 slaves "born", 29 die as infants; 29/82 is 353 per 1000
p799 of 82, 9 births excluded (mother unknown or house servant or DOB unknown); of the 73 pregnancies, 51 with complete records; 181 of 219 trimesters had complete records.
p800 Table 1  51 complete-record pregnancies: 33 infant survives, 18 infant dies

p801 1837-4 die/live 31/27  1849-61 32/91 total 63/118   181 completed trimesters  

p812 n28 5 of the 29 deaths had a specific cause cited -- lockjaw




### abolitionists/ism  

Alice Tyler (1944 book)  odd anti-abolitionist in various ways; useful for giving 1940s view of main figures



Walker's Appeal (1829?)

Liberator (1831-1865)  Garrison   One? issue at Smithsonian, from [1856](https://transcription.si.edu/view/10302/NMAAHC-2016_166_41_9_001)

Anti-Slavery Society (1833-1840? via Tyler p493):  one each week, *Human Rights*, *Anti-Slavery Record*, *Emancipator*, *Slave's Friend*.   
Ohio: Weld,



Lydia Maria Child (1833 tract) *An Appeal in Favor of That Class of Americans Called Africans*   a tract that added to the usual
description of the horrors of slavery a moving appeal for education and decent treatment for free blacks. It is interesting as one of the
earliest protests against race prejudice (Tyler 494)    

Theodore Weld (1839) *Slavery as It Is*  compiled largely from Southern newspapers. It contained numerous examples of the cruelty and physical hardships suffered by slaves. (Tyler 495)

William Jay (18??)  *Slavery in America, an Inquiry*

p499 The year 1836 marked the height of the success that came from this linking of abolition with the Great Revival. In the next year there was a decline.

The crisis in this dissension and disintegration came in 1839-40 when the Garrisonian radicals determined to capture control of the national organization and use it for their own ends.


Stowe *Uncle Tom's Cabin*

Helper *The Impending Crisis*


<a name="TRAVsect"></a>  

### Travellers' Accounts & other Contemporaries

Olmstead (1861) *Journey in the Seabord Slave States*     

p418 The negroes do not enjoy as good health on rice plantations as elsewhere; and the greater difficulty with which their lives are preserved, through infancy especially, shows that the subtle poison on the miasma is not innocuous to them: but Mr X. boasts a steady increase in his negro stock of five per {419} cent. per annum, which is better than is averaged on the plantations of the interior.



Jenkins 1842 "Experience, Labours, and Suff erings of James Jenkins of the South Carolina Conference" Methodist (pre1844 split over slavery) {found via Stuckey 2013/1988; searches infant/burial/death/nurs}
p7 I seemed to be the butt for the whole family, even the negroes.     
p34  Chapter VI .... Various Incidents Returning home -- Effects of the slave question at the South      
p40 {in Manchester ?} He then forbid my giving the sacrament to the negroes. 
p84{1837}My object in moving was to acquire a subsistence by some other business than farming, for which my increasing blindness almost entirely disqualified me; besides, some of my neighbors (or the negroes of my neighbors) were often doing me private injuries, such as killing my stock, burning my rails, &c.



<a name="HEALTHsect"></a>  

### Slave Health / Medicine


Bankole (1998 Garland) *Slavery and Medicine: Enslavement and Medical Practices in Antebellum Louisiana*

Kiple & Kiple (1977 J Soc Hi)




### BIO lit exploring legacies of slavery

Jasienska (2008 AMJHiBio) ["Low birth weight of contemporary African Americans: An intergenerational effect of slavery?"](https://doi.org/10.1002/ajhb.20824)



[back to top](#TOC)
