---
title: "SSMM-data: Data Sources for the SSMM/SR1 Project "
author: "jri, with jrm"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
  
<a name="TOC"></a>

## Overview ##
<p>[US data](#USA), [Canada's sources](#CAN), [India Census](#IndiaCensus);  [Life Tables](#LifeTable),  </p>

[Australasia](#AUSNZ)   [South Africa](#SouAfr)    [Italy](#ITALY)

UN [pop by age/sex](https://population.un.org/wpp/Download/Standard/Interpolated/)
UN [life tables](https://www.un.org/en/development/desa/population/publications/mortality/model-life-tables.asp)

### to organize/move ###

US Census offers biblio of recent [foreign Statistical Abstracts](https://www.census.gov/prod/2011pubs/12statab/app1c.pdf)


[Handy UN chapter on LifeTables](https://www.un.org/en/development/desa/population/publications/pdf/manuals/estimate/childmort/chap1.pdf)

Total, UN [World Population Prospects](https://population.un.org/wpp/Download/Standard/Population/)   Sou Afr total pop, u2 and u5, by sex (coloured/white not separate). 

[Bourbeau, Légaré, Émond](http://www.publications.gc.ca/Collection/Statcan/91F0015M/91F0015MIE1997003.pdf) 

McQuillan 1985 life tables for Ontario <br>

<p>MOVE THIS TO CDC DATA AREA -- Bell&Miller Life Tables, Table 6 is "Period Life Tables" and 1900 has male e0x 46.41 (p26); Table 7 is "Cohort Life Tables" and 1900 has e0x (p89) 51.52 

Richards (1909) "A Study of New England Mortality"
[Annual Reports 1898](https://books.google.ca/books?id=L2VBAQAAMAAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false)



### General Sources ###


[HMD country codes](https://www.mortality.org/cgi-bin/hmd/DataAvailability.php)


### CRVS ####

UN Demographic Yearbook [2019](https://unstats.un.org/unsd/demographic-social/products/dyb/dyb_2019/) classifies vital stats data as complete C or incomplete I  Introduction discusses classification.  But note that IMR estimate at IGME don't seem to need CRVS to be any good

Suthar et al [2019 PloS Med](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002929 ) “Evaluation of approaches to strengthen civil registration and vital statistics systems: A systematic review and synthesis of policies in 25 countries” most low- and middle-income countries still have underdeveloped systems

The World Bank. [Civil Registration and Vital Statistics for Monitoring the Sustainable Development Goals 2017.](http://documents.worldbank.org/curated/en/979321495190619598/pdf/115150-WP-CRVS-for-Monitoring-the-SDGs-web-version-May-18-2017-PUBLIC.pdf) 

[Mikkelsen, et al (2015 The Lancet)](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(15)60171-4/fulltext)
"A global assessment of civil registration and vital statistics systems: monitoring data quality and progress"


### Europe ### 

Summary view of societies, time-periods for which we have good IMR/SR data.     
Nordic countries: Denmark (1840-1970), Finland (1885-1970), Iceland (1845-1970), Norway (1890-1970) and Sweden (1751-1970)

Corsini & Viazzo (1997), [The Decline of Infant and Child Mortality](https://books.google.ca/books?id=0l3wMZBq3hgC&dq=Infant%20and%20Child%20Mortality%20in%20the%20Past&source=gbs_similarbooks)  TO LOOK OVER?


Nothing new for us in JSSL 1885 "Statistical Results of the last Census of France, Prussia, Austria, Italy, Switzerland, and Belgium," Journal of the Statistical Society of London, Vol. 48, No. 2 (Jun., 1885), pp. 288-297. No age data on Italy    
  Reporting on Toussaint Loua's paper published by Journal of the Paris Statistical Society ... LT5
  On France:  the falling off in the number of the population comprised in the age period 10-15, chiefly due in his opinion to the excessive  infantile mortality during the year 1871, and also by the abnormally large number of females returned as being between the ages of 20 and 25, which he attributes to the fact that many women, desirous  of being thought to be younger than they really are, return them-selves as under 25 

many 19-c sources listed in Galloway, Patrick R., "The golden age of published demographic data in Europe 1850-1915: sources and research possibilities", 2008. [Download](http://www.patrickrgalloway.com/galloway_2008_golden_age.pdf)  See his Table 1. Principal Official Publications of Census and Registration Data for Major European Countries to around 1905. 

Portugal Mitchell reports IMR 1970 58   1960 78     1950  94    1940     1930    1920 


<a name="ITALY"></a>

#### Italy ####

Breschi et al fn 1: 1  The bibliography on infant and child mortality in Italy is very wide. For an overview, see: Del Panta, 1997; Pozzi, 2000; 2002; Pozzi and Robles González, 1997; Manfredini and Pozzi, 2004.


##### Italy regional data #####

Various scholars trash the stillborn data (before maybe 1930s?) but they seem to see the IMR data as valid. So we are left with anomalous results ... like 1936 Campania (in southern ITA) with f/m -4% with IMR 116 (and male mortality just 9.6% greater (Ln) ). And worse, Sicilian SR5 that is -8% female ...

Regions mapped and labelled in Daniele & Malanima (2014 EcHiRes).

1881 census: have not found regional breakdowns (see below)

1901 census has regional age/sex (by birth-year), 621-;      
1911 census; vol II has age/sex by region   Presente 621 Piemonte, 622 Liguria, 623 Lombardia,  624 Veneto, 625 Emilia-Duc
632 Campania pdf638, 636 Sicilia,     
[1921 census volumes](https://ebiblio.istat.it/SebinaOpac/resource/risultati-sommari-del-censimento-della-popolazione-eseguito-il-1-dicembre-1921/IST0010376?locale=eng&tabDoc=tabcontiene)   

This [1936 census volume](https://ebiblio.istat.it/digibib/Censimenti%20popolazione/censpop1936/IST0005813vol3RegnoParte2_Tavole/IST0005813_vol3_Regno_Parte_2_Tavole+OCR_ottimizzato.pdf) has age/sex by region -- pdf134 126 Piemonte, 127 Liguria, 128 Lombardia,

[129 Venezia Tridentina, 130 Veneto, 131 Venezia Giulia e Zara (80k)  Veneto IMR 80; Greater area 86.6]
Veneto SR5 104.0  

132 Emilia (Bologna), 135 Umbria, 136 Lazio, next are SOUTH (I deem) 137 Abruzz Mol, 138 Campania 

  Wikip has The Triveneto or Tre Venezie ... a historical region of Italy ... what would become the three Italian regions of Venezia Euganea, Venezia Giulia and Venezia Tridentin     1936 has VenTrid VenezGuilia  

1936 census 129 Venezia Tridentina 62k -- becomes Trentino-Alto Adige; [130 Veneto 460k is long-term region], 131 Venezia Giulia e Zara 80k   IMR combine note that TAA is comprised of (SouTyrol aka BlozanoBozen) and (Prov di Trento) and the sum (TAA) and the 2 parts are reported
248- Trentino-Alto Adige/Südtirol imr 100, 252-53 Bolzano Bozen (So Tyrol; 1927-70) imr114  , 254- Prov di Trento (1927-70 ), 256 Veneto imr80, 260 Venezia Giulia (1924-72) imr 102;

1936 census corrections -- look for those in Table XII:  pdf 3 p98 col 2 line 72 instead of 97133 read 47133  pdf 4 none;



1951 census   10 Piemonte, 12 Lombardia, 13 Trentino-Alto Adige, 14 Veneto, 15 Friuli-Venezia Giulia, 17 Liguria, 18 Emilia-Romagna, 19 Toscana,  20 Umbria (70K), 21 Marche            
1951 tiny places 11 Valle d'Aosta (tiny); 16 Trieste, <16K, capital city of Friuli-V G;
1961 census  121 Piemonte 122 Valle d'Aosta, Liguria (99k), Lombardia, Trentino-Alto Adige (69k), 126 Veneto, 127 Friuli (74k), 128 Emil-Rom (238k), 129 March (97k), 130 Toscana (205k), 131 Umbria (53k), 132 Lazio (336k), 133 Campania (510k),  134 Avruzzi e Molise,  135 Puglia, 136 Basilicata (69k), 137 Calabria, Sicilia, Sardegna 
1971 census  [volV](https://ebiblio.istat.it/digibib/Censimenti%20popolazione/censpop1971/Volumi/RER0044590CP1971_VOL_V_Sesso_eta_stato_civile+OCRottimizz.pdf)  pdf246p240 Trentino-Alto Adige,  p234 Piemonte, p236 Valle d'Aosta, 238 Lombardia, 240 Tentino-Alto Ad, 242 Veneto, 264 Liguria, 248 Emil-Rom, 250 Toscana, 252 Umbria, 254 Marche, 256 Lazio SOUTH:   258 Abruzzi, 260 Molise, 262 Campania   p264 Puglia pdf270,  

1971 The sums of "Regione" u5 populations end up much below the "Stato" total value. 428,136 boys short -- about 19% --  ? Rome? other cities?      
p692- Tav 4 Pop resident & present of the capital municipalities by sex and age    
p786- Tav 5 Pop residente per sesso, anno di nascita e stato civile A) Stato  796- B) Regione     
  
1971 add Abruzzi and Molise to pair with Abruzzi IMR  
 
 

Regional IMR from IStat 1975 [Tendenze evolutive della mortalità infantile](https://ebiblio.istat.it/SebinaOpac/resource/tendenze-evolutive-della-mortalita-infantile-in-italia/IST0002260?locale=eng)     
238-43 Piemonte, 242-45 Valle d'Aosta (1943-70), 244-49 Lombardia, 248- Trentino-Alto Adige/Südtirol, 252-53 Bolzano Bozen (So Tyrol; 1927-70), 254- Prov di Trento (1927-70), 256 Veneto, 260 Venezi-Guilia Zara  262 Friuli-Venezia Giulia (1924-72),  262 Liguria, 268 Emilia-Romagno, 272 Toscana, 278 Umbria, 282 Marche, 288 Lazio,     
SOUTH p292 Abruzzi e Molise p298 Campania p302 Puglia p308 Basilicata p312 Calabria p318 Sicilia p322 Sardegna p328 ITALIA

IMR by region 1990-2013 online at Istat, ranges from 3.9 to 10.4 -- so those data are too late for us.

Regional stillbirths data from Istat (1965), [Sviluppo della popolazione italiana dal 1861 al 1961](https://ebiblio.istat.it/SebinaOpac/resource/sviluppo-della-popolazione-italiana-dal-1861-al-1961/IST0002072?locale=eng), Annali di Statistica, s. 8, vol. 17.    E.g. p722 Umbria p726 Lazio p730 Campania p734 Abruzzi e Molise  p738 Puglia  p742 Basilicata p746 Calabria  p750 Sicilia p754 Sardegna

Deadends:       
1881 IST400060cp1881sullaclassificazionexeta      


It is tempting to use the comment about "extra caution" and data problems for Italian mortality as a basis for dropping the Italian SR:IMR set.  But the comment misleads about IMR data, which does have single year deaths (and original sources show u1month and u1year deaths, by sex).     
Jim kills a day poking around ITA 19th C data (and sources) to find that stillborns are a little lower than expected for the IMR (e.g. 30 per K livebirths while Prussia has more like 40 -- and they both have IMR around 200). But that does not seem to be a basis for challenging the Italian IMR. If we shifted infant deaths over to stillbirths to make Italy look like Prussia (raise ITA stillborns by 1/3) then 1870s avg IMR drops from 214 to 207 (1871 226 drops to 220) -- negligible.

**Regional differences in registration quality**  Pizzo & Barona quote Woods “Italy offers an excellent example of what we would expect to see in a country with improving registration coverage. National rates of late-fetal mortality only reached credible levels during the early decades of the twentieth century because regional differences in registration quality had narrowed by them. Rates in the south rose to match those in the north and then stayed at a higher level longer” (Woods, 2009, 82)."

LOOK AT BRESCHI REGIONAL IMRS and TRY TO LINK TO SR REGIONALLY ....

HMD  "ABOUT MORTALITY DATA FOR ITALY" (Last updated 2021 May 12)  Prior to 1906, deaths counts are available only by five-year age groups (i.e., 0-4, 5-9, …, 65-74, 75+), with the exception of 1883-84, when they are available for single years of age. The data for 1883-84 demonstrate clear patterns of age heaping. In 1893 and 1894, data are available only for the total number of deaths by sex (not by age group); the age distribution has been estimated (see Appendix II for details)     
p5 DATA QUALITY ISSUES     
The data prior to 1906 should be used with extra caution due to problems of quality. For most of these early years, the original death counts were available only by five-year age groups with an open age interval at age 75+ years. Thus, life tables by single years of age are based on estimates. Users are advised to use the life tables by five-year (or 10-year) age groups, which are based mostly on the original data rather than estimates.    

Sviluppo pdf 694-95 gives births and u1 deaths 1862-1960? 


[1881 & 1882 Statistica delle cause di mort](https://books.google.ca/books?id=HxtRAQAAMAAJ&printsec=frontcover&dq=Statistica+delle+cause+di+morte&hl=en&newbks=1&newbks_redir=0&sa=X&redir_esc=y#v=onepage&q=Statistica%20delle%20cause%20di%20morte&f=false)      
pdf56-65 p2 Tavola I  1881 total pop 7,000,883  IHS shows pop 28.46 million  
pdf162 Tav2   total deaths across months  197,559
NOT all of Italy

1881 age0 deaths (within first year of life)   
Istat 112,182 95,605 218,244    
HMD__ 112,218 95,620 207,838 

Movimente della popolazione seconda gli atti dello stato civile
 xx Nati   

1874 pdf009
1875 pdf067   119pLI Nascite  120 births by sex: Italy France EngW Germ Prussia Bavaria  146 stillborn 
1876 pdf237   258pxx Nascite    pdf307 Appendice

1881 pdf46 births by sex, 1863-1881; 
1892 pdf31 births by sex, 1872-1892; nati-morti pdf45 same years ; 1890,91,92 deaths sex/age
1903 pdf34 births by sex, 1882-1903; nati-morti only 1901-1903

Sviluppo 1965 pdf694 p688 has births 1862-

For Jim, bottom line question is whether the IMRs are overstated. Do stillbirth data suggest anything? The fact that the male rate is only 10% above the female is interesting -- that is consistent with the sex-ratios being not-so-female-biased. This is all about Italy's SR data being inconsistent with the IMR values; e.g. 1881 Ln(u5f/u5m) = -3.7%   and IMR > 200.  My simulator predicts -3% Can't rule out mortal misogyny, but sex ratios by age do not show a shift toward boys (as expected in case of substantial excess female mortality).

Italian [digital stats pubs](https://ebiblio.istat.it/SebinaOpac/resource/annali-di-statistica/IST0030194?locale=eng&tabDoc=taboggd) incl one referenced in tab 2.3 which has different birth counts

##### Italy as a whole #####

U5 populations are on the Istat web-site with the same values as Mitchell's IHS. HMD's data has years are advanced by 1;  seems HMD refers to start of year and Istat end of year?  IMR values are on the Istat web-site; IHS (2013) has less precise version of the same.

At least for 1901, the under-5 age group embraces some 5-year-olds, insomuch as the census reported Feb 9, 1901 populations by year of birth; probably less than 1/12 of the 1896-birthyear were age 5 at the census-date. But one wonders how precise the census-takers and respondents were when doing the census.     

SRB is somewhat male-tilted, with Ln(m/f) values usually at or above 6.0% until the second half of the 1880s; values usually in the 5.5-5.9% range into the early 20th century; values range from 4.9% to 5.4% in the years from 1908 to 1916. Interesting to see births fall more than 1/3 from 1915 to 1917 and the SRB tilt 0.9% toward boys (presumably because the decline of births was concentrated among the poorer and less-healthy women).

The Istat data are in xls tables in the dempap/wrangling/raw folder.

For SR5 [Istat](http://seriestoriche.istat.it/index.php?id=1&no_cache=1&L=1) and IHS (Mitchell) have the same numbers for 1861, 1871, 1881, 1901 (no 1891 census). HMD numbers seem the same, but years are advanced by 1.

1881 census ["Sulla classificazione per età della popolazione del Regno](https://ebiblio.istat.it/digibib/Censimenti%20popolazione/censpop1881/IST400060cp1881sullaclassificazionexeta+OCR.pdf) offers various estimates of pop by sex and age for 1881 and 1871, along with discussion. Probably using birth/death data to "equalize" populations ... 


Deaths-data are in the [Health tab](http://seriestoriche.istat.it/index.php?id=1&no_cache=1&L=1&tx_usercento_centofe%5Bcategoria%5D=34&tx_usercento_centofe%5Baction%5D=show&tx_usercento_centofe%5Bcontroller%5D=Categoria&cHash=b73e856aedfc85d2f1e27730c3822c86)  

Istat births are in Table 2.5 in the [Population  tab](http://seriestoriche.istat.it/index.php?id=1&no_cache=1&L=1&tx_usercento_centofe%5Bcategoria%5D=32&tx_usercento_centofe%5Baction%5D=show&tx_usercento_centofe%5Bcontroller%5D=Categoria&cHash=04e5a2e51acfa92f173aac082f0d8872), under the menu-heading [Resident population and demographic dynamics](http://seriestoriche.istat.it/index.php?id=1&no_cache=1&L=1&tx_usercento_centofe%5Bcategoria%5D=32&tx_usercento_centofe%5Baction%5D=show&tx_usercento_centofe%5Bcontroller%5D=Categoria&cHash=04e5a2e51acfa92f173aac082f0d8872#), "Births by vitality and legitimacy status - Present population at reference year borders - Years 1863-2014". These these births data are the same as those in Annuario statistica and HMD.     
Different birth data are in Istat Table 2.3  (demographic balance: note a     
(a) The demographic balance of the Italian population for individual years has been estimated on the basis of Censuses and demographic statistics availables. For more information: "Sviluppo della popolazione italiana dal 1861 al 1961" Annali si Statistica Serie VIII, Vol. 17, Istat 1965.)

Mitchell IHS (pdf140) shows IMR 200 or more in 1863-88 except for 5 years (192 198 186 194 193) in 1881-1887 ;  And his Table A2 (pdf47) has Italy u5 populations which give Ln(SR5) 1861 -2.0% 1871 -2.9% 1881 -3.66%  (1881 m/f of 103.7  -- 'healthy-looking'?) and 1901 104.2  1911 103.8   1921 104.4  TREATMENT OF STILLBORN IN ITALY's STATS?     
Mitchell's sources: Annali di Statistica (1871-); Annuario Statistico Italiano (1878-); Cento Anno di Svi/uppo Economico e Sociale del/' Italia ; Somma rio di Statistiche Storiche italiane, 1861-1955 

HMD has single-year by sex for 1872 forward -- source?
For the Human Mortality Database, we use data based on the presente population for years prior to 1981. Population estimates are calculated based on census counts of the presente population in order to be consistent with the vital statistics (i.e., deaths, births).    
HMD says, misleadingly, that death counts come 0-4, 5-9, ... but in fact the sources have 0, 1-4, 5-9 etc; and the 0 group is sometimes broken into 1month and 1-12months 

    Prior to 1906, deaths counts are available only by five-year age groups (i.e., 0-4, 5-9, …, 65-74, 75+), with the exception of 1883-84, when they are available for single years of age. For 1912-20 and 1937-51, the pre- and post-war census counts and deaths data for the total population (including the military) are used to derive annual (January 1st) population estimates.      

For 1912-21, 1937-51 (WWI, WWII), HMD "Italy, data sources" refers to Jdanov et al. for births & deaths, but that paper covers war-time mortality of young males.


UN volume The Aging of Populations and Its Economic and Social Implications  -- used by Mitchell IHS for Greece population by age/sex in 1861 (or so)


#### Italy's historical data sources ####

Breschi et al. Sardinia paper intro refers to Istat sources for IMR by region    

    Indeed, since 1862, official statistics (Istat, 1958 ; 1965 ; 1975) allow to calculate annual infant mortality rates (and its component : neonatal and post-neonatal), as well as stillbirth rates for the whole country and for each region.

Istat (1958), [Sommario di statistiche storiche italiane 1861-1955](https://ebiblio.istat.it/SebinaOpac/resource/sommario-di-statistiche-storiche-italiane-18611955/IST0034893?locale=eng), Roma. what for? (cited in Sardinia article). It has u5 for census years ... not by region
Istat (1965), [Sviluppo della popolazione italiana dal 1861 al 1961](https://ebiblio.istat.it/SebinaOpac/resource/sviluppo-della-popolazione-italiana-dal-1861-al-1961/IST0002072?locale=eng), Annali di Statistica, s. 8, vol. 17.   
Istat (1975), Tendenze evolutive della mortalità infantile in Italia, Annali di Statistica, s. 8, vol. 29.   

maybe also useful is Istat (1961), Dal censimento dell’unità ai censimenti del centenario. Un secolo di vita della statistica italiana 1861-1961, Roma (written by Roberto Fracassi).   

IStat 1975 has regional IMR ...  "To this purpose, a great quantity of data had to be collected and computed: in appendix, utiHzers can frnd the complete series since 1863 to 1972, at regional level, of infant mortality rates by sex, considering neo-natal and post-neo-natal mortality separately,and number of live born auci deceased children

pdf/p  275 Append 1     283p237 App 2  IMR by region

Piemonte IMRs 1896-1901  male 158-184  female 134-158   SR5 


1880 census volume just has population with geographic breakdowns (no age nor sex)

1901 census population counts are by year of birth, with 1901 Jan 1 to Feb 9 and earlier full years. Perhaps of interest, the SR of the January babies is very male (m/f 109%), and moreso than the SRB.   

1901 vol 1 Tavola 1 Popolazione dei Comuni e Frazioni di Comune     

1901 census vol 2 ([google books CA](https://books.google.ca/books?id=6JUyAQAAMAAJ))  pdf475 Indice, 
pdf 615 Tav III is population par sesso & eta for various places  132-140  141-177, 178-229, 230-267,    
A In ciascun capoluogo di provincia o avente oltre 15,000 abitanti (In each provincial capital or with over 15,000 inhabitants)      
B In ciascun circondario ed in ciascuna provincia (In each district and in each province). Pp 230-267 (706-743) pop by birth-year and sex; 268-319 (744-795) single/married by age groups    
C In ciascun compartimento e nel regno (In each compartment and in the kingdom). Pp 320-337 (796-813) ages by sex ; pdf813 is p337 with population by sex and birth-year for the kingdom as a whole (Regno).

**Redundant sources:**
 
 Statistica delle cause delle morti [1888](https://books.google.ca/books?id=2AuQ4GGhjkQC) -- does not seem to give infant deaths (nor deaths by age otherwise). 1887 also available (via other editions)

Annual stats are Annuario statistico italiano, [Vol 1](https://books.google.ca/books?id=TUoYAAAAMAAJ) is 1878.     

1897 has births by sex 1872-1895  pp38-39 pdf62-63. Birth totals match HMD and Table 2.5 of Istat (but Table 2.3 of Istat estimates larger birth counts; e.g. 1880 Istat's 989 K live births; AnnStat and HMD have 957,900 (as does Table 2.5).

 pdf67 Igiene e sanita -- sources include Statistica delle cause delle morti;  limited mortality data -- pdf68 p44  1887 828,992 total deaths -- matches HMD. HMD says age 0 deaths 1887

 HMD deaths shows 1881 age 0  95620.21 112217.85  207838.06
 



#### Switzerland (CHE) ####

Combined.RDS has 1880, 1888, 1900, 1910, 1920, 1930, 1941, 1950, 1960.  Why not 1970? Maybe IMR too low (1960 is ~23)

IMR from HSSO matches Mitchell/IHS 2013. Calc via 4yrs of data 1867-70 210.3, 4yr avg 210.2

[u5 ages](https://hsso.ch/en/1996/b/8) for censuses 1860 onward from HSSS

[deaths by age](https://hsso.ch/en/2012/c/38)   Historical Statistics of Switzerland HSSO, 2012. Tab. C.38. hsso.ch/2012/c/38  Total Deaths by Age Group 1841–1870 (Estimate of I. and H. Ritzmann)

c39 Male Deaths (Excluding Stillborn Births) by Age Group 1867–1995    
c40 Female Deaths by Age Group c40      Total Deaths by Age Group c41
c42 Deaths in First Month and First Year of Life
c43 Deaths in First Year of Life by Month
Male Deaths in First Year of Life [c44](https://hsso.ch/en/2012/c/44)
Deaths in First Year of Life by Canton 1867–1995 [c45](https://hsso.ch/en/2012/c/45)

1871-1890 in the 4 volumes of Mariages, naissances, décès en Suisse de 1871 à 1890.   
v1 marriages; v2 births; v3pt1 deaths; v3pt2 death-causes. All [full-view at Hathi](https://catalog.hathitrust.org/Record/011529302).     
births 1871-1890 [Vol 2](https://babel.hathitrust.org/cgi/pt?id=coo.31924092590847)      
p3 total births per year (copied)    
p47 La prédominance régulière des garçons est un phénomène bien connu  (106 b/f)     
Pages restart with Tables.    
Table 8 (p14) births by sex, 1871-1890     
Volumse has data on still-born (mort-nés) but not infant mortality.     
Vol 3 pt 1, deaths; Vol 3, pt 2 causes;   
V3pt1 Tables p18 deaths by sex/age

1860 census [v3](https://catalog.hathitrust.org/Record/101659639) for age/sex (5year)


1888 census [v2](https://babel.hathitrust.org/cgi/pt?id=hvd.32044106522675&view=1up&seq=59) for age/sex data  p191 1860-1888  p210 1888 


### Germany

Germany 1880-1933 with IMR/SR  ~240 100.5  (1880)  to   ~77 103.7 (1933)  
Prussia 1875  ~220 101.1

u5 populations
1871 IHS-A7-3580; 1880: Statistisches Jahrbuch 1883, p. 10; 1890: Statistisches Jahrbuch 1896, p. 5;   1900: Statistisches Jahrbuch 1903, p.6;  1910: Statistisches Jahrbuch 1919, pp. 6-7;  1925:  Statistisches Jahrbuch 1919, p. 14; 1933: Statistisches Jahrbuch 1939, p. 14.


[Statistical Yearbooks](http://www.digizeitschriften.de/dms/toc/?PID=PPN514401303) 1880-1941/42 are online from German site.      
[1903](http://www.digizeitschriften.de/dms/toc/?PID=PPN514401303_1902) has age/sex [p6](http://www.digizeitschriften.de/download/PPN514401303_1903/PPN514401303_1903___log7.pdf) has age/sex     
1893 has u10  ;   1913 no; 1914, 1915 u12; 1916,17,18 no;   1927x  1928&1929 have 1925 age/sex.     
1936 yrbk has the IHS values of u5 pop, date of 31dec1833; 1837 yrbk gives slightly smaller values, from June which is the census date. So we should use those -- the census values.

1881 no age/sex data found. These seem not to be searchable.      
1914 p497 has International Overview (of what?)     
1991 has data for 1950 forward     

Early YrBooks, full-view at Hathi, [1873 and later](https://catalog.hathitrust.org/Record/100422932)
 1873 no ages; 

Seems that all the Yearbooks are [Online at Columbia](https://clio.columbia.edu/quicksearch?q=Statistisches+Jahrbuch+f%C3%BCr+das+Deutsche+Reich&commit=Search) (Statistik des Deutschen Reichs) and those probably are Hathi and searchable. 

Later Yearbooks are online. I checked 1991 index: Säuglingssterblichkeit  74, 86, 434.
p434 causes; p74 births; deaths in first year of life;    
Gestorbene im 1 Lebensjahr 1950 1116701 67175     
Die Säuglingssterbeziffer    


**Mitchell**   2013 pdf3396 A- Population and Vital Stats

YrBks corroborate Mitchell's u5 populations for 1880 1890 1900 1910 1925 1933 (Series A2, 2013:13pdf3454, 1983:45). Seems Alsace & Lorraine included 1871-1918 (But Js assures these are small).  Series A1 Germany (pdf3408) has fn24 (pdf3437); A1 has pops for those census years. 1910 has fn25 From 1910 (2nd line) the territories ceded after the First World War are excluded 
A2 is pop by 5-yr ages.  (2013:15pdf3454);  1933n13 p45pdf3484 Excludes Saarland.
A1 is census pops (2013:10pdf3407) 1910 has two lines, n25 ()

Mitchell gives a consistent series for IMR data for 1875-1900 ("five states"), but 1900-40 (Empire & Republic) is different.    

Our spreadsheet (IMR-SR.xls) refers to 1875-1900 series as D5S (5 states) and it is to be used for SRs from 1880-1900.  The subsequent IMR series is DER (Empire & Republic) and it is to be used for the 1910 and later German data.

Mitchell reports (pdf139, 2013:pdf3577) IMR from 1836 (292), but via footnote 3 (pdf146p127) 1836-50 is Bavaria only; 1851-70 is Bavaria and Kingdom Saxony;  1871-74 + Baden, Wurttenburg; 1875-1900 + Prussia; 1901-1940 German Empire & Republic.   fn7 
1875 IMR=242 but n9 1875 say IMR without Prussia 308 (1872-1874 values listed are 301 307 297)  so Prussia pulls average IMR way down. Knodel 1974 corroborates that, with Prussia IMR 1871-75 224 1876-80 205      
Mitchell IMR p3589 n3: Bavaria, Saxony, Baden, Württemberg, and Prussia for 1875–1900; German Empire and Republic for 1901–40;     
Mitchell U5 p3454, n13 on 1925& 1933, n14 on 1939;  p3484 A2 Notes 2. For fuller footnotes on territorial changes and on the nature of these statistics see table A1 (Population of European Countries at Censuses).  Footnotes 13 Excluding Saarland. 14 1937 territory.       
Table A1 p3407 Germany footnote 24, p3408 1910 n25, 1933 n27        
n24 figures to 1864 (1st line) ... exclusive of areas ceded ... in 1860-71  / <those areas included> from 1865     
n25 from 1910 second line territories ceded after WW1 are excluded     
n27 1939 includes a small part of Austria    

The u5 counts in Mitchell match the Yearbook Vol 4. There  "Eheschliessungen, Geburten und Sterbefälle in den Jahren 1872—1881" (Marriages, births, deaths).

HMD life-tables for Germany, [1870s](https://www.lifetable.de/data/DEU/DEUFRG018711880AU1.txt) has q0m of 252.73 q0f 217.40 

Säuglingssterblichkeit 


**Prussia** and Berlin. Annual IMR 1875-1914 and u5 m & f counts for 1875, 1885, 1895, 1900, 1905, 1910. 

Our Prussian IMR match Knodel where we have overlap: 1876-80 1881-1885.

Voegele 2000 show 1886 peaks. From our source, rural/urban all  211/251  225  -- seems consistent
[1886](https://babel.hathitrust.org/cgi/pt?id=uc1.c100401527&view=1up&seq=284&size=125) 

[Patrick R. Galloway](http://www.patrickrgalloway.com/prussia.htm) Prussian data. But they are an old version of XLS file, which read_excel can't open; they need resaving in a somewhat more current version of XLS. Jim's R code to get Galloway data is in github/dreadful (home to my log, lit, sources htmls): SSMMgallow.R and SSMMgallowFix.R

annual IMR data 1875-1914 via births by sex, but u1-deaths not by sex    
These values are much above Knodel's ... 

age/sex counts 1867 u10;  in IMR-SR.xls 1871 u5; 1875 u1, 1to4; pop1885, 1890no, age1895, age1900, age1905, pop1910: u1, 1to4 (so u5); m/f ages NOT in 1890 (pop,age), pop1900, pop1905;

E.g. POP71.XLS gives us u5 pop; via his [codebook](http://www.patrickrgalloway.com/galloway_2007_prussia_codebook.pdf), I confirm the souce is the vol 30 [1871](https://babel.hathitrust.org/cgi/pt?id=uc1.c100244734&view=1up&seq=258&size=125). Hathis page #516 or so.  BIR1871.xls has births by sex, from same source (pages 24-25, 29-36)      
Die Ergebnisse der Volkszählung und Volksbeschreibung im Preussischen Staate   
The results of the census and description of the population in Prussian states

vit1875-vit1914 births and u1 deaths -- now in RDS

birm & birf  includes  birinstm/f -- those in public institutions;   
geburten births  Zahl der Geborenen number of born     
sterblichkeit  mortality   Zahl der Gestorbenen     number of dead     

via 1888 I see my birth count is live-births;

Galloway's codebook directs to [1875 Prussia Yrbk (vol 42)](https://babel.hathitrust.org/cgi/pt?id=uc1.c100244813&view=1up&seq=241&size=125)

II. Geburten/Births   Ueberhaupt/in general (overall)    in

my birth counts are good (live births only), but I need to deduct stillborns ... 

the mortality count includes stillborn     
IV. Sterbefälle (einschliesslich der Totgeborenen).     
IV. Deaths (including the stillborn).     

Galloway via [ifo institute iPEHD data](https://www.ifo.de/en/node/44166)

Prussian below is superseded by Galloway (but might be used to corroborate)

[Prussia 1877](https://books.google.ca/books?id=yXQOAAAAQAAJ)

Preussische Statistik  [xxxix 1875 ages u5](https://books.google.ca/books?id=yXQOAAAAQAAJ)
vol 39  Uebersicht IV  Geschlecht und Alter p50 u5 ages in 1875
vol xxiii 1869 Druck, temp xxiv 1870 Druck, temp     xxv 1871 Druck, temp     xxvi in and out migration einwanderung und auswanderung xxvii 1872 Druck, Temp     xxviii 1869-72 violent deaths etc xxix births, marriages, deaths [1868-72](https://babel.hathitrust.org/cgi/pt?id=uc1.c3458206&view=1up&seq=5)  Trauungen  p74 ages of couples p178 (Trauungen weddings) xxx Die Ergebnisse der Volkszählung und Volksbeschreibung 
    
[1871 census](https://babel.hathitrust.org/cgi/pt?id=uc1.c100244734&view=1up&seq=388) p24 #82     293 #352 agricultural census
 Some "balancing" data/estimates ... Jim deems these are pseudo-life-table and not a basis for pop counts.  330 (#388) u5?   columns 9 & 10, male & female.    
315 
Darn! Jim can't find age/sex counts ... this seems to be the most likely volume ...

XXXI Viehzählung  (cattle count); XXXII Klimatologie; XXXiii Druck , Temperatur , Feuchtigkeit und Niederschläge; XXXiv 1874 Druck, Temp ... ; XXXV Finanzstatistik; xxxx business census?; XXXVII weather; xxxviii accidents & suicides 1873,74,75; 

**AUT AUSTRIA**   

u5     
1869, 1910  from IHS    
1880 from Handbuch 1886, p3; 1890 from [Handbuch 1893](https://babel.hathitrust.org/cgi/pt?id=hvd.hl0lnt&view=1up&seq=5&skin=2021), p. 6; 1900 from 1903, p. 7.


Interesting [austrian biblio](https://anno.onb.ac.at/cgi-content/anno?zoom=33)    
A [wiki](Statistisches_Jahrbuch_der_Österreichischen_Monarchie) that may provide links for AUT data    
[austrian lit online](http://www.literature.at/viewer.alo?objid=785&viewmode=overview)     

In the IHS listing of sources, the only reference to 1869 is Statistisches Jahrbuch der Österreichischen Monarchie (1861–1881). Those are linked in [this wiki](https://de.wikisource.org/wiki/Statistisches_Jahrbuch_der_%C3%96sterreichischen_Monarchie#1863%E2%80%931881:_Statistisches_Jahrbuch). Looking for age/sex: not 1868-1871;   (new format starts in 1872)  1872-1880 (has 1880 census); end looking.

u5 for SR have 1880 1890 1900 from 19C AUT sources; use IHS for 1869 and 1910; 2010 YrBk and IHS have 1923 and 1931 Republic of Austria    


IMR 1876-1907 u1 deaths from StHb1909; 1875-1907 births from YrBks 1886, 1893, StHb1907, 1909.
IHS "From 1914 the statistics apply to the present Republic, except that Burgenland is not included until 1922 -- so how big is Burgenland? 1923 286K in pop of 6535K  or 4% -- I deem NEGLIGIBLE for us

From Google Doc:  we have data for IMR by sex for 1875-1907; total IMR (Mitchell/IHS) 1908 onward. M & F u5 pops for 1880, 1890, 1900 from contemporary sources; use Mitchell for 1910 u5 pops (total matches OK with 1910 census as reported in 1913 Statistische Monatschrift.  Austria’s stats bureau has u5 pops for only a very small subset, smaller than offered by the Jahrbooks of circa 1900/1910).   
HMD’s ”Austria” is very small compared to 19C Austrian sources. 
Yearbook 1886 p3. has 1880 u5 pops 1449168 1465661, matches IHS/Mitchell (2013:pdf3440) has 1449 1466. The corresponding SR-values are 98.87 and 98.84 (so IHS rounds to .1 lower).
Page 5 has infants deaths, m & f, <1month, 1-12mos. HMD says “In general, the degree of completeness is high enough to classify Austrian birth statistics as being of high quality”.
HMD’s birth count for 1880s are only about ⅕ of Austria’s YrBk for 1886. From MItchell/IHS it seems YrBk does not include Salzburg.

Modern/small Austria's [u5 pops at censuses from 1869](file:///home/jim/Downloads/population_stat.yearbook.pdf)
found at http://www.statistik.at/web_en/nomenu/searchresults/index.html [Population (Stat.Yearbook](http://www.statistik.at/wcm/idc/idcplg?IdcService=GET_PDF_FILE&RevisionSelectionMethod=LatestReleased&dDocName=042776)  But that is a very small version of Austria

[1868](https://www.google.com/books/edition/Statistisches_Jahrbuch_f%C3%BCr_das_Jahr/lz5YAAAAYAAJ) p20 for infant deaths     
[1873](https://www.google.com/books/edition/_/h0NYAAAAYAAJ?gbpv=1)  p44 infant deaths? 
p50 Kindersterblichkeit (infant mortality) von der Geburt bis mit 5 Jahren  (birth to 5 yrs) by month of year

Bewegung der Bevölkerung, mouvement de la population, volume annuel depuis 1881.

Statistisches Jahrbuch der österreichischen Monarchie, Annuaire statistique : 1863-68 (1 vol.); 1869-70  (1 vol.); volume annuel de 1871 à 1881.
Osterreichisches statistisches Handbuch, volume annuel depuis 1881.

[Stats Jahrbuch 1861 to 1881](https://catalog.hathitrust.org/Record/000678775) Hathi-UMich

[various Jahrbuch at Google](https://www.google.com/books/edition/_/h0NYAAAAYAAJ?gbpv=0) 

[1870](https://www.google.com/books/edition/_/L0FYAAAAYAAJ?gbpv=1)   p20  weddings according to age 
[1877](https://www.google.com/books/edition/_/WkVYAAAAYAAJ?gbpv=1) GoogleBooks lists as 1880, the publication year.
[1878 at Hathi](https://babel.hathitrust.org/cgi/pt?id=mdp.39015033611834&view=1up&seq=53) not on Google
[1879](https://www.google.com/books/edition/_/IUZYAAAAYAAJ?gbpv=1)  p44 Kindersterblichkeit 
[1881](https://www.google.com/books/edition/_/nElYAAAAYAAJ?gbpv=1)  Stats Jahrbuch does not seem to have the births and deaths for previous years, which we find in later volumes (Ji looking for 1876-79 )
[1882](https://www.google.com/books/edition/_/nElYAAAAYAAJ?gbpv=1)
[1886](https://books.google.com/books?id=D0sS25Ei5KsC) has 1880 u5 pops (p3) and u5 mortality by sex   [1893](https://babel.hathitrust.org/cgi/pt?id=chi.12960051) p24 has births and u1 deaths 1882-1893.      [19xx](https://babel.hathitrust.org/cgi/pt?id=chi.101238827&view=1up&seq=22&size=125) for 1895-1906

 Statistisches Jahrbuch 
 Österreichisches statistisches Handbuch Hathi 1895-10 9(got) got 1895-1909  OSH

[OSH 1893 1899 1901](https://catalog.hathitrust.org/Record/100466360) via Hathi-Harvard

[OSH 1895-1909](https://catalog.hathitrust.org/Record/012306732) via Hathi-NYPL

[1904](https://www.google.com/books/edition/_/bs1CAQAAIAAJ?hl=en&sa=X&ved=2ahUKEwj9p4zO_8zxAhUTQ80KHZ9QDCgQ7_IDMAB6BAgDEDQ) check for leads / other editions to bridge 1907 to 1914 and to look for u5 populations ...

[1909 Os st Hb](https://babel.hathitrust.org/cgi/pt?id=nyp.33433090775069&view=1up&seq=42&q1=alter) 

p2 Zivilbevölkerung civil population 1818-1900    
p7 Altersgliederung nach einzelnen Altersjahren und dem Geschlechte  1900  agebreakdown by sex (lists birth year and m f pops)     
p28 1907 infant deaths (#42 p28)  p40-    has 1895-1906     
a) Ohne Berücksichtigung der Legitimität  -- w/o taking legitimacy into account     
p41 b) taking legit into account
 Ehelich Geborene  born in wedlock; Unehelich Geborene illegitimate births

 1911-1919 GoogBks no preview Österreichische Statistik

1920 onward is 	Statistisches Jahrbuch für die Republik Österreich   SJB
[1921](https://babel.hathitrust.org/cgi/pt?id=uiug.30112054454993&view=1up&seq=10) has 1914-1921

1923&1924 doesn't have age/sex

Monthly data in [Statistische monatschrift](https://clio.columbia.edu/catalog/ht009025775) are not likely of use (Jim had a quick look)


[**Sweden**](https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__BE__BE0101__BE0101I/LevandeFodda/) IMR (1751-2020) and births (1749-2020). HMD for population counts 1749 forward; Statistics Sweden seems to have the same data for 1860 forward (at least the 1866 values are the same (random choice)).


### Norway ###

Thinking we'll want to estimate Norway's IMR 1845, 1855, 1865, 1875 based on the SR values and Nordic IMR:SR relationship of 19th C ...


Listing of Statistics Norway historical publications by subject [1828-1876 & 1977-96](https://www.ssb.no/a/english/histstat/publications/)

<H4>Norway U5 Populations</H4>     
The data are found in HMD Norway (where years refer to year-beginning). Our years are year-end, to line up with IMR.     
1845-1900 values are in [Norges folkemængde fordelt paa de enkelte aldersaar 1846-1901 (Population de droit](https://www.ssb.no/a/histstat/nos/nos_v_113.pdf), pp. 32, 34 (pdf 47, 49). Same values are in HMD.

1910 census
1920 census 
1930 [Folketellingen i Norge 1 desember 1930. Femte hefte](https://www.ssb.no/a/histstat/nos/nos_ix_024.pdf), p2; also Historisk statistikk 1978, p. 35 and online table 3-3.
1946 [Folketellingen i Norge 3. Desember 1946, Tredje hefte](https://www.ssb.no/a/histstat/nos/nos_xi_041.pdf), p. 2 (Recensement de la population le 3 décembre 1946, III). 
1950 [Folketellingen 1, Desember 1950 Annet hefte, Folkemengden etter kjønn, alder og ekteskapelig stilling](https://www.ssb.no/a/histstat/nos/nos_xi_146.pdf), p. 2 (Population Census December 1, 1950, Second Volume, p. 2). 
1960  [Population Census Volume II](https://www.ssb.no/a/histstat/nos/nos_xii_117.pdf), p 8. Also Historisk statistikk 1978, p35.
1970  [1970 census](https://www.ssb.no/a/histstat/nos/nos_a448.pdf) (Folkemengden etter alder og ekteskapelig status 31 Desember 1971) also Statistics Norway, Historiskonline table 3-3, ["3.3 Resident population, by sex, marital status and age"](https://www.ssb.no/a/histstat/tabeller/3-3-en.html); 31 Dec 1970.


1930 census, not volume 1; 

Details     
1845 (Jan 1 1846) HMD, which has same values as in Norges folkemængde; corroborated with reference to census u7 values found in Hist-Stat 1948.     
[1855 census](https://www.ssb.no/a/histstat/nos/st_16r_1846-55.pdf) ; p viii (pdf 9) for 5yr age groups. Also p30 (table No. 4 seems to have geographic detail) <br>
1865 (jan 1 1866)  Census, same values as in HMD and in Norges folkemængde
[Resultaterne af Folketællingen i Norge 1 Januar 1876](https://www.ssb.no/a/histstat/nos/nos_i_c1_i_1876.pdf)    slightly different age/sex counts for u5
p97 Tilstedeværende Folkemængde -- population present;    p134 Hjemmehørende Folkemængde  NATIVE population
1876 (Jan 1) Census, resident population (negligible difference from population present); it is the HMD value of 1876.  
[1886 census](https://www.ssb.no/a/histstat/nos/nos_iii_053.pdf) shows u15 by sex. pdf p22

1890/91 Census Pop  Tilstedev / de fait .... Present in 1893 YrBk; But we use "resident" pop as reported in HMD and Norges folkemængde (resident / present about the same SR).  oecd: de droit residence; de fait -- present;  
      
1900, 1910, 1920, 1930, 1940 ... 1970?     

Historisk statistikk 1978 (pp. 34-35)  has u5 pops 1900, 1930, 1960, 1975. So does HS 1994. 

The U5 ages also on pdf3478 of Mitchell (2013) -- they are rounded but otherwise seem to match censuses.

[Norges folkemængde fordelt paa de enkelte aldersaar 1846-1901 (Population de droit](https://www.ssb.no/a/histstat/nos/nos_v_113.pdf). Norges hjemmehørende : resident population (de droit)          
Tableau no 1. Population de droit de la Norvège répartie par années d'âge au commencement de chacune des années de 1846 à 1901; pp32-37 (pdf47)  Tab 2 5yr age-groups by year.      
Translation from Norwegian: The figures relating to the population on January 1, 1846, 1856, 1866, 1876, 1891 and 1901, rely on censuses, while those for all intermediate year is calculated.       
See below for more on this source.      

Careful of dating -- HMD data are for Jan 1 of the year stated, but StatsNorway gives same values as Dec 31 of the prior year. So there is a simple 1-year discrepency to be alert for.     

NOTE Timing issue. HMD year is (StatsNor +1); HMD is for Jan 1 and SN is Dec 31. So HMD u5 t should be associated with IMR t-1, t-2, ..., t-5. Magnitudes: *Norges folk* refers to census-based populations: "The figures relating to the population on January 1, 1846, 1856, 1866, 1876, 1891 and 1901, rely on censuses, while those for all intermediate year is calculated." (translated from Norwegian).

E.g. HMD for 1866 and 1971 are Jan 1 values, which show up as the 1865 and 1870 values at Statistics Norway Tab 05810 (which table has footnote "Until 1990 the figures correspond per 31 Desember. As from 1995 the figures correspond per 1 January.." )

u7 populations 1845-2021 in [05810: Population, by sex and age 1845 - 2021](https://www.ssb.no/en/statbank/table/05810); those years correpsond to HMD(year +/- 1?); thus the 05810's 1865 value is HMD's 1866 value.

HMD & Norgesfolkemængde have same timing; but many of the pubs refer to end of year (so HMD t-1)

HMD u5 is same data as Norges folkemængde, which states age/sex data is for the start of the year; e.g. u5 male 1866 117,026 -- that is the value reported for 1865 by Statistiske oversikter 1948 and by HMD?.  Census refers to Jan 1, 1866 (but pdf39p3 refers to 31Dec1865 pop 1,701,756 which is table 05810 value for 1865 . 
e.g. u5 male 1865 114,326  1866 117,026  in HMD  & Norges folk; reported for 1865 in Statistiske 1948    

[Norges folkemængde fordelt paa de enkelte aldersaar 1846-1901 (Population de droit](https://www.ssb.no/a/histstat/nos/nos_v_113.pdf)  RESIDENT POP (de droit)
TRANSLATED   
FROM NORWEG: The figures relating to the population on January 1, 1846, 1856, 1866, 1876, 1891 and 1901, rely on censuses, while those for all intermediate year is calculated.
FROM FRENCH: Since 1876 the age has been expressed year by year, but for years previous years into groups which have been divided by years using calculations approximate, based on the number of births over the years corresponding. Similar calculations have been undertaken in part also for the censuses of 1876, 1891 and 1900 in order to correct certain irregularities from ages shown in round numbers.
FROM NORWEG: Norway's resident population distributed by individual age at the beginning of each of the years 1846-1901
Tableau no 1. Population de droit de la Norvège répartie par années d'âge au commencement de chacune des années de 1846 à 1901; pp32-37 (pdf47)  Tab 2 5yr age-groups by year;       
Tab 3 30yr age-groups; Tab 4 1yr ages for 5yr periods; Tab 5 5yr age-groups by sex for 5yr periods (1846-50, 1851-55, ... , 1896-1900)      

Hist Stats 1978 has u7 sex/age at 10-year intervals 1845-1875, 1890-1900, and 5-year intervals 1900-1975.

YrBk 1975 has u5 for 1972;  1971 has u7 values;

**IMR stats**  Use IHS 1876-1970.

1968 Hist Stats pp45-46 has IMR annually from 1836. But 1961 study authored by Backer (former Chief of Pop Division or such) indicstes that 1876 forward are reliable/valid. And 1978 Hist Stats p53 has 5-yr averages starting 1876 (not before). 1961 publication identifies likely errors in counts of miscarriages, stillbirths, and early-dead infants until the 1870s; and identifies 1876 as start of good data (in terms of stillborn vs eraly-dying). See below.     
<p>I dismiss HMD because HMD births data has m/f 106.00 for 1847-1915, except 1907 is 105.9948 -- I'm surprised they didn't tweak m or f by 1 ...
</p>

Ji calculated IMR via births and U1 deaths -- but the results are almost identical to those in IHS -- which is accesible to others.         

<p>Online data has births from 1735 and U1 deaths from 1836 in [3.13 Folkemengde, fødte, døde, ekteskap, flyttinger og folketilvekst](https://www.ssb.no/a/histstat/tabeller/3-13.html#)
<br>Population, births, deaths, marriages, relocations and population growth 
</p>
<p>Hist Stats don't give IMR by sex. [**Yearbooks**](https://www.ssb.no/a/histstat/aarbok/) have births & U1 deaths by sex, but be careful b/c they get revised over time (so early editions may be erroneous).
E.g. 1882 YrBk has births & u1 deaths for 1871-1880; 1885/86 YrBk has births & u1 deaths for 1878-1884; 
1890 1884-1888
1893 1887-1891
etc (see spreadsheet)
1902 1898-1900  plus 5yr avgs 1871-75, ... 1896-1900  (pdf 44); 1903 nothing new; 
1905 1899-1903   inf deaths 1897-1903; 1911 YrBk       births & inf deaths 1900-09; 1922 YrBk 1900-1919 (also 1917 has 1901-1915); slight changes from 1911, 1905 entries;     
1925 1900-1921 --but later birth totals not by sex don't match totals in table by sex ; 1948 Hist Stats has 5yr avg 1891 forward     
<p>
Ji finds one Stats Norway publication with IMR rates before 1871: [Dødeligheten og dens årsaker i Norge 1856-1955](https://www.ssb.no/a/histstat/sos/sos_010.pdf) (TREND OF MORTALITY
AND CAUSES OF DEATH IN NORWAY
1856 -1955, authored by "Julie E. Backer, former chief of the Population Statistics Division, Central Bureau of Statistics of Norway).     
This reports has 5yr avgs 1836-40 onward, for IMR and stillborn rates.    
Chapter IV.     
Table 20. Stillbirth rate and infant mortality rate 1836—1955 presents 5-yr averages of IMR.     
Table 21. Perinatal mortality and infant mortality rates 1876—1955 57     

p36 Ch2   Grunnlaget for dødelighetsstatistikken i Norge / The basis for mortality statistics in Norway.

vital stats (marr/bith/death) reg starts in 1685, with Priests.     
The registration of deaths with us has probably always been fairly complete,    

Siden 1797 er dødfødte barn blitt meldt til sokneprestene, men helt fram til 1870-årene var registreringen av disse mindre tilfredsstillende. Det samme gjelder for levende fødte barn som var døde like etter fødselen.  
*Since 1797, stillborn children have been reported to the parish priests, but until then In the 1870s, the registration of these was less satisfactory. The same goes for for live-born children who had died shortly after birth.*

Dette førte til at tallet på registrerte levende fødte og døde barn ble for lavt og tallet på dødfødte for høyt. De gjeldende bestemmelser om hva en skulle forstå med et levende og dødfødt barn ble imidlertid stadig innskjerpet overfor jordmødrene, og fra 1876 kan en gå ut fra at de tall som står oppført i den offisielle statistikk stort sett gir et riktig uttrykk for forholdet.
*This led to the number of registered live births and dead children being too low and the number of stillbirths too high. However, the current provisions on what to understand with a living and stillborn child were constantly tightened up for midwives, and from 1876 it can be assumed that the figures listed in the official statistics largely give a correct expression of the relationship.*

1866 summary lists were replaced by transcripts of the church books

p37 Starting with 1866, annual overviews of births, marriages, deaths in the resident population.  

LATER, assertion that IMR declined in 1840s and 1850s:  Den samlede dødelighet før og under fødselen og i første år etter denne var meget høy i slutten av 1830-årene, men falt så sterkt i de to følgende tiårsperioder og var relativt gunstig i 1856—60. 

The overall mortality before and during birth and in the first year after this was very high in the late 1830s, but fell so strongly in the two following ten-year periods and was relatively favorable in 1856-60.


[Dødeligheten blant spedbarn i Norge 1901-1963](https://www.ssb.no/a/histstat/sos/sos_017.pdf)  IMR 5yr averages, 1901-1905 ... 1956-60, 1961-63    Also [public in Norweg re: mort](https://www.ssb.no/a/publikasjoner/pdf/sa94/sa94.pdf) has some graphs re IMR, e.g. pdf44


[Statistisk årbok 1880](https://www.ssb.no/a/histstat/aarbok/1880.pdf)  (1880 yearbook)
ægtevielser marriages in 1876
livebirths m,f,tot 1870-76 pdf29 p21
u1 deaths m,f,tot 1870-76 p22 (6,236 in 1876; p23 born in 1876 died in 1876 4,238; born 1875 died in 1876 3,219)     
Antal utvandrere  number of emigrants

[YrBk 1885-86](https://www.ssb.no/a/histstat/aarbok/1885-1886.pdf)  p10 refers to pop by age 1875   then 1856-84 p19 births   p20 sstillb  deaths      


[1925](https://www.ssb.no/a/histstat/aarbok/1925.pdf)  p25 Table 22 has IMR 1901-1923  p22 births    

<p>1994 YrBk reports u6?</p>

[Statistical Yearbook of Norway 2000](https://www.ssb.no/a/en/histstat/aarbok/2000_en.pdf) Includes historical statistics and discussion, including "Nearly all statistics are revised, and nearly every revision means that comparisons of data from one year to another cannot be made without reservation. In notes to the tables, attention has been called to the substance of some of these revisions and how they have affected the data. For more information readers are referred to the text of Statistical Survey 1948, Historical Statistics 1968 and Historical Statistics 1994 (http:/Mww.ssb.no/historisk/ .).      
p67 provides dates of censuses, for us: 1845/46  1855/56 1865/66  31Dec (1945,55,65,75,90); 3Dec (1900,46); 1Dec (1910,20,30,50); 1Nov (1960,70,80); 3Nov (1990)    
p83 has u6 by sex every 5 yrs from 1961Jan1 to 2000.    p123 has IMR 5yr avg 1876-95, annually 1988-96.

[U7 populations](https://www.ssb.no/a/histstat/tabeller/3-6-en.html)

Historical Statistics has various years, including 1994 1968  1948
1948 version has u5 pops 1865 1875 1900 1910 1920 1930 1940

[2. Befolkning. Helseforhold (Population. Health)](https://www.ssb.no/a/histstat/publikasjoner/histemne-02.html#P538_17722)


HISTORISKE TABELLER OVER FOLKEMENGDE, GIFTERMAL, OG DODSFALL](https://www.ssb.no/a/histstat/nos/nos_a986.pdf) Historical Tables on Population Marriages and Deaths 1911-1976   --- based on 1911 entries, this has the HMD value offset by 1 year. The 1911 value here (end of 1911) is the HMD's 1921 value (start of year).

Online data: Historik statistikk	[3.3 Resident population, by sex, marital status and age](https://www.ssb.no/a/histstat/tabeller/3-3-en.html)  gives some resident population data, slightly different from (HMD and Norges Folk).     

[Historisk statistikk](https://www.ssb.no/a/histstat/)      
Mitchell reports IMR for Norway from 1786; but I cannot find those in the sources he cites (too broad a set for me to get through and translate). We will use the HMD time frame, 1846 forward. 

Statistics Norway [Historical Statistics](https://www.ssb.no/a/en/histstat/) .       
[Historical publications 1828-1996](https://www.ssb.no/a/english/histstat/publications/) list all statistical publications by subject with links.   That in turn groups the pubs as [1828-1976](https://www.ssb.no/a/histstat/publikasjoner/histemne-02.html) and [1977-1996](https://www.ssb.no/a/english/histstat/publications/ereg77-96_en.html#02) . The latter has two with pre-20th C items: the censuses of 1769 and 1801.      

[HS 1978](https://www.ssb.no/a/histstat/hs1978/hs1978.pdf) and 1968 -- have 5year average IMR; Mitchell publishes annual IMR values (source seems to be (p117) "official publications noted on p xv:)      

FROM Stat Norway: 

     Statistical survey/Historical statistics is a series of survey publications of historical time series published by Statistics Norway. Until the 1948 edition the publications were in Norwegian and French, thereafter in Norwegian and English. CR    The historical time series date as far back as it has been possible to give comparable figures. The publications are organized by subject and each chapter starts with an overview of the statistical sources and with a description of development trends.  CR  Editions: 1994 | 1978 | 1968 | 1958 | 1948  CR Note: The editions from 1978 and 1968 are more extensive than the 1994 edition.

[1978](https://www.ssb.no/a/histstat/hs1978/hs1978.pdf)


Drake [Population and Society in Norway](https://archive.org/details/populationsociet0000drak)
p94 Table 4.14 shows (for year 1832-38) inland IMR rates between 97 and 122; coastal rates between 162 and 191.

### Finland ###

Use HMD births and u1 deaths; they match Mitchell IMR for 1878 & 1879.
[Statistical Yearbook of Finland](https://www.doria.fi/handle/10024/67152/browse?type=dateissued) (Suomen tilastollinen vuosikirja) runs from 1879.     
Might use Mitchell for IMR, or HMD u1 deaths & u1 pop match Mitchell IMR for 1878 & 1879. HMD has births 1865-2019; deaths by yearly-age run from 1878 -- as do u1 death rates. Mitchell has IMR from 1866 ...   Mitchell's U5 populations do not match HMD (series 1), but they match HMD series 2;      

### Brazil

Brazil's [IBGE](https://loja.ibge.gov.br/) has historical statistics for [download:](https://biblioteca.ibge.gov.br/index.php/biblioteca-catalogo?view=detalhes&id=231573); e.g  [1822-89](https://loja.ibge.gov.br/historia-das-estatisticas-brasileiras-estatisticas-desejadas.html), 

[Brazil 1872](https://biblioteca.ibge.gov.br/biblioteca-catalogo?id=225477&view=detalhes)  Some funny-looking sex-ratio values in mestizos and slave >10 yrs?

<a name="AUSNZ"></a>

### Australasia

#### New Zealand  NZL ####

u5 populations by sex. 

1864, 1867, 1871, 1874, 1878, 1881: [Results of a census of the colony of New Zealand, taken for the night of the 3rd of April, 1881](https://www3.stats.govt.nz/historic_publications/1881-census/1881-results-census.html#idchapter_1_92910), 
Chapter 28, Table 1 ("Showing the Increases of Persons ... at different Ages ... the various censuses ... 1864 ... 1881).      

1881, 1886, 1891, 1896, 1901, 1906, 1911, 1916: Results of a census of the Dominion of New Zealand ... 1916, [Part II Ages](https://babel.hathitrust.org/cgi/pt?id=uc1.c2991401&view=page&seq=13&skin=2021), p. 1.     

[pop data](http://infoshare.stats.govt.nz/infoshare/SelectVariables.aspx?pxID=d7395c5c-e0e0-47bc-8747-9ec8360322d6) with "discontinued data" selected -- this has 1936 onward, all or excl Maori; but IMR includes Maori as of 1925ish
     
IMR:   1862-1945 ex-Maori  1947-1971 incl Maori  (NZ VS)     
     
Alternative sources:       
      
1864, 1867, 1871, 1874  [Results of a Census of the Colony of New Zealand ... 1874](https://www3.stats.govt.nz/historic_publications/1874-census/1874-results-census.html#idchapter_1_38615) Chapter 5, Table 1 ("Showing the Increases of Persons ... at different ages ... the various censuses ... 1864 ... 1874),
       
1867, 1871: [Results of a Census of New Zealand ... 1871](https://babel.hathitrust.org/cgi/pt?id=nyp.33433109911655&view=page&seq=23&skin=2021), page xvii.    

*1886*, *1891* in Ch 19 of 1891 Report     
*1896*, *1901* in Ch 17 of 1901 Results    
1896, 1901, 1906, 1911* in Ch 52 of 1911 Results (inet archive & downloaded)     
1886, 1896, 1906, *1916* in Ch 24 of 1916 Report.     
Proportions by age for males and females 1867, 1871, 1874, 1878, 1881, 1886, 1891, 1896, 1901, 1906, 1911, 1916 in Ch 24 of [1916 census](https://www3.stats.govt.nz/historic_publications/1916-census/Report%20on%20Results%20of%20Census%201916/1916-report-results-census%20.html#idchapter_1_20399) 

Ji thought there were u2 and u5 counts for 1881 through 1916 (censuses at 5yr interval) in a 1916 volume. Seems only u5? in ages part 2

-- the easily-found digitized 1916 census is overview only. BEWARE OF wasting time with 1916 census Report [condensed form](https://www3.stats.govt.nz/historic_publications/1916-census/Report%20on%20Results%20of%20Census%201916/1916-report-results-census%20.html?_ga=2.105906122.859603122.1632398281-861795157.1632395815) 
Preface. THIS volume gives in condensed form, with comments, the principal results of the New Zealand population census of 1916. Detailed results have already been published in twelve parts and five appendices, as under:—
Population May, 1918.  Ages July, 1918. Birthplaces and Length of Residence in New Zealand Sept., 1918. Religions Aug., 1918. Education Nov., 1918.  Infirmity Nov., 1918.  Conjugal Condition Nov., 1918. Fertility Sept. 1919. Occupations May, 1919. Aliens Feb., 1919. Dwellings June, 1919. Households: June, 1920. Appendices: (a.) Maori Census May, 1918. May, 1918. (b.) Census of Cook and other Pacific Islands May, 1918. (c.) Libraries and Religious Denominations May, 1918. (d.) Industrial Manufacture May, 1918. (e.) Poultry and Bees Oct., 1918.   
1916 census    
[Vol 1](https://babel.hathitrust.org/cgi/pt?id=uc1.c2991400&view=1up&seq=5&skin=2021) has 2 pdfs per page;    
[Part II Ages](https://babel.hathitrust.org/cgi/pt?id=uc1.c2991401&view=page&seq=7&skin=2021)
[Part II Ages](https://babel.hathitrust.org/cgi/pt?id=nnc1.cu08551570&view=1up&seq=94&skin=2021&q1=under%205) is pdf 94 on.
[Appendices A-D](https://babel.hathitrust.org/cgi/pt?id=nnc1.cu08551588&view=1up&seq=9&skin=2021) 

Listing of NZ stats-books online, from [UPenn](https://onlinebooks.library.upenn.edu/webbin/book/lookupname?key=New%20Zealand%2E%20Registrar%2DGeneral%27s%20Office) 


[Stats NZ Inforshare, Long-term data series, Infant mortality rates - DMMA](http://infoshare.stats.govt.nz/infoshare/SelectVariables.aspx?pxID=766e0a03-8df4-4b06-98f6-9b372a266fbc)

IMR was published in the NZ official year books; most have multiple years from which we can cobble together a series for total/non-maori/maori. Name changes from European to Non-maori.  E.g 1950 has 1939-1949, 1957 has 1937-1956, 1941 reports non-maori only, as IMR, for 1939 & 1940.  1890 Handbook 1881-90; 1899 1883-1892; 1893, 1894 inf mort in 4 cities

Excel spreadsheet at Stats NZ Store House, [A2.7 Infant mortality rate and infant mortality number](https://cdm20045.contentdm.oclc.org/digital/collection/p20045coll35/id/220/rec/1)  

Long-term data series / About this collection / This collection contains datasets that are no longer on the Stats NZ website.   
The long-term data series were collected by staff at Treasury to provide a general reference source of information on demographic, social, and economic trends in New Zealand. The series cover varying periods of time between 1840 and 2004. They are available as downloadable Excel spreadsheets (Excel 2002 format), and each file contains one data worksheet and one documentation worksheet.   
18 spreadsheets from search term Population in LTDS: A1.1 Total Pop; A1.4 North and South ISland pop; A1.6 Pop by Aage and sex; A1.2 Rural and urban population; A1.3 Maori and Pac Isl Pop; A2.8 Nat Increase; A1.5 Pop main cities and towns; A3.3 Assisted immigration; A2.4 deaths rates and numbers;   A2.3 Birth rates and birth nums; a3.4 immig expendit ; a2.2 Divorce; a3.1 immig emig net;  a2.5 Life exp; a2.1 marriage; a3.2 international visitors; a2.6 fertility rates; a2.7 imr

[browsing items in Long-term data series](https://cdm20045.contentdm.oclc.org/digital/collection/p20045coll35/search/searchterm/long-term%20data%20series!Population/field/subjec!subjec/mode/exact!exact/conn/and!and)

Infoshare search results for 'ltds' has 17 results, 2 with imr --  

9	Infant mortality rates - DMMA (Annual-Dec)
Last updated: 02 April 2012 10:45am
Table path: Long-term data series\Long-term data series - LTD Use with caution\
Select variables    Select series identifiers
10	Infant mortality numbers - VSDA (Annual-Dec)
Last updated: 02 April 2012 10:45am
Table path: Long-term data series \ Long-term data series - LTD Use with caution\
Select variables    Select series identifiers

Note, via HMD, Ji finds claims of underenumeration of births, with uncounted neonatal deaths ommitted from births and deaths. Correction might raise IMR from 100 to 116 in circa 1879.

births  
1855 to 1916 in [Chapter 20](https://www3.stats.govt.nz/historic_publications/1916-census/Report%20on%20Results%20of%20Census%201916/1916-report-results-census%20.html#idsect1_1_16061) of 1916 Census.


[***New Zealand***](https://www3.stats.govt.nz/historic_publications/)
[1916](https://www3.stats.govt.nz/historic_publications/1916-census/Report%20on%20Results%20of%20Census%201916/1916-report-results-census%20.html#idchapter_1_20399) has u2 and u5 counts for 1881 through 1916 (censuses at 5yr interval)


New Zealand [Yearbook collection: 1893–2012](https://www.stats.govt.nz/indicators-and-snapshots/digitised-collections/yearbook-collection-18932012/)    
[Archived version](https://web.archive.org/web/20120325003954/http://www.stats.govt.nz/yearbooks)      

1920 NZOYb no age data; 
1921-22 reports on 1916 census; 1923 some imr data;  no SR data: 1924 (some 1921 census data), 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935. AGES 1936 has 1926 u5 (also estimates for 1935, extrap from 1926 via vital stats -- not census, we don't use). NOT: 1937x 1938x 1939x 1940x, 1941no (1940 ages extrapolated from 1936 census) 

[1921 census report](https://catalog.hathitrust.org/Record/100209810)  hard copy at Columbia, looks like p82 has Age-Distribution in 1921

[1871 Results of a census of New Zealand ... ](https://catalog.hathitrust.org/Record/100615639) full view available. The catalog page has links to [1891 full](https://catalog.hathitrust.org/Record/008430840) 1901 [digitized](https://www3.stats.govt.nz/historic_publications/1901-census/1901-results-census/1901-results-census.html) at Stats NZ) 1916 1911 1916 1921

[Historical census collection](https://www.stats.govt.nz/census/previous-censuses/historical-census-collection/) for 1871, 1874, 1878, 1881, 1886, 1891, 1896, 1901, 1906, 1911, 1916.  


<H4>HMD on New Zealand</H4>

HMD suggests problems with NZ data.    
Non-Maori [Background and Documentation](file:///home/jim/Downloads/firefox.tmp/NZL_NMcom-1.pdf). "ABOUT MORTALITY DATA FOR NEW ZEALAND NON-MĀORI". By Domantas Jasilionis and Dmitri Jdanov Last updated: 07 December 2017.    
Important note: Due to recently discovered numerous inconsistencies in the historical data for Non-Māori, we restricted previously published series of Non-Māori data to the period 1901 onwards (for more details see the Background and Documentation file for New Zealand). 

New Zealand, Total Population. [Background and Documentation](https://mortality.org/hmd/NZL_NP/InputDB/NZL_NPcom.pdf) links to "ABOUT MORTALITY DATA FOR NEW ZEALAND". By Domantas Jasilionis, Rembrandt Scholz, and Dmitri Jdanov Last updated: 07 December 2017      
Important note: the population data for New Zealand are complicated by different levels of data quality by ethnic group (Māori and Non-Māori). Due to recently discovered numerous inconsistencies in the early historical data for Non-Māori, we restricted previously published series of Non-Māori data to the period 1901 onwards (for more details see the ‘Data Quality Issues’ section below). Starting in 1901, data for the Non-Māori population meet at least minimal data quality standards. 

p4 There is some evidence that death registration was incomplete until the beginning of the 1960s. First of all, concerning Māori deaths, ... possible underestimation at older ages prior to the 1960s  ... In addition, Non-Māori neonatal deaths were seriously underestimated at least until the 1910s (by about 18% in 1876).   NO SOURCE GIVEN
p4 Due to very serious deficiencies of data on deaths before 1901, the series of Non-Māori mortality estimates begin in the year 1901. However, the user should be aware that the HMD estimates for the Non-Māori for the periods 1901-1921 and 1939-1947 should be used with extra caution (see the ‘Data Quality Issues’ section below).      
p7 Historical data on Non-Māori births are also problematic, especially before the 1910s (Statistics New Zealand, 2006). First, there was an underestimation of neonatal deaths, which was quite significant (about 18% in 1876) until the beginning of the 20th century. Second, some Māori births were registered as Non-Māori. Last, births of Non-Māori who lived among Māori were also generally unrecorded (Statistics New Zealand, 2006). 


p10 There is evidence that New Zealand censuses conducted before 1926 were affected by undercount and age misreporting problems (Pool, 1973). Pool (1973 Pop Studies), "Estimates of New Zealand Maori vital rates from the mid-nineteenth century to World War I". Page 121: "From 1911 on ages were published in quinquennial groups, but the I9I6 Census was noted to be poor both in terms of coverage and age-reporting, while by 1921 the 'half-caste' rule mentioned above was becoming unworkable."     
Very strange to challenge non-Maori census data via an article seeking to estimate Maori vital rates.


HMD SOURCES refers to "Census Counts" Bloomfield, Gerald T. (1984). Tables II.5-II.6. Pp. 47-51 in: New Zealand, A Handbook of Historical Statistics. Reference publications in international statistics 1984. Boston, MA: Hall and Co. By sex and age group for 1858, 1861, 1864, 1867, 1871, 1874, 1878, 1881, 1886, 1891, 1896, 1901, 1906, 1911, 1916, 1921, and 1926. 

Non-HMD:    
Cited by HMD, Statistics New Zealand (2006), ["A History of Survival in New Zealand: Cohort life tables 1876–2004"](http://globalag.igc.org/elderrights/world/2007/survivalnewzealand.pdf)     
p9  Non-Mäori births understated when neonatal deaths occurred, probably until 1910s.
p12 2.1.4 Non-Mäori live births, 1876–1935
Although the birth registration system is believed to have provided an acceptable level of non-Mäori coverage, some adjustments to registration data were needed to estimate the number of non-Mäori live births that actually occurred in each year. The most signifi \cant adjustment was the addition of unregistered births when neonatal death occurred. The under-registration of neonatal deaths in New Zealand is recognised (eg Pool 1982, 1985), although quantifying the extent of registration is more difficult. The distribution of infant deaths by age (days at death) suggests under-registration of non-Mäori neonatal deaths before the 1910s and Mäori neonatal deaths before the 1960s. Based on mortality patterns at that time, roughly 80 percent of these unregistered neonatal deaths were likely to have occurred within the fi rst day of life. For infants who died soon after birth, it is likely that if their death was unregistered then their birth was unregistered also. The adjustments to neonatal deaths (see Section 2.2.4) were therefore applied to births. This corresponds to an increase in non-Mäori births of less than 2 percent in 1876–1911.     
p21 [births] Maximum of 320 added in 1879.  1921 census has births -- implication is IMR of 100 raised to 116



older version (maybe HMD)? [ABOUT MORTALITY DATA FOR NEW ZEALAND](https://www.demogr.mpg.de/publications/files/2172_1150381700_1_MortDataNewZealand.pdf) By Domantas Jasilionis Last updated: 06 October 2005 Rembrandt Scholz Dmitri Jdanov    
p2 Although the completeness of Māori data has improved, data quality problems remain important (see the section on "Data quality issues"). Furthermore, starting in 1962, these problems may have also been relevant for the Non-Māori data1     
p5 Historical population data on Non-Māori (prior 1930s) seem to have data quality problems at older ages (see section on ”Data quality issues”).     
p6 Due to poor quality of Māori statistics, births may be underreported or misreported until 1961     
p7 DATA QUALITY ISSUES     
1. Quality of data on population counts. There is evidence that New Zealand censuses conducted before 1926 are affected by undercount and age misreporting problems (Pool, 1973). Due to substantial under-reporting of vital events, the quality of Māori population estimates are considered less reliable until 1936, or perhaps even 1961 (Statistics New Zealand, 2004a).     
Our own estimates suggest serious under-reporting of deaths at older ages among the Māori and Non-Māori populations    
p8 3. Problems with Non-Māori old age mortality estimates before 1902. Prior to 1902, our estimated death rates at older ages are implausibly low

OTHER: Seems not useful: source book of population data : New Zealand, non-Maori population, 1921-1967 / by Shailendra K. Jain.

#### Australia ####


Australia under-5 populations by sex: census values, populations "as recorded" 1901-1961; 1966 & 1971 census allocated "unspecified" ages to ages based on responses to other questions, so the values ("adjusted" rather than pure census) should be fine for us.

1901 April 

Slightly different values are in ABD 3105.0.65.001 Table 2.1: "Population, age and sex, Australia, 30 June, 1901 onwards" (Released at 11.30am (Canberra time) 18 April 2019); downloaded 27 June 2021  from 3105.0.65.001 Australian Historical Population Statistics, 2019.   

[Census volumes at ABS](https://www.abs.gov.au/AUSSTATS/abs@.nsf/ViewContent?readform&view=ProductsbyCatalogue&Action=Expand&Num=2.2)

[Dates](https://www.abs.gov.au/methodologies/historical-population-methodology/2016) of censuses      
1871 Apr 2 (QuLd Sep)  1881 Apr 3, 1891 Apr 5, 1901 31 Mar; April 1-3 for 1911, 1921. 1936 forward June 30.  

[HCCDA](https://dataverse.ada.edu.au/file.xhtml?fileId=15310&version=4.1) has wide range of AUS census data.

1933 census offers populations "as recorded" by age/sex for 1901, 1911, 1921, 1933
1901 is almost the same as the ABS; 1911 ABS is the "as recorded" census value; 1921 almost the same (ABS 103.71 Cen 103.68)      
1933 is non-negligible: ABS 104.85  Cen 102.29   -- deviation is 0.54%      
<p>1947 census offers recorded age/sex populations 1901 to 1947;     
1954 census has  
</p>
<p>1961 Bull 25 p2 The figures for five-year age groups contaim:d. herein are a r3vision of and supersede the f,'L'ouped age data appearing in p:revious bUlletins. The single age data are pUblished for the first tL:le</p>

<p>1966 5yr ages shows 1954 1961 1966 unspec ages were allocated (various discussions suggest well enough for us)
</p>
1971 census includes aboriginals, for the first time; Bulletin 3 has u15, then single year ages.     
1976, 1981 census pubs don't seem to add data for us (1981 confirms 1971 u5 total). 1976 and others have % distributions ...


HMD has u5 counts and IMR date from 1921; we use ABS data instead (basically the same for 1921 onward)


##### IMR for AUS

IMR 1901-1991 from Australian Bureau of Statistics

For AUS  IMR 1870-1991 (1870-1901 AHS; 1901-1991 ABS; 1901 values same in both); Before 1870, we have only 1 point: NSW 1861 IMR & U5   (IMR 89.2 Ln(f/m) = -1.42% (m/f=101.4) )
 
1901 onward is straightfoward, with the data in [ABS spreadsheets](https://www.abs.gov.au/statistics/people/population/historical-population/latest-release) (3105.0.65.001 Australian Historical Population Statistics, 2019).     
U5 pops from [2. Population Age and Sex Structure](https://www.abs.gov.au/statistics/people/population/historical-population/2016/3105065001ds0002_2019.xls)
Table 2.1 has AUS u5 f/m pops 1901, 1911, 1921-2019.  Various other tables give state-level U5 by sex from 1901 onwards (NSW, Vic, Qld, SA, WA, Tas). Varying coverage of pre-1901 (see below.)     
IMR data from Table 5.4 in [5. Deaths](https://www.abs.gov.au/statistics/people/population/historical-population/2016/3105065001ds0005_2019.xls). This provides annual IMR, Australia and by states and territories (3105...ds0005_2019.xls) for 1901 forward.     

We may also want to use [4. Births](https://www.abs.gov.au/statistics/people/population/historical-population/2016/3105065001ds0004_2019.xls) in Table 4.1 Births registered by sex, states and territories, 1824 onwards  Births (m,f) for AUS and by state from 1860 or earlier.

For data before 1901, we mostly refer to Vamplew (1987) *Australians: Historical Statistics.*     
Ch 2 (Population) includes census data with u5 f/m pops for AUS and states for census years 1861 to 1901; also      
1854, 1857 Victoria; 1856 New South Wales (u4 populations). If additional regional data is needed, we should check the ABS Tables above (Population Age and Sex Structure) -- but I expect those are the same.

Ch 3 has IMR nationally and by states from 1870; also infant deaths. 1921 on has some sex-specific data.    
Ch 18 (Health & Medicine) has NSW death rates for u1 male and female for census years 1861 to 1891.


If narrower age breakdowns are desired, for state-level data 1911 onward, use [census publications 1901 onward](https://www.abs.gov.au/AUSSTATS/abs@.nsf/ViewContent?readform&view=ProductsbyCatalogue&Action=Expand&Num=2.2)   
For 1911, use census values "recorded" for regions; the "recorded" values for AUS are those in ABS 3105 Table 2.1  And so we don't use "unadjusted" (unknown ages added in, unsmoothed), nor the "adjusted" which are smoothed in some fashion. We rely on ABS 3105 Table 2.1 and our presumption that recorded is best. 

Notes on 1911 *Ages* "Number of Males recorded at each Age" and same for females, by state; also u5 f/m pops for 1901 and 1911. Also for AUS f/m pops by single-year of age in 1891, 1901, 1911 (p15); described as "unadjusted" but unspecified have been added in pro rata ("but the figures have not been smoothed" Table 7 p15pdf15).     
Also for AUS, f/m U5 pops for 1881, 1891, 1901, 1911.  1911 U5m 268,073  -- same note as above, uspec added in     
Also "adjusted number" at each age in 1911. Consider age 0:      
males recorded NSW 22,939 AUS 59,102 (Tab 1, p5)     But with unspec Tab 7 1911 AUS male u1 59,248    
adjusted males NSW 22,750 AUS 58,648 (Tab 9, p17)     
My older notes said: Decennial censuses benchmark 1881, 1891, 1901, 1911 are in [1911 census](https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/2112.01911?OpenDocument) Ages volume has "adjusted" numbers by age/sex for 1881 1891 1901 1911  (pdf p32)  Vol1 discussion of smoothing has figures suggesting not much done to 0-4 group.

1911 Table 24 has age/sex for cities (metropolises)


[Taylor et al 1998](https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1467-842X.1998.tb01141.x) p28 says "Annual infant deaths ... for Australia are recorded back to 1870. FN 4,5,8,9

4 is Van Plew ed. [Australians - Historical Statistics](https://socialsciences.org.au/australians-historical-statistics/)  Ch 2 Population   series 44-54 Victoria 1854, 1857 by age & gender -- maybe 30k males u5 in 1857 (with 60k kids, 75% CI is +/- 1.0 )    

5 is Cumpston JHL. Health and disease in Australia: a history. LCumpston JHL. Health and disease in Australia: a history. Limited search via google books ...

9 is [P Mein Smith thesis](https://openresearch-repository.anu.edu.au/handle/1885/117391) link down Sun 27 Jun 912. 

ABS has Coghlan's [full set of volumes](https://www.abs.gov.au/AUSSTATS/abs@.nsf/second+level+view?ReadForm&prodno=1398.0&viewtitle=A%20Statistical%20Account%20of%20the%20Seven%20Colonies%20of%20Australasia~1892~Previous~22/04/1892&&tabname=Past%20Future%20Issues&prodno=1398.0&issue=1892&num=&view=&)   Past releases Tab

Limited data for 1899-1900 in [issue8 1899-1900 at ABS](https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1398.01899-1900?OpenDocument)

Coghlan 1899-1900 p249 (pdf264) Population    pdf271 1899 births by sex and state, and New Zealand. Later, total births by 5yr periods (could be useful to check HMD) But deaths are for 1898, data for ages 0 1 2 3 4 5-19 by sex pdf 277    
p272 whooping cough kills girls more than boys

Google.ca has some (or all?) volumes of Coghlan. E.g. [Coghlan v10 1902-03 ](https://books.google.ca/books/about/A_Statistical_Account_of_Australia_and_N.html?id=mmoZAAAAYAAJ&redir_esc=y)  


Coghlan [1903-04 Vital Stats](https://www.ausstats.abs.gov.au/ausstats/free.nsf/0/383F14EFC0D4D9E4CA257F60007C3D73/$File/18_13980_1903-04_Vital_Statistics.pdf)  p177 births in 1903, by sex, for States, AUS, & NZ; p 184 deaths by age in 1903, for states, AUS, & NZ. 

[Victoria 1871](https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1309.21871?OpenDocument)

https://www.abs.gov.au/AUSSTATS/abs@.nsf/ViewContent?readform&view=ProductsbyReleaseDate&Action=Expand&Num=129.2

[items by date](https://www.abs.gov.au/AUSSTATS/abs@.nsf/viewcontent?readform&view=ProductsbyReleaseDate&Action=expandview&num=1)  Lots of Aussie datA


For interest, other sources include [Yearbook Australia](https://www.abs.gov.au/AUSSTATS/abs@.nsf/second+level+view?ReadForm&prodno=1301.0&viewtitle=Year%20Book%20Australia~2012~Latest~24/05/2012&&tabname=Past%20Future%20Issues&prodno=1301.0&issue=2012&num=&view=&) annually 1908 onward

HMD [on Australia data](https://www.mortality.org/hmd/AUS/InputDB/AUScom.pdf) says:   

     Due to the legal requirements of the birth registration system established in the middle of the 19th century, data on births are considered to be complete and of good quality

ABS page with [good overview of the censuses](https://www.abs.gov.au/ausstats/abs@.nsf/Products/F3AF616665E821A6CA2575D2001AA12E?opendocument) as well as links to spreadsheets of data.

<a name="SouAfr"></a>

### South Africa ###

u5 population data is lacking; we have 1904, 1911, 1918. IMR data is available for whites 1910-1990.

IMR "coloured" IHS starts with 1937 and 1937-1940 ranges 157-166 (with 1941 166, 1942 177)
So we want SR data 1921 1931?  1941?      6th census 1936  vol II ages  vol IX Bantu     

Columbia Clio shows     
microform [South Africa--Census, 1865, 1904, 1911, 1918, 1921, 1916, 1931, 1936, 1941]()


[1921](https://clio.columbia.edu/catalog/10770950) via Gale, 19th C COllections Online

1936 is more than vol 1 available? SHould be, since it is on microfilm
ZAN-T4817 Africa: South Africa  1926: no. 1-1936: no. 1   ADV REQUEST
	
Sixth census of the population of the Union of South Africa, enumerated 5th May 1936. Ages and marital condition of the Bantu Population / Sesde sensus van die bevolking van die Unie van Suid-Afrika, opgeneem 5 Mei 1936. Leeftye en huwelikstaat van die Bantoebevolking / Unie van Suid-Afrika. by South Africa. Office of Census and Statistics (1917-1951);

South Africa. Office of Census and Statistics.  Sixth census of the population of the Union of South Africa, enumerated 5th May, 1936. = Sesde sensu  Pretoria : Printed by the government printer, 1938
Schomburg Center - Research & Reference	 Sc+ 312-S (South Africa. Office of Census and Statistics. Sixth census)  v. 6-7, 9  

[Columbia -- Offsite at Princeton](https://clio.columbia.edu/catalog/SCSB-1076056)
Natives (Bantu) and other non-European races. [Microform]
AuthorSouth Africa. Office of Census and Statistics.
TitleNatives (Bantu) and other non-European races. [Microform]
PublishedPretoria, 1942.  
Subjects
South Africa > Census, 1936.

UG12/42, Sixth Census of the Union of South Africa 1936, Volume IX Natives (Bantu) and Other Non-European Races (Government Printer, Pretoria, 1942), p xxv.      
UG50-'38, Sixth Census of the Union of South Africa 1936, Supplement to Volume IX Ages and Marital Condition of Bantu Population (Government Printer, Pretoria, 1938), p v.     

International population census publications, region, Africa. Country, South Africa. [Census year(s), 1946, 1951, 1960](https://clio.columbia.edu/catalog/SCSB-8778348) Seems to have 1946 no. 0-6   Seems to be at NYPL ... OFFSITE - Request in Advance for use at Schwarzman Bldg - Microforms Rm 315  

[Info on Sou Afr censuses](http://www.scielo.org.za/scielo.php?script=sci_arttext&pid=S0018-229X2011000200001)  1911  1918 whites only  1921 full pop   1926 whites only 1931 whites only  1936 full pop  1946 full pop   1951 full pop  1960 full 

[UPenn online Sou Afr stats](http://onlinebooks.library.upenn.edu/webbin/book/lookupname?key=South%20Africa%2E%20Office%20of%20Census%20and%20Statistics)

Maybe 1938 Official year book of the Union and of Basutoland would have age/sex for sr5?

IGME 1974.5 IMR 90    1980 67
IHS  1974 18 116  1975 20 104 (4/5 B  implies ~87)  1980   13  61 NOPE  
IMR for whites in IHS,  1910-1990. These are reported as integer values of rates per thousand; more precise values are found in the official yearbooks (Ji notice a few small discrepencies, but IHS is consistent with the more recent Yearbooks' data).    
IMR for "colored" 1937-1990    
But IGME IMR are higher:  1980 67.01  while IHS w 13 col 61  ...

u5 white populations (by sex) :  we have 1904, 1911, 1918    

Ouderdom -- Age

Report 03-00-092016.pdf says IMR fell to 35 per 1000 in 2011-16 versus 45 in 1993-98 (DHS )

IGME suggests 

Maybe Columbia has u5 pops in [Fourth census ... 1926](https://catalog.hathitrust.org/Record/009114310); but 1931 seems not online. Expect we can get u5 and u2 pops from [Report with summaries (1933)](https://clio.columbia.edu/catalog/SCSB-7896259) or [Fifth census ... 1931](https://clio.columbia.edu/catalog/2731375?counter=1); same is [search-only for Jim at Hathi](https://catalog.hathitrust.org/Record/009127872).       

Columbia has [1970 census[(https://clio.columbia.edu/catalog/2520600)

Columbia U has [1921 online](https://clio.columbia.edu/catalog/10770950), 1926, 1931, 1936, 1941 are off-site at NYPL?;  

First General Census of the Union of South Africa (1911)
Census of the European or white races of the Union of South Africa, 1918    
Third census of the population of the Union of South Africa, enumerated 3rd May, 1921.     
Fourth census of the population of the Union of South Africa, 4th May, 1926. (Enumeration of Europeans only)     
Fifth census of the population of the union of South Africa enumerated 5th May, 1931.     
Sixth Census 1936; Later censuses of interest 1951, 1960, 1970.

Censuses listed in the [OpenEdition book](https://books.openedition.org/irdeditions/1805?lang=en): 1951, 1960, 1970, 1980, 1985, 1991, 1996, 2001   Bevolkingsensus 1985 / Population census 1985

Aug30 looked to add 1926 and 1931, but copyright nonsense makes it impractical. IHS has IMR data -- so no need for a trip to NYPL for IMR data. 

** Yearbooks **

Maybe SR5 data for census years will be found in this set of the ["Official year book" at Hathi](https://catalog.hathitrust.org/Record/007119366), which has various years from 1924 to 1960. Or in [this set](https://catalog.hathitrust.org/Record/009064515) with various in the years 1917 to 1953.

Yearbooks 1919-61 are "Offsite" but requested/used at [NYPL](https://www.nypl.org/research/research-catalog/bib/cb3033381#). That entry  explains "None published 1922, 1936, 1942-1945, 1947, 1951, 1958-1959. Some years combined."

1964-66 on microfilm [at Stanford](https://searchworks.stanford.edu/view/6789332) or [offsite at Columbia](https://clio.columbia.edu/catalog/834401)

1968-1995 is called Suid-Afrikaanse statistieke [e.g at Columbia/NYPL](https://clio.columbia.edu/catalog/SCSB-8157364), they have 1968-1974,1988-2009.

Js checked [1925 Yearbook](https://hdl.handle.net/2027/uc1.b3076166): IMR by "health year" vs calendar year; the former running July 1 to June 30.  Bantu pop by sex u1 1-14 -- too broad.

IMR from [YearBooks](https://clio.columbia.edu/quicksearch?q=Official+year+book+of+the+Union+and+of+Basutoland&commit=Search); they are online at Columbia University (search term= Official year book of the Union and of Basutoland )  Nos. 1-4 ;  IMR 1924-1928 p932 of 1928;    1919 p209 ; 

[1922 Yearbook Vol 5](https://books.google.ca/books?id=hNIzAQAAMAAJ) has rich data for 1910-1921. PDF p17 indicates that 1922 repeats and adds to the stats data in vols 1-4 (No. 1, 1917, has 1910-16; No. 5, 1921, has 1910-21).     
p157-59   Ages of the people, lots of u5 data for 1904, 1911, 1918.    
p158 urban/rural 1911 1918

Census, 1911 ... Reports [vol. 1 (report/Part 1-4)](https://hdl.handle.net/2027/njp.32101031665449). South Africa.  
241-334 Part 1 Population and Dwellings pdf 241
242 Census Tables, 1911 ... show tables of pp 7-93  
335 Census 1911 Annexures to General Report, Part 2   337:Ages of the People
341p99 Afrik-language TOC   343p101 Part II  Comparative Summmary under/over 15
346p104 Table IV Numbers re Age 21 (under/over)  348p106 proportions under/over 21, 15
352p110 Table VII Union and each Province, Proportions re Age 21
354p112 Table VIII Whites 0-4 5-9 etc  1911 1904
360p118 Table XII Orange F S, Ages 1911 1904 0-5 
**single year 1 to 5** 
362-367 Table XIII Ages Union, and by Provinee, Urban+Rural  pdf362-367 **single year 1-5** 

368 Table XIV Proportions 374p132 Table XV proportions, by race    
380p138 Table XVI Urban, **single year 1-5** 144 Table XVII Proportions 392p150 TableXVIII proportions 396p154 Table XIX Numbers, single year, centres 2000 and more  402p160 Table XIX continued  408p166 TableXX RURAL    414p172 Table XXI rural proportions  420p178 Table XXII Proportions  424p182 Table XXIII Ages: Union, Provinces, Census Districts  440p198 Table XXIII continued         477- Census Tables Part III Education


1921 Third census of the population of the Union of South Africa  -- HATHI search-only  f548p18 asiatics by age;

[1926 census](https://catalog.hathitrust.org/Record/101697766), Third census of the population of the Union of South Africa, ... South Africa.    Part II Ages (Europeans)  Part VIII a Natives b Coloured & Mixed  c Asiatics    163Part3 341p1 372p32 occs & birthplaces


Census of the Union of South Africa, [1911 search-only Hathi](https://catalog.hathitrust.org/Record/100615661)

Census of the European or white races of the Union of South Africa, [1918](https://catalog.hathitrust.org/Record/009676009)

[maybe](https://catalog.hathitrust.org/Record/008616578)    Simkins & van Heyningen article seems to have leads

Dead-ends: Yearbook leads at this [Springer link](https://link.springer.com/chapter/10.1057/9780230271104_144)   [2001-2020](https://www.gcis.gov.za/content/resourcecentre/sa-info/yearbook)

***Natal***
1891 Census -- no IMR or birth data   Table 4 age and sex
1894 Statistical Year Book  G 8-9 some vital stats, with u5 pop and marriages, but not infant deaths,

***Good Hope***
[1875 census](https://babel.hathitrust.org/cgi/pt?id=uc1.l0074071200)  54p47 age by sex  No death data

Hathi has [Cape of Good Hope](https://catalog.hathitrust.org/Record/100119047): 1893 full view (also three search only 1902, 1907, 1908).  They are available on Google Books  [1905](https://books.google.ca/books?id=2NxCAQAAMAAJ)

Statistical Register of the Cape of Good Hope [for the year 1904](https://books.google.ca/books?id=2NxCAQAAMAAJ) page v lists births by year 1895-1904 with text saying 1904  euro or white 9454 males and 9006 females; Malay 291 males and 293 females; Fingo, Kafir, Bechuanaland 10,661 males and 10,187 females; Mixed and other 8548 males and 8361 females. Colony proper (ex. Bechuanaland) 46,419 9006 maleEuro 8603 femEuro (9006 twice - stet) ...   The 46,419 are also shown for 1904 in the table of births.  
Page 47 lists births, as M F for Total/Euro/Not and Urban/Rural; also Totals 1904, 1903, 1902

1904, 1909 search only at Hathi

[1892](https://babel.hathitrust.org/cgi/pt?id=nyp.33433062734938&view=1up&seq=9&skin=2021) reports the 1891 census data u5 and single years
[1894](https://babel.hathitrust.org/cgi/pt?id=nyp.33433062734946&view=1up&seq=7&skin=2021)  p32 U14 ages

IHS cites South Africa Statistical Year Book (1912–13, 1915–16); Official Yearbook of South Africa (1917–60); South African Statistics (1964 ongoing). And IHS gives white IMR 1910-1990; 1910 value in IHS is 89 but 1922 YrBk has 91.24  and 1980/1 has 88.5
A7 Africa: Deaths of Infants under One Year Old per 1,000 Live Births  IHS 1750-2010: Africa, Asia and Oceania  

### Organization/locations of R scripts and csv files



<a name="Data"></a>

## Data Sources and Links ##

HMD is perhaps key, I look for q0 in England and Wales, Civilian National Population, Life tables (period 1x1), Total	Last modified: 10 Jul 2020;  Methods Protocol: v6 (2017)

Europe IMRs in B. R. Mitchell (1998), International Historical Statistics Europe 1750-1993 4th edition  pdf140

### UN Sources ##

re: Demographic Yearbook  https://unstats.un.org/unsd/demographic-social/products/dyb/documents/techreport/ageandsex.pdf

Our data from [demog stats DataBase](http://data.un.org/Data.aspx?d=POP&f=tableCode%3a22) thailand 1956 1960  1970 1980 

The Bulletin of the WHO, [2000, 78:1175-1191](https://www.who.int/bulletin/archives/78(10)1175.pdf)   
U% mortality rate ... has a number of advantages over the infant mortality rate as a composite measure of health risks
at young ages. In particular, the indirect demographic techniques for measuring the under-five mortality rate are more robust and less sensitive to assumptions about the underlying patterns of mortality than the infant mortality rate (28, 29) 
Data obtained from the complete registration of births and deaths provide the best possible basis for the direct estimation of child mortality. Unfortunately, such data are available for only 55–60 countries.d

<p>Unicef spreadsheet of [IMR Data](https://data.unicef.org/wp-content/uploads/2020/09/Infant-mortality-rate_2020.xlsx) </p>

Bangladesh article [IMR source](https://link.springer.com/article/10.1186/s12884-018-2129-y)


UN Demographic and Social Statistics [Demographic Yearbooks]](https://unstats.un.org/unsd/demographic-social/products/dyb/#statistics)
1997 version has preliminary values; 
1998 PDF pp149-228; notes 228 CDFC census, de facto, complete tabulation (vs sample)
Thailand 1990 0-4  

UN Dept of Eco Soc Affairs [Population Dynamics](https://population.un.org/wpp/Download/Standard/Population/) (in Jim's digital library SSMM/demog). *These do not match with Demographic Yearbook data*

Mortality from IGME [UN Inter-agency Group for Child Mortality Estimation](https://childmortality.org/data/Nigeria)

IMR [Estimation methods for child mortality](https://www.who.int/gho/child_health/mortality/ChildCME_method.pdf), p2. states IMR = 1q0 *1000  (2013 WHO)

[WHO Mortality Database](https://www.who.int/healthinfo/mortality_data/en/) has population for <1 1-4  ... single year, 1950 forward. But not Nigeria nor Ethiopia

[HMD life table](https://www.lifetable.de/data/BGD/BGD001019801980AU1.pdf)  Bangaldesh 1980 0q1 male 90 female 118 per 1000. Seems to be early work of [HDSS](https://academic.oup.com/ije/article/46/3/809/3867622)

Looking at UN? pop by age data: Ghana Cameroon   1-4 yrs
https://population.un.org/wpp/Download/Standard/Interpolated/


<a name="USA"></a>

### USA ###

#### SR Population counts

<p>our spreadsheets USAkidsForR.xls has national totals; US-KIDSFORR.XLS has state and finer data, but I (Ji) don't know if it is the most complete.  </p>

<p>1910 PUMS SRs from usa_00043.csv; 
<br>**discrepencies** between fPUMS and published volumes include <br>Mass SR5 f-101.5 c-102.0 ; <br>NY white SR5 f-101.4 c-102.1 (SR2 101.9 102.9) ... when time, Jim to randomly sample ...
</p>
<p>1920 PUMS SR5 OH & NY are 0.2 above the census-volume values. MI P&C are both 102.9.
</p><p>
census date or census timing: 1930 onward April 1 (90/365); 1920 Jan 1;  1910 April 15, 1840-1900 June 1* (1890 June 2)  
1850-1900 June 1 (but 1890 June 2); 1910 April 15; 1920 Jan 1; 1930 onward, Apr 1. 
[1900](https://www.census.gov/history/www/through_the_decades/overview/1900.html) Jan.1; [1910](https://www.census.gov/history/www/through_the_decades/overview/1900.html) Apr 15; 1920 Jan 1;   
</p>
<p>Underenumeration of infants and children? Hacker (2003) relies on PUMS samples, which we doubt for SR data. Earlier work on fertility refers to infants, but the empircal work and estimates work with 5-yr groups (u5, 5-9, etc). See LIT? for Thompson & Whelpton (1933), Yasuba, Coale & Zelnick.
</p>
<br>
1850 compendium DeBow p 104 mentions age heaping at 10 15 20 ....
<p>US Census Office offers a partial listing of [**Pubs by decadal census**](https://www.census.gov/programs-surveys/decennial-census/decade.1950.html). But the 1890 page does not show Volume 4, which has vital statistics<br>
Maybe other volumes are at the older link to [Decennial Pubs](https://www.census.gov/prod/www/decennial.html). 
<br>Sometime useful are the IPUMS USA [incomplete links to census volumes](https://usa.ipums.org/usa/voliii/tPublished.shtml)
<br> * also see the PDF on 20thC US for linked sources, in our B/W page
</p>

#### USA IMR

HSUS (1976) [Vital Statistics and Health and Medical Care](https://www2.census.gov/library/publications/1975/compendia/hist_stats_colonial-1970/hist_stats_colonial-1970p1-chB.pdf). Vital Statistics (Series B 1-220). Series B 142-144 Infant mortality rate, by, race, 1915-1970. Source: U.S. Public Health Service, 1915-1939, Vital Statistics--Special Reports, vol. 45, No. 1, p7. {I find it at Google via Hathi. Odd that they don't cite Linder & Grove, as in the 1957 edition}. 1940-70 from Vital Statistics of the US: 1940-67 in VSUS, 1967, vol. 11, Part A, p. 2-3; 1968-70 VSUS annual issues.
<br>1915-1932 Registration area only.  1915 99.9  1916 101.0   1931-61.6 1932-57.6  1933-58.1
And same values in Linder & Grove.     
<br>p44 B 1-220. General note.  
<br>A two-part compendium updating and expanding the second edition, Historical Statistics of the United States, Colonial Times to 1957. 
<br> US Bureau of the Census, *Historical Statistics of the United States, Colonial Times to 1970,Bicentennial Edition, Part 1*, Washington, D.C., 1975.

<p>June 1959 [Historical Statistics of the United States, 1789 - 1957](https://www.census.gov/library/publications/1949/compendia/hist_stats_1789-1945.html)9-
<br>Cites Linder & Grove for IMR. 
    </p>


<br>[NVSS HIST293](https://www.cdc.gov/nchs/nvss/mortality/hist293.htm) offers data and discussion about US mortality statistics (DRA 1900-32, USA 1933-98) 

<p>CDC NCHS [Vital Statistics](https://www.cdc.gov/nchs/products/vsus.htm) e.g. [1890-1938](https://www.cdc.gov/nchs/products/vsus/vsus_1890_1938.htm)
<br>[1900-1970](www.census.gov/data/tables/time-series/demo/popest/pre-1980-national.html)  
</p>


#### BRA/DRA data

2021Nov02 1850-1900 June 1 (1890 June 2); 1910 April 15; 1920 Jan 1; 1930 onward, Apr 1. 
[1900](https://www.census.gov/history/www/through_the_decades/overview/1900.html) June 1; [1910](https://www.census.gov/history/www/through_the_decades/overview/1900.html) Apr 15; 1920 Jan 1;   
DRA 1910 IMR estimated via u1 deaths, u1 pop, separation factor
 1910 u5 boys 3145145.0      eIMR 107.45935 (m&f)

1910 builds from USimrDRA1910.RDS 16June2021, which is with USimrBRA.RDS in Wrangling/Raw/US ...
USimrDRA1910.RDS   Note we have only 1 yr of IMR data to connect to SR (so use SR2?)

Dempap uses full BRA. BRA data for IMR 1920, 1930 -- US totals (but 1920 is Jan 1, so 1920 refers to 1919; before 2021Nov 2, 1920 erroneously included some 1920 IMR). Ji also looked at US-North 1920 (excludes DC) amd   1930 US-North US-Sou-white US-Sou-black.        

USimrBRA.RDS is simply the BRA part of USimr-BRA.xls (which covers 1915-1931); that RDS file was made by EstUSimrDRA.R, and that file reads the u1 deaths counts from USimr-BRA.xls (top part of which is the BRA data) and merges them with the u1 pop counts in US1910SR1.RDS (which was created from 1910 PUMS full-count in 2nd part of buildPUMSurb10.R). That SR1 file has 27 states (tot/urb10k, rur10k)

u2u5forBRAimr.RDS 

For 1920 and 1930, we get IMR by state/race from [Lindner & Grove (1943)](https://www.cdc.gov/nchs/nvss/mortality/hist293.htm#:~:text=Lindner%20FE%2C%20Grove,the%20Census.%201943%3B) Vital statistics rates in the United States, 1900-1940. We use annual Birth Statistics pubs to get birth counts. Oddly, [Hetzel's](https://www.cdc.gov/nchs/products/other/miscpub/vsushist.htm) history of US vital statistics systems has SC starting in DRA 1916 and BRA 1919, yet SC not in Birth Stats 1926     

South: 1925-1930 DC (6 2.8) DE (3.6 0.7) FL (20 9) KT (53 3.5) MD (24 6) NC (53 24) VA (38 16) WV (38 2) 

1925 birth stats (google books or Hathi)  pdf 33 has table with legit & illegit by state, but not total births ...       
Va 1917      
Ala Ark La Tn are 1927 onward, so could relate them to SR2 ...   GA 1928 

1910 builds from USimrDRA1910.RDS 16June2021, which is with USimrBRA.RDS in Wrangling/Raw/US ...


#### USA data on/for Infant Mortality 1890, 1900-1904, 1900-1905

<p>CDC NCHS [Vital Statistics](https://www.cdc.gov/nchs/products/vsus.htm) e.g. [1890-1938](https://www.cdc.gov/nchs/products/vsus/vsus_1890_1938.htm)
<br>[1900-1970](www.census.gov/data/tables/time-series/demo/popest/pre-1980-national.html)  
</p>

Children's Bureau
Montclair NJ, Baltimore MD, Waterbury CT, Johnstown PA, Manchester NH, Brockton MA, NewBedford MA  
Also Pittsburgh 1920, Memphis

Duncan BS, Duke E. 1917. Infant mortality: Results of a field study in Manchester, N.H. based in births in one year. Washington, DC: U.S. Government Printing Office, 134 pp. (Children's Bureau publication; no. 20; Infant mortality series; no. 6)


<p>Mortality Statistics

1906 onward has infant deaths for large cities 

1909 Table2 pdf468-   T2 doesn't have rural totals?
1910 Table 3 pp204    pdf195-242   1910 has urb/rur breakdown



1900-1904 1900 Table 8   pdf  308-349    1902 Tab 2 death/age  532-549      Tab 8 deaths/age by cause CITIES

1910-1920 Table IV pp428-   (pdf426-) 1910 and 1920 death rate per 100K enumerated population by age groups u1 1-4 u5 5-9 etc  MAYBE can back out IMR estimates from these?  pdf 426-27, 454-55, 484-85,     
PAGES  512-13, 540-41, 568-69 (pdf566) Pittsb RI SC, TN UT VT VA WA WI    
 (pdf is 2 less)

1920 Table 8 deaths by age (u1, 1, 2 ..., 5-9); Table 9 cities; 

</p>

<p> **Birth Statistics for the BRA**    

[Maybe a full set](https://catalog.hathitrust.org/Record/003923081) at HathiTrust

[1915](https://babel.hathitrust.org/cgi/pt?id=uiug.30112051430939&view=1up&seq=9) [1916](https://babel.hathitrust.org/cgi/pt?id=hvd.li4xnm&view=1up&seq=5), IMRs pdf 8-17 
[1917](https://babel.hathitrust.org/cgi/pt?id=hvd.li4xnn&view=1up&seq=5) has link to Google books for download.   pdf 28-61 (in digLib)

1918 pdf44-75 for Table 1   1919 pdf 42-61

[1921](https://babel.hathitrust.org/cgi/pt?id=uiug.30112002972542&view=1up&seq=7)   [1922](https://babel.hathitrust.org/cgi/pt?id=uiug.30112051430954&view=1up&seq=9)

1919  Table 1 "rural" excludes municipalities 10K+ in 1910;   66p61 Table III  -76p71 Table IV    


1926 Table 1 pdf -20
1927 Table 1 pdf349-354   (pdf has 2 vols, 1926 & 1927)
[1928](https://babel.hathitrust.org/cgi/pt?id=uiug.30112002972575&view=1up&seq=7) Tab 1 pdf 55-
[1929](https://babel.hathitrust.org/cgi/pt?id=uiuo.ark:/13960/t3521c56x&view=1up&seq=27&size=150) Downloaded. Table 1 pdf 53-59

[1931](https://www.cdc.gov/nchs/data/vsushistorical/birthstat_1931.pdf) IMRs pdf 51-102

1935 not sure why I'm looking through it ...

<p>[1900-1940 Vital Statistics Data](https://data.nber.org/vital-stats-books/vsrates1900_40.CV.pdf)  IMR Tables 26 to 35. Table 26 IMR by state  But these don't have birth counts? (for GLS weighting)
p572. I'm looking for SRB data -- not Table 53, which gives total births (and IMR data) at various geographic levels. Not Table 50, crude birth rates by month;    </p>

<p>Early on: Bureau of Labor Statistics [Annual Reports](https://fraser.stlouisfed.org/title/bulletin-united-states-bureau-labor-3943?browse=1890s#477578) have city-level deaths by causes (these found via Cain & Rotella (2001)). But they lack age-specific deaths.  
</p><p>But there are death-by-age in Registration cities for 1900 (census year, in Census Reports, Volume IV, Vital Statistics, Part II, [Statistics of Deaths](https://www.cdc.gov/nchs/data/vsushistorical/vsush_1900_4.pdf)); I pdf-save Table 5 23-55   pp21-53


#### CDC "Births:Final Data for 20xx ####

annual [Health](https://www.cdc.gov/nchs/hus/previous.htm
https://search.cdc.gov/search/index.html?query=%22sex%20ratio%22&sitelimit=NCHS&exact=sex%20ratio%20at%20birth#results) reports.

https://www.cdc.gov/nchs/products/vsus/vsus_1980_2003.htm
vital stats don't have births by sex

[National Vital Statistics  Reports](<https://www.cdc.gov/nchs/products/nvsr.htm>). (Births)
Most recent (as of 2020 May) seems to be 2018 (SBRs  1.046all 1.052white 1.029black 1.063Asian 1.036Hispanic 1.036Amerind/Alaska 1.022PacficIsle). Looking for SRB discussion later than 2001 report (not 2018, 2015,  YES: 2005 noting downward trend 1970s to 2002 -- citing Mathews&Hamilton (2005 CDC)

Mathews&Hamilton (2005 CDC) [Trend analysis of sex ratio at birth in the United States](<https://www.cdc.gov/nchs/data/nvsr/nvsr53/nvsr53_20.pdf>). Quick read by Jim indicates they don't place a welfare interpretation on the declining SBR 1970s to 2000 ...  1.050  "In 2002 the sex ratio reported for fetal loss was higher than for live births (1,128 compared with 1,048)" 1.0763 -- CDC data

Matin, Hamilton, et al. [Births 2001 (CDC 2002)](<https://data.nber.org/natality/2001/docs/nvsr51_02.pdf>). p8 1046 p9 .... 

CDC Deaths 2017 Infant mortality 

Bell&Miller Life Tables, Table 6 is "Period Life Tables" and 1900 has male e0x 46.41 (p26); Table 7 is "Cohort Life Tables" and 1900 has e0x (p89) 51.52 


#### State of Mass

##### U5 populations by sex in Mass 

US census volumes and data-sets for 1860-1970 at 10-year intervals; Mass State Census for 1865-1915 at 10-year intervals. 1925-1965? (2021Oct26): not 1925 1935  1945 1965.      
Some in 1955, Table 16, p 108

<p>Mass [state cenuses](https://archives.lib.state.ma.us/handle/2452/122027/browse?type=dateissued) of 1865-1915 have u5 pop by sex. Not so: 1925 

[1855 MASS census](https://archives.lib.state.ma.us/handle/2452/122030) Table 2 (64-97 -119) gives totals in age-groups, but not by sex.  p222 discusses sex. Jim cannot find any sex/age data here. 

[1865 MASS census](https://archives.lib.state.ma.us/handle/2452/122031) has age/sex
</p>

##### Mass IMR 

Haines (1998:231) Unfortunately, collection of vital statistics was left to individual states and municipalities, which resulted in tardy and uneven coverage. Massachusetts was the first to begin this activity at the state level in 1842 and achieved relatively good coverage by about 1855 (Abbott, 1897:714-715). 

Abbott 1897:714 The period of forty years (1856–95) has been selected for consideration for the reason that it presents a definite portion of time in which the returns of vital statistics of the cities and towns may be deemed to be fairly accurate. The returns of the first few years following 1842 are more or less incomplete and untrustworthy, but those of the forty years under consideration must be considered as approximately correct.

<br> Note: arguably, the rural data are perhaps not "deemed to be fairly accurate" ?

Haines (2006 HSUS essay) The Massachusetts data reach reasonable quality by about 1860 and are reproduced here in Tables Ab928 and Ab1048–1058.


<p>Mass Vital Statistics [Annual Reports](https://archives.lib.state.ma.us/handle/2452/39847)
[By date?](https://archives.lib.state.ma.us/handle/2452/39847/browse?type=dateissued)  I started to check 1890 versus 1885 and 1895, but realized Mass 1890 looks fine ...</p>

<p> [searched Mortality](https://archives.lib.state.ma.us/discover?filtertype_1=dateIssued&filter_relational_operator_1=contains&filter_1=1901&submit_apply_filter=&query=Mortality&scope=2452%2F39847)  And then use advanced filters to get date desired (issue date 1900 gives rpeort  of 1900 )

[1842-1899 Mortality etc](https://archives.lib.state.ma.us/discover?query=Mortality&scope=2452/39847&filtertype_0=title&filter_relational_operator_0=contains&filter_0=&filtertype=dateIssued&filter_relational_operator=equals&filter=%5B1842+TO+1899%5D)


1859 births 20 xx   stillbirths xxvi  deaths 42? 44? 54?  xxxiv (pdf132)
1860 xxiv ; 1861   xxxiv   (births pdf 100 p xx)     
    1862 xxxiv pdf111 for u1 m/f deaths


1865  6? 10?    p29    clii -- 10  year sum 

1876 pdf56p42 gives 10yrs of births and u1 deaths for Mass  cxlvi ? deaths by age

1889  24 year totals p198 deaths p185 births

1898 1899  2, 34
1900     34 (pdf46)

1914 has births 1866 forward pdf194 p180 
1915 TOCpdf8 deaths 130-31


<p>[city codes](https://usa.ipums.org/usa-action/variables/CITY#codes_section) 
Boston 0810    NewYork 4610 (Brooklyn 4611)  Phil 5330 (1850: 5331-35)  Chicago 1190
   Baltimore 530   NewOrleans 4570  Cleveland 1330    Detroit  1750     <br>
[State Codes](https://usa.ipums.org/usa-action/variables/STATEICP#codes_section)</p>

<p>Life Table [2005](https://pubmed.ncbi.nlm.nih.gov/20578408/) 

[1961 Vital Stats](https://www.cdc.gov/nchs/data/vsus/vsus_1961_1.pdf) live-births by sex, 1-28, pdf 
1962 t15 pdf       pg 1-30 pdf38 by state

<br> 20th C sources   
[1992 Vital Stats](https://www.cdc.gov/nchs/data/vsus/mort92_2a.pdf) for HSUS IMR 1915 on. pdf p507 </p>


<p>[1950](https://www.cdc.gov/nchs/data/vsus/vsus_1950_1.pdf) p81 (pdf 91) offers SRB for 1935-1950, for all/white/nonwhite.  E.g. 1940 white 106.0    But I worry Southern whites tend to inflate the national average?
</p>

<p> For 1930, Birth, Stillbirth, and Infant Mortality Statistics for the Birth Registration Area, [1930](https://www.google.ca/books/edition/Birth_Stillbirth_and_Infant_Mortality_St/yM3cOoJMf2UC?hl=en&gbpv=0) (difficult to find, I downloaded from GoogleBooks). For 1931 we have both the B-SB-IM-BRA and Mortality Statistics, and they give same u1 death count for Illinois (which serves to confirm same data, for me)

  -17 Stillbirths; Tables 18-20 cover whole BRA;   
  
Table 21 give State-level deaths by causes, and by ages (u1day, 1, 2, 3-6 days, 1wk etc)

Table 22 gives States' total/cities/incorps/rural with >10K and >2.5k as cutoffs.  And deaths are by sex. 

Table 23 has that same 3-way breakdown, for deaths by days/weeks/months




<p> [Mortality Rates 1910-1920](https://www.cdc.gov/nchs/data/vsushistorical/mortrates_1910-1920.pdf)  438pdf436 Calif influenza. 
<br>[Mort Stats 1931](https://www.cdc.gov/nchs/data/vsushistorical/mortstatsh_1931.pdf) Tab 3 Deaths by age and color 80-90 (pdf 86-95),   

[Mort Stats 1929](https://www.cdc.gov/nchs/data/vsushistorical/mortstatsh_1929.pdf) Tab 3 108-116  (pdf 110-118).    
Tab4 States, u1 1to4 m/f    
Tab5 deaths by cause (not age)  pp134-
Tab6 causes: state, urb/rur  pp  176
Tab7A causes: by race
Tab8 causes: by age, for states
Tab9 causes: by age, for major cities
Tab10A causes: by month for cities
Tab11 by cause, by infant-age, in Houston?

</p>
<p>[Life Tables](), where we see 1920 Registration Area states are a large proportion of population (maybe 80% or more?). I used 1919-21 and 1929-31 from the [1930 Life Tables volume](https://www.cdc.gov/nchs/data/lifetables/life30.pdf)
</p>
<p>1900 census reports vol III; we use table 19  pp  285-555 (pdf 598-868)
<br>
p xiv The registration record was accepted as sufficiently complete and satisfactory in Mass, CT, RI, and NH; certain counties in the state of NY ... cities: Albany, Cohoes, NY (greater), ... and certain counties and cities in the state of NJ ...
<br>In all these areas the mortality schedule was withdrawn from the enumerators. In all others they were directed to report deaths, and their returns ... compared with the reg records. The result of the comparisons, ... indicated that registration was defective in many places where it was supposed to be perfect, a considerable percentage of the deaths reported by the enumerators not being found in the reg record. As the enumerators did not report more than 50 or 60 per cent of the deaths, the presumption is strong that the omissions in the registration record were even greater than indicated.
<br> tabulated result of the comparison of the two sets of returns [on next page]
<br>xv  xvi Chicago looks not bad: registration record (RR) forms have 93.5 of deaths recorded (the other 6.5% being enumerated deaths not in the RR
<p>CDC weekly [Achievements in Public Health, 1900-1999: Healthier Mothers and Babies](https://www.cdc.gov/mmwr/preview/mmwrhtml/mm4838a2.htm)
</p>
<p>
These may contain age/sex/race, but odd text files ...
[1980-1989](www.census.gov/data/datasets/time-series/demo/popest/1980s-national.html)
</p>


<p> Except for Mormon's 1850 & 1880, the full-count PUMS are from Ancestry.com  </p>


ICPSR datasets with ages: 1800, 1810, 1820: 0-9;  0-4 (or better) are in 1830, 1840, 1850, 1860,  1930 (Part 27), 1940, 1950, 1960, 1970.  

NOT 1870 5-18,18-44, 21+
NOT 1880 -- can get u10 via 10-14, 15-20, 21+
1890 get u5 via 5-20, 21+  nat-white, for-white, colored
1900 get u5 via m21+ 5-20
NOT 1910 no age/sex
NOT 1920 
1930
Ages NOT in 1870, 1880 (5-17, 10-14, 15-20, 18-44, 21+),
02896-0005-Data.dta 


<p>[2020 all races by age](https://www2.census.gov/programs-surveys/popest/tables/2020/2020-demographic-analysis-estimates/table-1.xlsx) U.S. Census Bureau, Population Division, 2020 Demographic Analysis (December 2020 release).
<br>[2020 tables](https://www.census.gov/data/tables/2020/demo/popest/2020-demographic-analysis-tables.html)
<br>[2010 by age](https://www.census.gov/data/tables/2012/demo/popest/revised-2010-demographic-analysis-estimates.html)
<br>Jim pasted in 2020 and 2010 demog analysis estimates of pop by age/sex/col
<br>[1900 to 1970 Nationals](https://www.census.gov/data/tables/time-series/demo/popest/pre-1980-national.html)
</p>

**2010 and 2000** [2000-2010](https://www.census.gov/data/datasets/time-series/demo/popest/intercensal-2000-2010-national.html)
<br>
Maybe [1990-2019](https://wonder.cdc.gov/controller/datarequest/D163)
<br>
maybe [2000-2010 Intercensal](https://www.census.gov/data/tables/time-series/demo/popest/intercensal-2000-2010-national.html)

maybe [State Intercensal Datasets: 2000-2010](https://www.census.gov/data/datasets/time-series/demo/popest/intercensal-2000-2010-state.html)

NOT 2000 state-volumes "Summary Population and Housing Characteristics" e.g. [Rhode Isle](https://www.census.gov/prod/cen2000/phc-1-41.pdf)  not single years of age. PHC-1-41 is not what we're after (but does have U5)

Not useful: [1990-2000](www.census.gov/data/datasets/time-series/demo/popest/intercensal-1990-2000-national.html)

[Census of Population and Housing, Decennial Pubs?](https://www.census.gov/prod/www/decennial.html)
<p>
[*Publications grouped the census Decennial*](https://www.census.gov/programs-surveys/decennial-census/decade.html)</p>
**2000**  For NYC I find [Total Population by Single Years of Age and Sex - 2000](https://www1.nyc.gov/assets/planning/download/office/data-maps/nyc-population/census2000/sf1p6a6i.xls)<br>
2000 PHC-1 u5 ages; PHC-2 no age-data; PHC-3 no age data; DP-1 u5; Briefs NO; Profile NO;

**1990** [1990 Census of Population, General Population Characteristics, United States](https://www2.census.gov/library/publications/decennial/1990/cp-1/cp-1-1.pdf)
States 262a-g Northeast metro/not etc tables 64, 65 <br>
cities in tabs 61-63?
<br>[PA 1990](https://www2.census.gov/library/publications/decennial/1990/cp-1/cp-1-40-1.pdf). Table 17 for urban/rural. Phil is part 2 (I printed the page)br
[1990 states](https://www2.census.gov/library/publications/decennial/1990/cp-1/)  10DC 11FL 12GA  15IL 18Kansas  22Md   26Missi  36ND  38 OK   44 TN   47Vt   50 WVa

**1980** [USA ages](https://www2.census.gov/prod2/decennial/documents/1980/1980censusofpopu8011u_bw.pdf) Page 1-23 Table 41 Single Years of Age by Race, Spanish Origin, and Sex: 1980, in 1980 Census of Population, Volume 1, Ch. B, General Population Characteristics, Part 1, United States Summary<br>
pdf 35-55

[Illinois](https://babel.hathitrust.org/cgi/pt?id=uva.x004451315&view=1up&seq=173&q1=single%20year) at HathiTrust, images 173-
<br>
[NY volume](https://www2.census.gov/prod2/decennial/documents/1980/1980censusofpopu80134unse_bw.pdf)
pdf84 Table 18 p72   pdf111 NYC&NENJ urbanized area <br>
General Population Characteristics, PC80-1-B34, Vol 1, Characteristics of the Pop, Ch B, General Pop Char
<p>
IPUMS has good access to [1980 age volumes](https://usa.ipums.org/usa/voliii/pubdocs/1980/pubvols1980.shtml) <br>
<br>Michigan 1980 [Table 18 pdf 162ish](https://catalog.hathitrust.org/Record/009780899)
<br>But it does not have Illinois Ch B
Chapter 2 (with ages) for PA seems to be missing (looked on Hathi too). Poked around the census directory, looking at pdfs 80134 is NY <br> vol 1
</p> 
<p>Illinois at [Hathi](https://catalog.hathitrust.org/Record/102583049)
<br>[PA ages Tables 18-20](https://www.dropbox.com/s/jzhux09h39clhfz/1980PATabs18-20.pdf?dl=0) extracted from  [Penn Volume](https://www.dropbox.com/s/3nectos2e359yql/PA_1980_Vol1B.pdf?dl=0) downloaded from GoogleBooks.Ca
</p>
**1970** census  [Characteristics of the Population](https://www.census.gov/library/publications/1973/dec/population-volume-1.html) <br> Generally Ch 4 on that webpage (URLs differ)<br>
Table 19 Single Year of Age by Race and Sex p87 negro and negro&other   Table 24 p102 SSMA's Table 17 p85 race by sex -- no ages.

<p>The standard [MASS link](https://usa.ipums.org/usa/resources/voliii/pubdocs/1960/Population/Vol1/37722946v1p23ch3.pdf) is missing the start of Table 16. So we use the detailed [Table 271](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37722946v1p23ch5.pdf).
</p>

[PA ages](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/00496492v1p40s1ch3.pdf) pdf 51 t24 Phila

[NY ages](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_ny1-02.pdf)

[MA ages](https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_ma-01.pdf)

**1960** 
<p>Reconciling Vt data, I find statement (Vol 1, Part 47 Vermont, p xii) that chapter B has complete-count while chapters C and D have 25% sample stats. Eg the U5 totals differ by 3. For [Vermont](https://www.google.ca/books/edition/Census_of_Population_1960/vSabfPk3ERMC?hl=en&gbpv=1), I use google books copy. <br>
MASS is missing p31 or so; I use Google Books version.
</p>

[This directory seems to have the 1960 age data](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/). But Mass is missing the start of Table 16 (p23-31). This 
[page at census.gov](https://www.census.gov/library/publications/1961/dec/population-vol-01.html) has some valid links. But GA is missing -- maybe ok via write in URL at https://www2.census.gov/library/publications/decennial/1960/population-volume-1/
DC 10  FL 11 GA12 . Some are like GA: [12-d is Georgia](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-12-d.pdf). But others are like [NC, which is p35ch3](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/06586188v1p35ch3.pdf)
And then the 1960 census page has a valid link to [SC](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37749999v1p42ch3.pdf)

[only some via IPUMS](https://usa.ipums.org/usa/voliii/pubdocs/1960/pubvols1960.shtml) CT For any state, use its Population Vol 1, section 3, general pop characteristics.

census [Vol 1](https://www.census.gov/library/publications/1961/dec/population-vol-01.html)
col-01-01-k 
[Table 156 Single years of age, by nativity, color, and sex, for the US, urb &  rural](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-01-h.pdf)

Table 232 single years of age, by color and sex, for regions, 1960 p612   Vol 1 states or cities lack single year, lack age-group

1960 Vital Statistics [Vol 1 Natality,](https://www.cdc.gov/nchs/data/vsus/nat60_1.pdf) SRB by state 1-27   Also, p 1-9 for national SRB white 1.055  nonwhite 1.018     2-4 Live births by specified race and sex: US and States pdf54


Vol 1, Pt 2, for each State.  Single years : Tables 94, 95, 101, 102.  Cities: age groups 20, 96
[Mass](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37722946v1p23ch5.pdf)
Mass Table 16 (pdf p9) white female U1 52,822 but Table 94 52,940

[NY](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/37749573v1p34ch3.pdf) 
Table 16 Age by color and sex ... pdf p10
Table 20 pdf44 for NYC  

[PA](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/17216604v1p40ch07.pdf)
table 94 single year of age, state; color (white/nonwhite)

ILL [Tables 13-19](https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-15-e.pdf) in the directory as vol-01-15-e   15-c is Number of Inhabs    15-e includes age/sex color single year

1960 PE11XLS  single year, white/black/other


1960 The table presented here is a preprint of table 65 from Final Report PC(l)-1C, which contains summary information on these and other general social and economic characteristics of the population.

This report presents statistics on age by sex and color for the urban, rural-nonfarm, and rural-farm population of the United States.


[**1950** US Census](https://www.census.gov/programs-surveys/decennial-census/decade.1950.html) <br>
Age-data from Table 15 in [**Volume 2 for each state**](https://www.census.gov/library/publications/1953/dec/population-vol-02.html). Table 15 groups ages 1&2, we split as 48.5% age 1 (based on sample-evidence in Table 51). Table 15s are in dropbox. 
<br>Table 33 is SSMAs, urban, cities, etc.  <br>
[Penn T33](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/23760756v2p38ch3.pdf) is pdf 2-25
Population Table 95  single year  white/nonwhite  1940; Table 38  u1 1&2 3&4   white/nonwhite, 1940 & 1950; 
Table 39  5-yr ages    white/nonwhite    1880 to 1950


BW: 1950census does not have negro <br>
1950 For U2, we extrapolate on the full count's 1&2 age group by taking 48.5% of them as the age 1 (based on the 20%-sample counts). Maybe 1960 has full-count data for 1950?    Table 33 NY pdf 23-41
using the 20% sample (Table 51)   <br>
Table 51 says 1950 data from 20% sample; says Tab 14,15, 33 are complete count. 


US Census of Pop (via my zip 21983999v2p1 probably Vol 2 Part 1) <br>
Vol I Number of Inhabitants (comprising Series P-A bulletins) <br>
Vol II Characteristics of the Population (comprising Series P-A, P-B, and P-C bulletins) <br>
Vol III Special Reports: ... Nonwhite Pop by Race, <br>
<br>
Population Volume II   ... compruses 54 parts ... 1. US Summary 2. Alabama  ... 21 Mass
Looks like I have Pt 1 -- US Summary. <br>  Pt 32 is NY   [ch3](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/22980932v2p32ch3.pdf) for U1 and 2-yr or 5-yr age and sex <br>
[ch 4](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/22980932v2p32ch4.pdf) Tab 51 for single-year <br>
Part 38 is [PA](https://www2.census.gov/library/publications/decennial/1950/population-volume-2/23760756v2p38.pdf) tables 15, 33
<p>Region single year data Table 146 -- based on 20% sample. NE NC Sou West -- Full count Table 61 -- 5yr groupings. We'll need to tally up states.
</p>
1950 [Vital Statistics](https://www.cdc.gov/nchs/data/vsus/VSUS_1950_1.pdf) 
p81 Registered live births and live births adjusted for underregistration, by race and sex: US, 1935-50
p81 Male births per 1,000 female births, by race: US, 1935-1950 
1950 Vital Stats [Vol 2](https://www.cdc.gov/nchs/data/vsus/VSUS_1950_2.pdf) p187 live births by race & sex, US and states. pdf193 Table 18 page 187  p324

<p>US total for CEA paper, Jim extrapolated from the 1960 black/nonwhite ratios by sex: U2 for ages 0 and 1; Age2to4 for ages 2, 3, 4 (U2 and 2-5) to avoid noise.</p>
Census of Population: 1950, Vol. 2, Tables 94 & 97; Table 94 has sex by single year of age for “White” and for all “Nonwhite”. For our black SR02 in 1950 (100.9), we reduced the nonwhite value by 0.1, based on the difference between the negro and nonwhite sex-ratios for under-age-5 (via Table 97). A 1950 black SR02 of 101.0 results from applying the same correction to the nonwhite SR02 from the spredsheet for 1950 in the National Intercensal Tables: 1900-1990 (released in 2004). </p>
<p> PE-11 has Nonwhite SR2 is 101.1, census has 101.0 </p>



**1940**
<p>Table 1 in [Vol 4](https://www.census.gov/library/publications/1943/dec/population-vol-4.html) has ages. Page 4 has light discussion of under-enumeration of infants. States are in groups, within which there are city-data. E.g. For Philadelphia, see pdf35, p206 [Table 2](https://www2.census.gov/library/publications/decennial/1940/population-volume-4/33973538v4p4ch3.pdf).
<br>[1940 NY](https://www2.census.gov/library/publications/decennial/1940/population-volume-4/33973538v4p3ch6.pdf). 33973538v4p2ch3.pdf Arkansas
</p><p> USA 1940  98.9 if we use the PE-11 XLS (2004) SR2 adjusted for Black vs Nonwhite for 99.0-0.1     
<br>2004 PE-11 release for 1940 nonwhite has SR1 98.4  SR1-2 99.5 suggesting heaping    
<br>1940 census  has u1 and u5 negro  and more detailed for nonwhite. From that
<br>   negro vs nonwhite  U1 -0.13     U5 99.1 vs 99.2
<br> I ADJUST 1940 NONWHITE U2 DOWN BY .1 FROM 99.0 to 98.9     BUT see PAPER for latest version
<br> Looking for 1940 U5 by state or division v2 pt 1 Table 26 p59
</p>
<p>
[**1930**](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1930.html)
<br>See Vol 2 Ch 10 pdf 111 for Illinois
[1930 Vol 2](https://www2.census.gov/library/publications/decennial/1930/population-volume-2/16440598v2ch11.pdf) for ages, pp674-690  pdf 112-128
<br>
SR2 census negro 98.4  nonwhite 98.6    PE-11 nonwhite 98.6
<br> Vol III has state-level data, including urban/rural u5 age/sex; also 1920 u5 age/sex (and % splits for rural vs urban, but too imprecise)
<br> 
v3p1 TOC pdf   
pdf44p594 Table 3 age/sex rural/urban
pdf50 p600 Table 11    
Table 11 County-level  u1 u5, all/native white/foreign-born white/negro     
Table 12 Cities  pdf58-63    
Table 10 occs



<br>Looking for regional totals: Table 24 has 5yr totals

</p>

1925 NY state census -- no age data presented.


<p>

**1920**   [1920](https://www.census.gov/library/publications/1922/dec/vol-02-population.html) <br>
Our age data, including single-year for Divisions, found in [Vol 2, ch 3](https://www2.census.gov/library/publications/decennial/1920/volume-2/41084484v2ch03.pdf) pdf20 is p162 Table 9 "Dist by Single Years of Age" for US as a whole,    **pdf29** Table 13 single age  Regions and States (states is 188-285   pdf 46-143) 
<br>[ch 4](https://www2.census.gov/library/publications/decennial/1920/volume-2/41084484v2ch04.pdf) Table 15 has cities with single-year ages

v3 Tables 1 to 13; Table 8 is Ages for cities 
e.g. [Georgia](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch04.pdf)
[Kansas etc.](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch04.pdf)
[NewYork](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch06.pdf)  NYC Ch4 Table 15 pdf10
[Ohio, Penn](https://www2.census.gov/library/publications/decennial/1920/volume-3/41084484v3ch07.pdf) Table 3, e.g. pdf p3 p769  (Ohio) has u1 u5,  
<br> W/B use census, based on small difference and 1910-based doubts of PE11 for older data
DROP IT BY .2 to 98.5
census SR2 negro 98.4  nonwhite 98.6  
PE-11 nonwhite 98.7

**1910**  use [census](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p7.pdf)
census SR2 negro 99.2  nonwhite 99.6     PE-11 SR2 nonwhite says 100.8 with very rounded numbers, so I reject, and stick with census    TABLE 43 has Divisional ages
1910 Pop [Vol 1](https://www.census.gov/library/publications/1913/dec/vol-1-population.html). [Ch 4](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p6.pdf) has single year ages, including  [major cities](https://www2.census.gov/library/publications/decennial/1910/volume-1/volume-1-p7.pdf)
Table 29 is national totals, including the 1910 "negro" values which I found elsewhere. <br>
Table 33 has USA, u5 m/f 1880 1890 1900 1910   Table 41 age periods, states <br>
 Table 43 single year p391 NY
 Table 48 no sex breakdown, u5 by region. Table 49 1910 t50 (100-500k),t51 (500k+),t52,t53,t54 1910
1910 Vol 2 NOT AGES  has state detail, section for each state, Table 1 has state and county
<br>Looked for, and did not find, u5 by sex for previous years.

**1900** Much like 1890, single-year for states (Table 2); age-groups for cities    
vol 1 tables 1-4 NO age data; 
[vol 2](https://www2.census.gov/library/publications/decennial/1900/volume-2/volume-2-p5.pdf) <br>
1900 bulletins 1-60, 61-106
<br>Bulletin 13, "A Discusssion of Age Statistics"
[discussion of age statistics](http://www2.census.gov/prod2/decennial/documents/03322287no13.zip) p18 indicates 1890 ages were "age at nearest birthday" and therefore confusion in 0 1 2 age groups  <br>
To think about: if 11mo olds are rounded up, how does that distort the SR1? It would seem to leave more of the younger, who are more male ... That is a 39 page essay, with attention to sex-ratio evidence rural/city-sizes ...
<br>

**1890** census
<p> Report on the Population of the United States at the Eleventh Census: 1890, Part II (Washington, D.C.: GPO, 1897). Table 1 has US; Table 2 has states, Ages by U1 months and single years (we have it in 2 parts). Table 3 sex by age groups;  Table 4 ages by periods of years of native white; Table 8 Ages by periods of years ... for cities having 25,000 inhab or more </p>
<p>At [older link](https://www.census.gov/prod/www/decennial.html), 
Volume 4: Report on Vital and Social Statistics in the United States<br>
Part 1: Analysis and Tables <br>
Part 2: Cities of 100,000 population and upward (in Jim's digLibrary)<br>
Part 3: Statistics of Deaths<br>
Part 4: Statistics of Deaths<br>
</p>
<p>Volume 4, Part 2, Vital Statistics, Cities of 100,000 pop ... 19610506v4p2.pdf
<br>1890a_v4p2-01.pdf has TOC, shows pop by age/sex/color etc 337-360; 391-408 death rates by ward. 
<br>19610506v4p2ch4.pdf  p2-06.pdf has "General Tables" pp. 335-444; p2-07.pdf for pp445-549 table 5 is continued ;  p2-08.pdf pp550-655 still Table 5 ;
<br>48 cities death rates, u1 231, u5 78; Chicago u1 213  u5 69;  Newark stands out for high u1dr 318 (also DC, via "colored" dr > 490 )
</p><p>Can muscle out city U2 vales -- Chicago U2 103.3 U5 102.3 -- pattern like Illinois, with the SR2 a full point above the SR5 ... 
</p><p>
<br>e.g. p514 Table 1 has u1 u5 for US, states, cities?
<br> volume? is called: 1890 Bulletins  no. 100 Social Statistics of the Cities
</p>


**1880** Vol I, Statistics of the Population ... has single-year ages in Table XXI [Ala-Nevada](https://www2.census.gov/library/publications/decennial/1880/vol-01-population/1880_v1-15.pdf) and [NewHamp-Wyoming](https://www2.census.gov/library/publications/decennial/1880/vol-01-population/1880_v1-16.pdf) 
<br>
VA is pdf33 p636; With enough time, can compile U5 ages for cities,
1880 city ages in [vol 12](https://www.census.gov/library/publications/1885/dec/vol-11-12-mortality.html) <br>
Ages u1 & 1to5 [Vol 12, Table XIII](https://www2.census.gov/library/publications/decennial/1880/vol-11-12-mortality/1880v12-05.pdf) 

**1875** Mass state census  pdf p141 County of Barnstable       pdf541 occs

[**1870**](https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1870.html) US aggregates in Vol 2 [Table XXII](https://www.dropbox.com/s/dndp8e0uv4nf1vf/1870b-33Vol2TabXXII.pdf?dl=0) <br> [Table XXIII](https://www.census.gov/library/publications/1872/dec/1870b.html) for state-level ages.    Vol 1? tables large age group"ages" is school age, 18+ ;  XXV some large age groups, some cities, but no way to get u5
   City-level data for SRs not found. V1 Tab XXV has school age counts.




1860 state-level ages u1 1-5 (as in ICPSR); so use IPUMS full instead


### US Census for the Black SR1 ###
population volumes from 1850 and 1860 give U1, 1-u5, 5-u10 etc, for Whites, Free Colored Slaves.  Negro Population 1790-1915 Ch 4 provides SR1 for blacks 1850, 1860, 1870, 1900, 1910 and explains that 1880 and 1890 includes "indians, chinese, japanese" with blacks. So we need to extrapolate to fill in -- calculate non-white totals 

1940 can't find negro age 2 -- just nonwhite for single yr

Have nonwhite 1900-2010 ? really

searchable index
https://www2.census.gov/programs-surveys/popest/FTP2_Key.xlsx


https://www2.census.gov/programs-surveys/popest/tables/1900-1980/national/asrh/pe-11-1910.xls

https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.html

<a name="CAN"></a>

### Canada sources

#### Vital Stats for Canada -- Provincial?

Canadian Human Mortality Database [BDLC](http://www.bdlc.umontreal.ca/chmd/prov/nbr/nbr.htm)

[Quebec SRB](https://statistique.quebec.ca/en/produit/tableau/births-by-sex-and-sex-ratio-at-birth-quebec)
Canada & provinces [Lifetables 1999-2001](https://www150.statcan.gc.ca/n1/en/pub/84-537-x/2020001/xls/1999-2001_Tbl-eng.xlsx?st=x5IFJWHw)
<p>Canada Life Tables [1980/82 to 2017/19](https://www150.statcan.gc.ca/n1/pub/84-537-x/84-537-x2020001-eng.htm)
</p>
<p>1975-1995 Catalogue [82-003-XPB](https://www150.statcan.gc.ca/n1/pub/82-003-x/1997003/article/3476-eng.pdf) reports IMR from Canadian Vital Statistics Data Base
<br>[1991-2019](https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1310071201)
which is titled Table: 13-10-0712-01 (formerly CANSIM 102-0506) 
Geography: Canada

1861 census Lower Canada deaths unumbered page before [p578](https://www.canadiana.ca/view/oocihm.9_01612/309?r=0&s=4) . Total deaths by cause

</p>

Maybe https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310011401&pickMembers%5B0%5D=1.1&pickMembers%5B1%5D=3.1&pickMembers%5B2%5D=4.3&cubeTimeFrame.startYear=1980+%2F+1982&cubeTimeFrame.endYear=2017+%2F+2019&referencePeriods=19800101%2C20170101

#### Census Sources for Canada

<p>UofT library offers wide range of Can census [online](https://mdl.library.utoronto.ca/collections/numeric-data/census-canada/historical)
</p>

<p>
<br>1851 Que [p208](https://archive.org/details/censusofcana1800cana/page/208/mode/2up); Ontario p184  (NB U6 p224; NS U10 p230; Assiniboin p240 family heads;    
<br>1861 Quebec, Ontario; NB has U6 (not 0 1 etc); Nova Scotia (ages 346) is too small to use as a proxy for the Maritimes.
</p>
2011 and 2016 [tables](https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Index-eng.cfm)
[2011](https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Rp-eng.cfm?TABID=2&LANG=E&APATH=3&DETAIL=0&DIM=0&FL=A&FREE=0&GC=0&GK=0&GRP=1&PID=109523&PRID=10&PTYPE=109445&S=0&SHOWALL=0&SUB=0&Temporal=2016&THEME=115&VID=0&VNAMEE=&VNAMEF=)     
[2016](https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Rp-eng.cfm?TABID=2&LANG=E&APATH=3&DETAIL=0&DIM=0&FL=A&FREE=0&GC=01&GK=1&GRP=1&PID=109523&PRID=10&PTYPE=109445&S=0&SHOWALL=0&SUB=0&Temporal=2016&THEME=115&VID=0&VNAMEE=&VNAMEF=)
<p>UofT site lists various  **1861 and 1851** census volumes. Volume 4 of 1870 has previous census data. Eg [NS 1851 pages](https://archive.org/details/censusofcana1800cana/page/234/mode/2up?view=theater) with U10 (nothing finer). 1851 NB in 1871 has U6. 
<br>Pg 278 starts Lower Canada (Quebec); Pg 292 is the start of single-year ages;
<br>Page 252 of that volume starts Ontario (Upper Canada) 1860-61 and [p260 has single years](https://archive.org/details/censusofcana1800cana/page/260/mode/2up). 
<br>p330 is NewBrunswick
<br>
Newfoundland U10 (nothing finer), p245.
</p>
<p>
[1871](https://archive.org/details/censusofcanada05cana/page/46/mode/2up) Table F in Vol V (vol III is industry, shipping etc.).
</p>
[1881](https://www.canadiana.ca/view/oocihm.9_08062/32?r=0&s=1)     
[1891](https://www.canadiana.ca/view/oocihm.9_08071/5?r=0&s=1) Vol II has U5 singles ages<br>  [1901 vol IV](https://archive.org/details/1901981901FV41906engfra/page/n39/mode/2up)   <br>
1921 [vol II](https://archive.org/details/1921981921FV21925engfra) U5 single years by province for 1881-1921! <br>
1931 in dropbox<br>[1931 ages](https://archive.org/details/1931981931FV31935engfra)<br>
Vol 1 p195 refers to age-heaping and problems of single-year data. Mentions MacLean, [The Age Distribution of the Canadian People, 1931 Census Monograph](https://archive.org/details/1931981931CM21940eng)
<br>Table 9 has U1 and 1-4 by province, at censuses 1881-1931; Table 11 has 1931 Canada single yrs of age<br>
Vol 3 has some single-year of age data. Tables 6-10.<br>
[1941](https://archive.org/details/1941981941fv31946engfra/page/n31/mode/2up) data also at StatsCan, e.g. [Ontario](https://archive.org/details/1941981941M2C51941engfra/page/n55/mode/2up)  <br>1941 Fourth Census of Canada, 1901. Vol. IV, Vital statistics, school etc. <br>
Table 11 age groups;
[1951](https://archive.org/details/1951981951FV21953engfra/page/n17/mode/2up) Appendix A p1002
<br>1951 U5 single-year ages are inferred from census & birth/death registration and immigrants U4
<br>
[1961](https://archive.org/details/1961925431962engfra) Note that U4 single-year is inferred from birth/death registrations and U4 immigration. Interesting that Maritimes U5 looks good and U2 does not -- suspicious of the inferential process <br>
[1971](https://ia800607.us.archive.org/20/items/1971927161973engfra/1971927161973engfra.pdf) in Dropbox digLib<br>
[1981](http://archive.org/details/19819290%7D11982engfra) <br>
[1991](https://ia802902.us.archive.org/32/items/1991933101992engfra/1991933101992engfra.pdf)
[online](https://www12.statcan.gc.ca/English/census91/data/tables/Rp-eng.cfm?LANG=E&APATH=3&DETAIL=1&DIM=0&FL=A&FREE=1&GC=0&GID=0&GK=0&GRP=1&PID=71935&PRID=0&PTYPE=4&S=0&SHOWALL=No&SUB=0&Temporal=1991&THEME=101&VID=0&VNAMEE=&VNAMEF=)
[2001](https://www12.statcan.gc.ca/English/census01/products/standard/themes/Rp-eng.cfm?LANG=E&APATH=3&DETAIL=1&DIM=0&FL=A&FREE=1&GC=0&GID=0&GK=0&GRP=1&PID=55434&PRID=0&PTYPE=55430&S=0&SHOWALL=No&SUB=0&Temporal=2006&THEME=37&VID=0&VNAMEE=&VNAMEF=)
<br>  
1871 U2 Canada 103.9  Ont 104.2   Que 102.7   NB 106.5 NS 105.0 (NB NS each <22k)  <br>
1881 U2 Canada 103.9  Ont 104.5   Que 102.7   NB 105.3 NS 105.4      Toronto 104.2     Montreal 97.1 <br>
1941 U2 Canada 103.4  Ont 103.5   Que 103.1   NB 103.2 NS 102.3      Toronto 102.9     Montreal 102.5 <br>
1961 U2 Canada 104.7  Ont 105.1   Que 105.0   NB   <br>
1971 U2 Canada 104.9  Ont 104.4   Que 105.2 &nbsp;&nbsp;________ Alberta 105.6 BC 104.8
<br>
2016 U2 Canada 104.9  Ont 105.0  Que 104.5 
<br>  
UofT library offers wide range of Can census [online](https://mdl.library.utoronto.ca/collections/numeric-data/census-canada/historical)
censuses up to 1871 in one volume [online](https://archive.org/stream/censusofcana1800cana#page/252/mode/2up) or [in my dropbox](https://www.dropbox.com/s/z1kfsls00p3un32/censusofcana1800cana.pdf?dl=0).  422 1861 Lower Can   1869 Nwfld  1870 BC  477 Manitoba   491, 499 PEI
 Censuses [1851 to 1871](https://archive.org/details/censusofcanada05cana/page/2/mode/2up)

[1861](https://www.canadiana.ca/view/oocihm.9_01612/4?r=0&s=1) No 5 & 6 is ages, 

Statistics Canada pubs at Internet Archive [1941](https://archive.org/details/statisticscanada?&and[]=year%3A%221941%22)




<a name="UKIre"></a>
## England, Scotland, Ireland Data & Results ##


### England, Scotland, Ireland ###

<p>
On SRB in England 1880, from [Plowden's Report on the census of India ... 1881](https://catalog.hathitrust.org/Record/012155211)  (1883 p. 53)  <br>Plowden (India 1881) pdf  1623   In England they do not even publish in any detail the age figures as recorded, but doctor them, sometimes to the extent of 5 per cent., before using or printing them.*   * See Census Report of England and Wales, 1871, Vol. IV., p. 46, and XI
</p>

### Scotland

HMD offers age/sex data from 1855 -- probably their description of 1855-60 is relevant
"Population estimates for the period 1855-1860 are pre-censal population estimates calculated according to the HMD methodology (assuming zero net-migration)." 
    HMD sex-ratios are very close to census values (usually 0.1 less feminine than census; biggest discrepency is 1861's 0.3 less feminine).

HMD says The compulsory registration of births began on July 1st, 1837. However, according to the U.K. Office for National Statistics (ONS) birth registration was incomplete until 1874. Therefore, the quality of the data for 1855-1875 is assumed to be lower than in later years and should be used with caution.

Mitchell has IMR from 1855 

Scotland,  Births (1-year)	Last modified: 10 Jul 2020;  Methods Protocol: v6 (2017)
Scotland, Deaths (period 1x1), 	Last modified: 10 Jul 2020;  Methods Protocol: v6 (2017)
Use R to check the births/deaths ... 

Scotland 1851 is with England. 

SR5 values in HMD versus the census.  1861-1911 HMD a little less feminine.    
1861 HMD is 0.3 less feminine; 1871 is 0.1 less femin; 1881 is 0.2 less femin; 1891, 1901, 1911 are all 0.1 less femin.    

By either source, census or HMD, SR5-wise, 1901 & 1911 look less healthy (101.3-101.5) versus the 1861-1891 values (103.3    102.7   102.5  103.0) 

1861 the HMD u5 count is 0.5% above the census; HMD SR5 is 0.3 points less feminine. So the HMD SR5 looks healthier the census value. PUMS is full-count; it is 0.1 points less feminine thant the census (96.7 vs 96.8)

[Census of Scotland -- 1861](https://catalog.hathitrust.org/Record/008879851), Population Tables and Report.    [page xxii](https://www.dropbox.com/s/wix21p9xu99mi9m/Scotland1861xii.pdf?dl=0) has a great quotation about SBR 106 and the frail male "At birth 106 males appear for every 100 females ...; yet, by the law of nature, -- a law seen in still more powerful operation even in intra uterine life -- the tendency to succumb under disease is so much greater in the male than in the female, that by about the 18th year of life the proportion of the sexes becomes equalized, 100 males being alive at that age for every 100 females"       
Citation: Census of Scotland -- 1861, Population Tables and Report (Number of the inhabitants, families, children at school, houses, ... ), Edinburgh 1862.     
That volume does not have the age data.

Scotland 1861 [age table](https://www.dropbox.com/s/r8w9j9y521809yw/Scotland1861ages.png?dl=0). The text with the table says "the ages of only 2695 persons, consisting of 2467 men and 228 women, were not ascertained. The great majority ... consisted of seamen on board ... vessels ... round the coast." Table title includes "The Ages not ascertained distributed among the others." It is NOT the case that unspecified ages are simply distributed among all ages, in which case the m/f ratio of kids would be somewhat inflated: u5 SR would feminize by 0.2 points. Comparison of Table 1 to Ages table in Volume 2 shows u5 ages are not augmented, those e.g. 30-35 are.

[1861 at GoogleBooks](https://books.google.ca/books?id=ng8TAQAAMAAJ&dq=Scotland+1861+census+volumes&source=gbs_navlinks_s)  p xi says of Table 1 "the persons whose ages were not ascertained are distributed among the classified ages according to the periods of life to which they most probably belonged; "     
Table 1 u1m 46055 m30-35 90,975  f30-35 111,570   95-100 109 250
Vol2p1 u1m 46055  m30-35 90,665  f30-35 111,543   95-100 109 250



1871 Census u5 count is 0.9% below the HMD value; the census SR5 is 0.1 more female than the HMD (97.40 vs 97.31).     

Ages Census of Scotland, 1871, Eighth decennial census of the population of Scotland taken 3d April 1871, with report. Vol. II.    BPP 1873 LXXIII [C.841]    xii     
p xiv Table 3 is a little inconsistent with the Table 1 values. Table 3 says U5 has 97.3 female per 100 males, and it lists u5 proportions as 50.656 and 49.344 but the Table 1 values give values 97.4 fems per 100 males, and 50.658 and 49.342 -- so Table 3 reflects some rough figuring (97.3 says less fems, 49.344 says more fems).  

Table 3 reports for 1871 England: 99.8 female to every 100 males.     

p xv "105.4 males are brought into the world in Scotland for every 100 females.  ... But whatever the case with other countries, it happens in Scotland that males are so much more difficult to rear than females, that by the time the 17th year of life is arrived at, the excess of males has died off, leaving but one male for every female." Census of Scotland, 1871, Eighth decennial census of the population of Scotland taken 3d April 1871, with report. Vol. II.    BPP 1873 LXXIII [C.841]    xv (page image dropboxed)



1901 ages are given in 1911 vol II (along with 1911 ages). The census is 0.1 more feminine than the HMD.

1901 Census vol III is occupations (see GoogleBooks)

1911 Census vol II has ages.  

1931 ages Census of Scotland, 1931, Vol. II Populations, ages and conjugal conditions, birthplaces, Gaelic speaking and housing    BPP 1933  [n/a]    79

Census 1981, Scotland : historic tables, 1801-1981; Age u15 1861 on -- too broad for us.


### Ireland Census

#### Ireland Census 1841
Report of the Comm ... Census of Ireland for the Year 1841 [At Hathi](https://catalog.hathitrust.org/Record/001306972) or our copy (in SSMM).  
Note: for illiteracy work, commsnrs p. xxxiv males age 56-65 194,079 40% read&write, 12% read, 48% neither ;   

For Provinces rural/urban SR1, need to add up 12m from County Level Data 

88 lxxx  expectation of life at each year (and maybe basis for IMR?)
91 lxxxiii  m & f at each age in rural and civic, equated from the general table of ages. Collapses all under 2 into  "1 and under" and those totals match the raw.

101unnum  County Tables
102unnum  Province of Leinster  103 Carlow
104p2 County of Carlow   Area Persons Houses Families
117unnum City of Dublin  
255unnum Prov Munster
267p166 City of Cork
293p192 Co Cork
388p288 Town of Belfast
457unnum Summary of the Province of Ulster 458p358
462p362  Ulster rural/civic by 4-month age-range, 2-5, 5-8, etc  I went county by county to get 1-year olds  

465unnum Province of Connaught 466unnum Galway 
527p428 Prov of Connaught Summary

533p434 civic is towns containing 2000 persons and upwards
535p436 cities and towns (pop, etc)
537p438 Ireland rural/civic by 3-month age, etc

587p488 raw pop by sex and one-year-age for Ireland and Provinces 
 check vs rur/civ breakdowns, using age 2 males 
587  Ire 117753        Leinster 26239  Munster 35297
     91  Ire         103270+14483=
589 Tables of Deaths


#### Ireland Census 1851

75p10 Ci Dublin I ages u1 1-u5 5-u10   .... 20-u30 ... 60+
79p14 Co Dublin II  read,write, school
220p158 Galway I ages u1 1-u5 5-u10 etc
250p188 Ireland civic/rural by month and by single-year

#### Ireland Census 1861

1861 census gives 1851 & 1861 U1 and 1-4 ... 

#### Ireland Census 1881
Part 1 Area, Houses, and Pop; also the ages, civil or conjugal ...
 Leinster (we have PDF) 1197p1183
Vol IV Connaught 13p621 age by year to 5
We have PDFs of Province summarries, from ProQuest (Js Columbia)

#### Ireland Census 1891

General report, Ireland, 1891
Table 78. Showing the number of males and females in 1881 and 1891, under 1 year, 1 year and under 5, and in quinquennial period

Part 1, Area, houses, and population, Vol. I Leinster
vII Munster
vIII Ulster

Maybe http://www.histpop.org/ohpr/servlet/TOC?path=Browse/Census%20(by%20date)/1891/Ireland&active=yes&mno=439&tocstate=expand&tocseq=37200&display=sections&display=tables&display=pagetitles

### England Census

#### England Census 1881
page v Table 




#### Time-series for England and Wales

Infant Mortality Rate 1900-2019 from ONS Dataset [Vital statistics in the UK: births, deaths and marriages](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/vitalstatisticspopulationandhealthreferencetables/current/vitalstatsannualreferencetable20201.xlsx)


Our british estimates: we accept 1901 forward from
[S92 NatArchives Database](https://discovery.nationalarchives.gov.uk/details/r/C11521415). That 1901 value is 100.1 and we extrapolate back, based on the 1911 census Table 43, back from 1901 to 1861. CLRIFY THIS: 1911 census has 102.2 (graduated) and 102.1 (Table 43), both close to the S92 value of 102.0;  1901 value of 100.5 (1911Tab43,1901Tab16) 1901 census has 100.6 as the graduated estimate, 100.5 as the value Tab16 via fems/thousand males age 0, in 1901 and 1911 census.  
1861 PUMS 101.2; 1861 volumes have 100.7; 1911/1901 101.5 Notion that 1861 misses boys ...  1851 estimated midyear is 100.7 vs 1861's ; We extrapolate via 1861 1851 1841 (risk overstating 1841, but it is so low, we can accept?)  
1851 and 1841 will be extrapolates from 1861. 


#### Britain 1901-2018 (official UK stats) ####
Official UK stats, annually from ONS/National Archive RG 69 [Historic Mortality: 1901-1992](https://discovery.nationalarchives.gov.uk/details/r/C11521415)^[Also [ONS data 1961-2018](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/adhocs/10727populationestimatesanddeathsbysingleyearofageforenglandandwalesandtheuk1961to2018/ewuksyoadeathspopdata19612018.xlsx), (found at ons.gov.uk search for " Population estimates by single year of age". Also can see 1998, 2008, 2018 data uk population pyramid interactive.]   

Scotland sex by age via [pyramid xls](https://www.nrscotland.gov.uk/files//statistics/population-projections/2018-based/2018-based-scotpop-pyramid-18-based.xlsm)
age-heap 2001

Also, [HistPop](http://www.histpop.org) has census data fairly conveniently (although it is often busy); might want to look at it compared to the "official" stats?

Note that the 1931 census gives SR1 102.8 while RG69 gives 103.2 (1930 102)

#### Britain before 1902####
Three main "sources" (the first Brit & Ireland only): [Histpop-The Online Historical Population Reports Website](http://www.histpop.org); Hathitrust; GoogleBooks.    
Age/sex tables in Census of England and Wales 1901 [General report](https://catalog.hathitrust.org/Record/100424194) with appendices (Harvard library's copy).^[Not in Hathi Census of England and Wales. 1901. Summary tables. Area, houses and population; ...]  
Compilation error is explained pp. 47-48 (Hathi images 63-64).^[Same source at histpop, in the essays, about pg 3 of them (the one for 1901?)]. Table 16 (p. 209; Hathi 227) offers females per thousand males at 1861 1871 1881 1891 1901 "based on the enumerated numbers at the several Censuses, revised by taking into account the births and deaths in the five years preceding each Census." Table 20 and 21 
(Hathi 230), Graduated Tables. Page 67 (Hathi 83) "Former Graduated Tables have been based on estimates of population at the middle of the Census year ; the Table for 1901 is based on the population actually enumerated. (para) In addition to this Graduated Table for 1901 ( Table 20 ) we have prepared by the same methods a Table for 1891 ( Table 21 ) . This differs from the Table given in the Report on that Census by including the Army, Royal Navy, &c., abroad , and by representing the enumerated population, not the estimated mid-year population, as well as by the methods of calculation employed."  

1882 Annual report of the Registrar-General for England ... v.45 1882 suppl.. pvii Old and New English Life Tables, based upon the Mortality in 1838-54, and in 1871-80


1891  [HistPop](http://www.histpop.org)  
1881 Hathi Cornell  

#### 1871
pdf93 ToC for tables Tab42 ages in towns  
  p46, pdf158p48  estimated ages
p47 Table 45 Estimated pop at each Yr of Age incl Army etc
p48 Table 46 Estimated pop at each Yr of Age excl Army, Navy, Marines, Merch Sea
p49 Table 47 estimates pops, incl army etc

#### 1861 
SR1 for E&W  
Scotland via Histpop --
v3 Hathi -- sr1 for whole country only
Census of Scotland - 1861: Population tables and report. Number of the inhabitants, families, children at school, houses, and rooms ... xxii Fun for 106 female births and for frail male "At birth 106 males appear for every 100 females ...; yet, by the law of nature, -- a law seen in still more powerful operation even in intra uterine life -- the tendency to succumb under disease is so much greater in the male than in the female, that by about the 18th year of life the proportion of the sexes becomes equalized, 100 males being alive at that age for every 100 females"

#### 1851 

[Our copy](https://www.dropbox.com/s/wlx1h29bjn8uq13/1851CensusGBPopTablesIIVol1Table4-clviiEstimated.tif?dl=0). Sourced from HistPop: [Great Britain **Population tables II,** Vol. I.](http://www.histpop.org./ohpr/servlet/PageBrowser?path=Browse/Census%20(by%20geography)/Great%20Britain/1851&active=yes&mno=30&tocstate=expandnew&display=sections&display=tables&display=pagetitles&pageseq=169&zoom=3) England and Wales. Divisions VII-XI. Scotland. Islands, 1851 Table 4 ... Estimated Numbers living at each year of Age.  

Hathi Versions
[Population Tables I, Vol II](https://hdl.handle.net/2027/coo.31924092723471) is listings of numbers of inhabitants 1801 1811 ... 1851. It seems Vol I would be same ? 


Tables II, Vol I, [Pt 1](https://hdl.handle.net/2027/coo.31924092723463) is only 8 pages, all junk.
[Pt 2](https://hdl.handle.net/2027/coo.31924092723471) is Pop Tables I, Vol II.

[Population Tables II. Vol II](https://babel.hathitrust.org/cgi/pt?id=coo.31924092723497&view=1up&seq=13) 

The [1851 Population Tables II Vol II](https://www.google.com/books/edition/Census_of_Great_Britain_1851_Population/VZYyAQAAMAAJ?hl=en&gbpv=0) is on Google books. 

Hathi [Census of GB 1851. Tables Pop & Houses ...](https://catalog.hathitrust.org/Record/001886111)  50 pages Probably same as HistPOP preliminary

Hathi Census of G B 1851 [226 pages](https://catalog.hathitrust.org/Record/004678725) reprinted in condensed form ...  5yr only ... (enum or est?)


London 1841 is given with and without Lewisham and Hempstead -- probably more rural-like, but too small to matter
"Original homelots were not divided up extensively until the 1840s, when enriched by the burgeoning whaling industry, New Londoners began to seek land for dwelling houses in outlying neighborhoods close to the center of town."
From Wikipedia The Official Illustrated Guide to South-Eastern and North and Mid-Kent Railways of June 1863, by George Measom, describes Lewisham as follows: 'Lewisham Station, situated on the slope of an eminence amidst picturesque scenery, beautiful green meadows rising abruptly to the summit of the hill on the left, dotted with handsome residences and gardens, while the Common is seen intersected by various cross roads and studded with country inns and houses on the low ground or valley to the right. The area of the parish is 5,789 acres... Lord of the manor, the Earl of Dartmouth to whom it gives the title Viscount'.  


#### **1841**
 Census results published in 1849 registrar-general report, which gives population by sex and one-year intervals; 1841 abstract table III under5

Reg Gen Report  5th 1843 has life table  ELM 40.17
Contemporary life-tables put Irish life expectancy just under 30 years and English life expectancy over 41 years, with Irish rates of infant mortality about 3.5 percentage points higher (Ireland Census 1841: lxxx; England, Registrar-General 1841: xvii, xix).
 
1841 lxxx rural male 29.58 (fem 28.90) civic 23.99  32%

Parish register abstract, England and Wales, 1841 for baptism numbers. Not Supplment to the 25th, 35th, ... 1891-1900 The Registrar General's Statistical Review of ... 1921 Does not have baptismal counts. Nor does 1845's Sixth annual report of the registrar-general (Registrar-general's edition) 1851 is 14th.

1841 has raw and corrected? 
pdf p13bottom "Note" refers to differences in populations given, arising from boundary changes.

pdf92p87 Part II starts, Populations
England excl military 15884302 incl mil 15914148 (same on pdf237)  
Londo ex mil 1942336 1948369
pdf095p090 Counties-House 1841; and Pop ...
pdf097p092  "" ""   Districts 
pdf122p116 11 Welsh Div - Houses 1841; and Pop. .. Dists 
pdf123p118 1 London - Houses 1841; and Pop 1801-1841 subD 

235p230 Part III tables of m & f   derived from census returns

pdf250 2 S E Div Ages of M & F enumerated ... in Districts 
pdf300 2 S E Div Ages of M & F enumerated ... in Sub-Dists
 pdf350 5 S W Div ....   in Sub-Dists 
pdf400 9 York Div ... in Sub-Dists
pdf425 11 Welsh
434p427 Part IV 
   p428   A comparison of the aggregate pop of Eng as given in the census abstracts, with that now published, will be found at pp 440 and 441  ... 1841   minutely explained SEE PDF 447
Part IV tables of M & f pop of parl counties 1801-1841 and ages 1841
 
 pdf449 p442  Index of Districts


### Prussia

Statistical Results of the last Census of France, Prussia, Austria, Italy, Switzerland, and Belgium, Journal of the Statistical Society of London, Vol. 48, No. 2 (Jun., 1885), pp. 288-297.  LT5

Eurostat 2008-2018  Not historical 

Die Gemeinden und Gutsbezirke des Preussischen Staates und ihre Bevölkerung: Nach den Urmaterialien der allgemeinen Volkszählung vom 1. december 1871 bearb. und zusammengestellt vom Königlichen Statistischen Bureau, Volumes 2-3 Hathi & Google books -- Under10 school stuff

Statistisches Handbuch für den Preussischen Staat. [Band 1. 1888](https://catalog.hathitrust.org/Record/000496591)   5-year age groups    pop by birthplace, by religion,  pdf126p104 m,f 5-year age groups (born 1885-81 1880-76 1871-75 etc)
   pdf304 ships less than 1 year old



<a name="IndiaCensus"></a>

### India Census Data

a huge set of census volumes for South Asia (India, Pakistan, Burma, SriLanka) e.g. [1871](https://www.jstor.org/site/south-asia-open-archives/saoa/census-reports-1871-26318834/?refreqid=excelsior%3A0f947b3954352bdb6fe656029bf6dd43) [1881](https://www.jstor.org/site/south-asia-open-archives/saoa/census-reports-1881-26318833/) and many more via [South Asia Open Archives -- Social and Economic History](https://www.jstor.org/site/south-asia-open-archives/saoa/social-and-economic-history-26289342/)



1871 Mysore SR1 SR1-5 SR6-12   
1881 census "Report" p. 119 Abstract XLVIII shows SR1 SR2 SR3 SR4 SR0-4 SR5-9 SR10-14 for every region  
1891    
1901 [Vol 1A Part 2](https://www.jstor.org/stable/saoa.crl.25352838?seq=1#metadata_info_tab_contents) Good age/sex source, pdf71 pp. 64-102 

#### 1871&1872 census of India
So far, unable to find much of the age data. Have NWProvs, Mysore, Bombay; Plowden (156pp65-66) gives some Bengal ratios and refers to  Appendix D? 


Coorg census -- population is only 168,312

1872 [Bombay Vol 2](https://www.jstor.org/stable/10.2307/saoa.crl.25057641 ) 
pdf14 p13 there is in the whole of British India, ... an excess of 5 1/2 millions of males over females, or nearly 6 per cent.  Physiological reasons have been assigned for this excess ..
hot climate to produce an excess of male births, ... early marriage of the girs, and consequent greater maturity of the husbands.  only apparent, being due either to the omission of females due to the low estimation in which they are held, or to their systematic concealment ... 


NW Provs [Vol 1](https://catalog.hathitrust.org/Record/100157780)   liv comparisons to England, Austria -- where as expected female share of pop increases over young ages  p lvi  the disparity does exist, and is mainly caused by female infanticide 

NW Provs V1 pp2-3  para8. [possibly tropical reversal of female/male vitality and early marriage bad for female life ]  ...

     some other cause is at work to produce so great a numerical inequality of the sexes: and the info so widely collected in late years, together with the fact that females are more numerous among Mahomedans than Hindoos, and among low castes than high castes, have forced Mr.Plowden (p3) to the conclusion that the disparity is mainly due to the wide prevalence of the practice of female infanticide, including in that workd not merely active deprivation of life but also neglect and disregard in the rearing of girls.



1871-72 Memorandum  over/under age 12


1871 Madras Presidency - Supplementary Reports -- 5-year ages
1872 Bombay Presidency - [Detailed Returns of](https://www.jstor.org/stable/saoa.crl.25057642?seq=1#metadata_info_tab_contents)   VolIII 37-72 p22- detailed geog age/sex 0 1-5 etc by religion   LT1 data found, see WK4

Central Provinces HIS DISCUSSION -- consistent with misogynistic mortality there. 
24p21 Section IV Distribution of the population according to sex and age  ... s41 children (12 and under) Central Provinces 52% male which is low -- Bengal 54.5%  NW 54.5% Oudh 54.3%  Berar 53.1%    Argues for liklihood that boys are not undercounted in the LT1 age, that 12-year-old girls likely reported as older (so they can be married off?), but not enough to explain low SR in the 12-20 group  s42 quotes 1865 NW Prov Report "the opinions of the Hindus in regard to females exercise and unfavourable influence on female mortality in the earlier years of life, but this influence is quite insufficent to account for the vast difference which is to be found in the proportion of the sexes in this country compared with others."  TENTATIVE SUM-UP is his p22 claim  "to the superior vitality of males is the preponderance of the male sex due."   

Census of the NW Provinces, 1872.  Part III Sex Statistics
v1 21toc VI pop by sex Tables L I-IX (paras 85-114)

Oudh Census Tables toward back no age detail (men, women, boys, girls) No sign of data for SR1 Rajput infanticide discussed Appendix J pdf 126   pdf 142 Sultanpoor boys 1880 boys 1157 girls (many more like that, usually smaller total) 
 

#### 1881 census -- 

Plowden 3 volums Report on the census of British India


1881 Panjab  3 vols #2 527 pages
Vol II (25057657) 

Plowden vol 3 via Hathi is useless Appendix stuff. 
People's Archive of Rural India has [Plowden](https://ruralindiaonline.org/library/rooms/census/1881/)

52 cites Hiaeker & Benrouille SBR 105-106 but less so in cities

From 1881 census (Plowden p. 54)   
    the actual disproportion between the sexes, though it might exist to some extent, and to what extent it was impossible then to say, was not anything like so great as had hitherto been portrayed by the census statistics.
 ... the nearer we approach to accuracy in the Census of a general population, the more clearly does the fact appear that there is nothing peculiar in this country in the proportion of the sexes; that if there are from 104 to 106 females to every hundred males in Europe, this proportion also obtains in India, that is in all parts of the country where female infanticide is unknown. The truth is that the great bulk of enumerators have been singularly obtuse in comprehending the fact that the counting of females was a matter of any importance in census work. To understand how this is, we must take into account **the low estimation in which females are held in this country,** and also the reticence of the people on all matters connected with their female relatives. In the registration of births and deaths the same error obtains. **The birth or death of a female child is considered such an insignificant matter,** especially among the lower classes of the population, that a great number escape registration in certain districts; and, from the causes adverted, to the numbering of the female population in 1871 was undoubtedly erroneous in so far that many were omitted in the Census schedules. But in districts where the Census work was well done it will be found that the female population is invariably in excess of the male; in fact, the general accuracy of the results of any district may be judged of by the way in which the proportions of the sexes have been recorded."

p56 regarding the Madras census 1881 arguing for big improvement in enumeratio

p57 girls less-effected by the famine

p178  It is obvious that a wave of infecundity has during the last few years swept over at least Northern India, and that the five years between 1876 and 1881 have seen a far smaller number of births than took place between 1871 and 1875.

1891 in SAOA [Census Reports - 1891](Census Reports - 1891)
Census of India, 1891. [General tables for British provinces and feudatory states](
https://www.jstor.org/stable/10.2307/saoa.crl.25318666) Poor quality copy -- Use another  [Hathi version](https://catalog.hathitrust.org/Record/100577017)  These have age data, pdf121p98

1901 in SOA [Vol 1A Part 2](https://www.jstor.org/stable/saoa.crl.25352838?seq=1#metadata_info_tab_contents) Good age/sex source, pdf71 pp. 64-102  Punjab 94p87

1901 Memorandum on the age tables and rates of mortality of the Indian ... Hardy, George Francis, Sir, 1855-1914.
p7 interesting on errors in counts

[Census of India Online](https://censusindia.gov.in/DigitalLibrary/browseyearwise.aspx)
1911 Punjab
1911  Appendices to the Imperial Tables, Part III, Vo-XIV, Punjab   NOT AGES


[back to top](#TOC)
<p>
LIFE TABLES
</p>
UN 1982 ^[https://www.un.org/en/development/desa/population/publications/manual/model/life-tables.asp]
  https://www.un.org/en/development/desa/population/publications/pdf/manuals/model/lifetables/annex1.pdf

Canada census https://www12.statcan.gc.ca/english/census01/products/standard/themes/Rp-eng.cfm?TABID=2&LANG=E&APATH=3&DETAIL=1&DIM=0&FL=A&FREE=0&GC=0&GK=0&GRP=1&PID=55521&PRID=0&PTYPE=55430,53293,55440,55496,71090&S=0&SHOWALL=0&SUB=0&Temporal=2001&THEME=37&VID=0&VNAMEE=&VNAMEF=


https://population.un.org/wpp/Download/Standard/Interpolated/  UN World Population Prospects


### South Africa 

At Hathi  1968-1995    Suid-Afrikaanse statistieke : opgestel deur die Buro vir Statistiek, Pretoria = South African statistics : compiled by the Buro of Statistics, Pretoria.  From 1992 or so, got age04 59 data

At Hathi 1970 South Africa Census (subject), No "full view"  -- maybe Columbia has temporary access? 

[1865 Cape of Good Hope](https://catalog.hathitrust.org/Record/011983572) full view

[1875 Cape of Good Hope](https://books.google.ca/books?id=6us1AQAAMAAJ) full view

[1891 Cape of Good Hope](https://www.dropbox.com/s/etbw2q7adkvzv3d/CapeGoodHope1891.pdf?dl=0) is in my Dropbox.^[Also, 1891 is at Gale Cenage 19th C Collections, says [WorldCat](https://www.worldcat.org/title/results-of-a-census-of-the-colony-of-the-cape-of-good-hope-as-on-the-night-of-sunday-the-5th-april-1891/oclc/12126896)]

1891 Cape Good Hope, 1891 Natal:  age by sex for ages 1,2,3,4, and quints thereafter  -- SR1various.wk4 in econhist has the start of tabulating the SR by age 

[births and deaths](https://catalog.hathitrust.org/Record/100811245)  But hoping Stat Reg has the data

1886-94 [Statistical register of the Colony of the Cape of Good Hope](https://catalog.hathitrust.org/Record/008616368)   [1893 full view](https://babel.hathitrust.org/cgi/pt?id=uc1.c2658750&view=1up&seq=9)

1907 [Statistical Register](https://books.google.ca/books?id=Ieo_AQAAMAAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false) I downloaded; see this for more links.

1904 Cape Good Hope



**1891 South Africa** has the heaping at age 0 relative to 1 

South Africa Census 1911, pp. 120-21 (populations by age and sex).
Census, 1911 ... Reports [vol. 1 (report/Part 1-4)](https://hdl.handle.net/2027/njp.32101031665449). South Africa.  
241-334 Part 1 Population and Dwellings pdf 241
242 Census Tables, 1911 ... show tables of pp 7-93  
335 Census 1911 Annexures to General Report, Part 2   337:Ages of the People
341p99 Afrik-language TOC   343p101 Part II  Comparative Summmary under/over 15
346p104 Table IV Numbers re Age 21 (under/over)  348p106 proportions under/over 21, 15
352p110 Table VII Union and each Province, Proportions re Age 21
354p112 Table VIII Whites 0-4 5-9 etc  1911 1904
360p118 Table XII Orange F S, Ages 1911 1904 0-5 
**single year 1 to 5** 
362-367 Table XIII Ages Union, and by Provinee, Urban+Rural  pdf362-367 **single year 1-5** 

368 Table XIV Proportions 374p132 Table XV proportions, by race    
380p138 Table XVI Urban, **single year 1-5** 144 Table XVII Proportions 392p150 TableXVIII proportions 396p154 Table XIX Numbers, single year, centres 2000 and more  402p160 Table XIX continued  408p166 TableXX RURAL    414p172 Table XXI rural proportions  420p178 Table XXII Proportions  424p182 Table XXIII Ages: Union, Provinces, Census Districts  440p198 Table XXIII continued         477- Census Tables Part III Education

[1926 census](https://catalog.hathitrust.org/Record/101697766), Third census of the population of the Union of South Africa, ... South Africa. 
Part II Ages (Europeans)  Part VIII a Natives b Coloured & Mixed  c Asiatics
 163Part3 341p1 372p32 occs & birthplaces

### various leads that we've glimpsed ###

[European Historical Population Samples Network](https://ehps-net.eu/databases) lists a wide range of micro data. Probably not useful for us. It includes the mosaic project, which seems like IPUMS for europe. [Historical Sample of the Netherlands](https://ehps-net.eu/databases/historical-sample-netherlands) indicates that Netherland used a population registry (rather than a census? or as well as?). I don't find any census-volume leads there.

  

[back to top](#TOC)